### ISSUE TITLE
Allow use of newer version of TypeScript?

### ISSUE THREAD

**Issue by FranklinChen** [ananthakumaran/tide#1]
Would it be feasible to add support for using a newer version of TypeScript? I'm currently trying `typescript@next` to get 1.6.0-dev features but this means `tide` complains about new constructs.

**Comment by ananthakumaran** [comment]
You can clone & rebuild the contents inside tsserver directory.  Makefile contains the required steps, unfortunately the patch doesn't apply in TypeScript master branch.

**Comment by ananthakumaran** [comment]
master now supports 1.6.2
