### ISSUE TITLE
error when opening in .tsx files

### ISSUE THREAD

**Issue by subash-a** [ananthakumaran/tide#10]
getting the following error when I open a .tsx file in my editor _Error from syntax checker typescript-tide: Error processing request. Could not find file: 'file/at/path.tsx'._  The plugin works flawlessly when I use it on .ts files. Any pointers on what I might be doing wrong would be great

**Comment by ananthakumaran** [comment]
did you check the example in https://github.com/ananthakumaran/tide/tree/master/example. If you can't get it working, post a minimal case(tsconfig.json, tide specific emacs config and a tsx file)

**Comment by subash-a** [comment]
suprisingly, I created a copy of your example folder and tried to see if the type hints were being shown, and it still was not. I am using the exact same configuration posted on the readme and the same example folder where I try to access the reactComponent.tsx file. Is there a possiblity that some other package I installed is causing this problem. As before .ts files work like a charm, not the .tsx file.

**Comment by ananthakumaran** [comment]
Well, it would be difficult for me to guess what might be wrong without any pointers. use `M-x toggle-debug-on-error` and see if there is some other error which prevents web-mode-hook from being executed. Alternatively you could run the setup code using `M-:` and see if anything goes wrong.

**Comment by subash-a** [comment]
Ok @ananthakumaran I will try your suggestions and reopen this issue if I am not able to find any external causes. I also wanted to let you know. I commented out my entire init.el file except for the parts which were supposed to do the tide setup part and it still was a problem. Anyways I will try to reproduce it again and see if I can get a place where it fails inside the code.

**Comment by subash-a** [comment]
@ananthakumaran Apologies for the issue raised earlier, it seemed to be a problem on my end with the tide package not being upgraded to the latest version. Thanks for your time. Cheers
