### ISSUE TITLE
How to remap C-c d in tide-mode

### ISSUE THREAD

**Issue by 1-9** [ananthakumaran/tide#101]
I am not able to remap key in tide-mode can you help?

**Comment by ananthakumaran** [comment]
```elisp
(add-hook 'tide-mode-hook (lambda ()
  (local-set-key (kbd "C-c x") #'tide-documentation-at-point)))
```

The above should work. Please post the error details if you run into any problems

**Comment by 1-9** [comment]
That works like a charm thanks. Are there any plans to improve the syntax highlighting for typescript, I feel the colors are bit too bland.

**Comment by ananthakumaran** [comment]
please open an issue in https://github.com/ananthakumaran/typescript.el with specific details. This project doesn't deal with syntax highlighting.
