### ISSUE TITLE
Customize indentation style

### ISSUE THREAD

**Issue by gabry2105** [ananthakumaran/tide#104]
Hi,
I would like know if it is possible customize the indentation style for the ':' operator when break line at return type. 
For example:

```
interface IMyInterface {
  /* I have to resepect a max-column rule, so I break the
   * line at return type of the method.
   */
    methodWithALongName(param: TypeWithALongName)
    : AnOtherTypeWithALongName // <-- Aligned with the method name 
}
```

And I would like this result:
```
interface IMyInterface {
  /* I have to resepect a max-column rule, so I break the
   * line at return type of the method.
   */
    methodWithALongName(param: TypeWithALongName)
        : AnOtherTypeWithALongName // <-- Indented : operator.
}
```

How can I configure tide to have that?

**Comment by ananthakumaran** [comment]
tide supports the following format options https://github.com/Microsoft/TypeScript/blob/master/lib/protocol.d.ts#L1713-L1735. Look at the readme for how to enable formatting on save. As for the specific indent style, tide is just a thin wrapper around the `tsserver` binary https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-(tsserver). The question would be better directed to the TypeScript repo.
