### ISSUE TITLE
Slow Startup (tsserver)

### ISSUE THREAD

**Issue by mzgnr** [ananthakumaran/tide#106]
Tsserver starts successfully but blocks UI for almost 2 seconds.

**Comment by josteink** [comment]
From what I can tell starting tsserver is pretty fast. Just doing it on the command-line for fun takes almost no time (500ms?).

If I were to take a random guess what's slowing us down is that after the server is started, we need to configure it, and inform it which files we are editing We do this in [`tide-setup`](https://github.com/ananthakumaran/tide/blob/master/tide.el#L1093). This in turn [fires off two commands](https://github.com/ananthakumaran/tide/blob/master/tide.el#L1073-L1075
) to tsserver.

Good thing for us I wasn't happy guessing. Profiling data shows me that these finishes in roughly 2 milliseconds.

What I seem to be able to reproduce fairly consistently though, is that the "lag" in opening the first TS-file (where we start the server and all that stuff) happens *after* these messages are fired.

To me that implies that the slowdown happens after all "regular" tide code has run. Could this be Emacs-internal things like fontification, syntax-tables and all that?

Have you tried disabling most of your mode-hooks to see how this runs on a "clean" system? Could it be some of your other customizations?

**Comment by ananthakumaran** [comment]
Can you reproduce it reliably? There is a way to run tide in sandbox mode https://github.com/ananthakumaran/tide/blob/master/Makefile#L49 This might be helpful to rule out other plugins
