### ISSUE TITLE
Add ability to navigate to named type

### ISSUE THREAD

**Issue by josteink** [ananthakumaran/tide#107]
One feature found in many IDEs is the ability to search for a type-name and navigate directly to it, often with a `completing-read` like interface which is populated with all known types.

Would this be possible to add?

I've fooled around with the following code, which *almost* but not quite works:

````emacs lisp
(defun tide-filter-types (body)
  (let ((result))
    (dolist (item body)
      (let ((kind (plist-get item :kind)))
        (when (or
               (string-equal kind "interface")
               (string-equal kind "type"))
          (setq result (append result (list (plist-get item :name)))))))
    result))

(defun tide-get-types ()
  "Gets all known types (by cheating and using the completions system)"

  (save-excursion
    (goto-char (point-max))
    (let* ((command-args `(:file ,(buffer-file-name) :line ,(tide-line-number-at-pos) :offset ,(tide-current-offset)))
           (command-response (tide-send-command-sync "completions" command-args))
           (response-body (plist-get command-response :body))
           (type-names (tide-filter-types response-body)))
      type-names)))

(defun tide-test-get-types ()
  (interactive)
  (let ((types (tide-get-types)))
    (setq my-test-get-types types)
    (completing-read "Select type to navigate to: " types)))
````

What it does is this:

* Move cursor to end of file to ensure we're not in any completion-context which will limit our results
* Request a completion from tsserver (which outside a completion prefix, should include "all" possible completions)
* We take the response and filter for types.
* We let the user choose a type.

This approach has several drawbacks and problems:

* We ask tsserver for way more than we need. So its slow.
* It will only show *imported* types.
* Even worse, it seems to only include types which has static members (because why on earth would we want to complete a type-name if we can't use it for a invocation in this otherwise empty statement-context?)

Checking the [tsserver protocol](https://github.com/Microsoft/TypeScript/blob/master/src/server/protocol.ts) I found no such command. The closest seems to be `navbar` or `navtree`, but they only return types from the currently loaded file. Iterating over all known files in the project and aggregating the results would probably work, but I'm going to guess it will be so slow it won't be close to usable.

Do you have any idea of another possible approach here? Or will we have to bugger Microsoft and request a new command to be added to tsserver before this can be implemented?

**Comment by josteink** [comment]
Looking at [Visual Studio Code](https://github.com/Microsoft/vscode), pressing `Ctrl P` while in a TypeScript-project and then prefixing your search with `#` seems to search all types in the project.

It would be interesting to see how Microsoft implemented this type-search there....

**Comment by ananthakumaran** [comment]
Did you try `navto`? vscode seems to be using that https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/features/workspaceSymbolProvider.ts

**Comment by josteink** [comment]
Thanks for the hint! That looks like it can get us somewhere.

There's just one catch: You need to provide a search-value to get results. That is: You cannot send a empty search and get "all" results back.

This means we need to be able to create a feedback-loop where typing more triggers a new search. Using a basic `completing-read` probably isn't sufficient for that...

#emacs on Freenode launching a manual input field and using `run-with-idle-timer` and what not, but that immediately makes this a order of magnitude more complex.

I'll prototype some simple "search first & select afterwards" based approach and see how well/bad that works out in practice. It'll probably be better  than nothing, right?

**Comment by josteink** [comment]
This is my code so far. It kinda works. It's better than nothing, but probably needs some cleaning up before submitting as a PR:

````elisp
(defun tide-get-types ()
  "Search for types and navigate directly to them."
  
  (interactive)
  (let* ((default (substring-no-properties (region-str-or-symbol)))
         (type (read-string "Search for type: " default))
         (response (tide-command:navto type))
         (types (tide-parse-types-response response))
         (type-names (tide-get-type-names types))
         (selected-type-name (completing-read "Select type to navigate to: " type-names)))
    (tide-go-to-named-type selected-type-name types)))

(defun tide-command:navto (type)
  (tide-send-command-sync "navto" `(:file ,buffer-file-name :searchValue ,type)))

(defun tide-parse-types-response (response)
  (tide-filter-types
   (plist-get response :body)))

(defun tide-filter-types (body)
  (-filter (lambda (item)
             (let ((kind (plist-get item :kind)))
               (or (string-equal "class" kind)
                   (string-equal "interface" kind)
                   (string-equal "type" kind)
                   (string-equal "enum" kind))))
           body))

(defun tide-get-type-name (item)
  (plist-get item :name))

(defun tide-get-type-names (types)
  (-map #'tide-get-type-name types))

(defun tide-go-to-named-type (name typelist)
  (let* ((type (tide-get-type-from-name name typelist))
         (file (plist-get type :file))
         (line (tide-plist-get type :start :line))
         (column (tide-plist-get type :start :offset)))
    (find-file file)
    ;; in case already open!
    (goto-char (point-min))
    (forward-line (1- line))
    (forward-char (1- column))))

(defun tide-get-type-from-name (name typelist)
  (let* ((types (-filter
                (lambda (item) (string-equal name (tide-get-type-name item)))
                typelist)))
    (car types)))
````

It has some "bonus" features like automatically picking up the symbol you're hovering over...

So If you're hovering over a something like a class name in a signature ("KittenFinder") and just press enter, by default you'll find related classes like ("KittenFinder", "KittenFinderView", "KittenFinderViewModel" etc).
