### ISSUE TITLE
How to get tslint to work with js2 mode highlighting

### ISSUE THREAD

**Issue by 1-9** [ananthakumaran/tide#109]
I currently use js2-mode for typescript syntax highlighting, but I can't get my tslint to work. I use flycheck, is there any way to have js2-mode-highlighting without loosing any functionality of tide mode. Here is my configuration I use

```
(use-package tide
  :ensure t
  :mode ("\\.ts\\'" . js2-mode)
  :init
  (defun setup-tide-mode ()
    (interactive)
    (when (string-match "\\.ts\\'" buffer-file-name)
      (setq tide-tsserver-executable "node_modules/typescript/bin/tsserver")
      (tide-setup)
      (flycheck-mode +1)
      (setq flycheck-check-syntax-automatically '(save mode-enabled)
            js2-mode-show-parse-errors          nil
            js2-mode-show-strict-warnings       nil)
      (eldoc-mode +1)))
  (add-hook 'js2-mode-hook #'setup-tide-mode)
  :config
  (define-key tide-mode-map (kbd "C-c d") nil)
  (define-key tide-mode-map (kbd "C-c b") 'tide-format))
```

Thanks.

**Comment by ananthakumaran** [comment]
Users normally use typescript-mode to edit ts file. All the default settings are geared towards this usage. There is nothing wrong with trying to use js2-mode for ts file, just that you would have to figure out how to initialize and tie together all the different pieces.

for your case, you would have to find out which checkers are enabled for js2-mode. checkers are defined as a list and run one after another. you probably have to add tslint checker to your current list. example `(flycheck-add-next-checker 'current-checker-for-js2-mode '(warning . typescript-tslint) 'append)`. Please look at flycheck documentation for details.
