### ISSUE TITLE
Jump to definiton in import doesn't work if a file extension is "jsx"

### ISSUE THREAD

**Issue by chessman** [ananthakumaran/tide#110]
Suppose we have import:
```
import Test from './Test.jsx'
```
<M-.> on string "Test" works only if file `Test` has extension ".js" but fails with extension ".jsx".

**Comment by ananthakumaran** [comment]
I tried with a .jsx file and it seems to work. Can you post the request/response from tsserver for the specific command `{"command":"definition"`. Look at debugging section in readme for how to enable logging.

Mine looks like below
```
Info 196  request: {"command":"definition","seq":"335","arguments":{"file":"/Users/ananthakumaran/work/repos/tide/example/reactComponent.jsx","line":3,"offset":12}}
Perf 197  335::definition: elapsed time (in milliseconds) 1.8027
Info 198  response: {"seq":0,"type":"response","command":"definition","request_seq":"335","success":true,"body":[{"file":"/Users/ananthakumaran/work/repos/tide/example/sample.jsx","start":{"line":1,"offset":1},"end":{"line":3,"offset":2}}]}
```

**Comment by chessman** [comment]
I added the repro to github:
https://github.com/chessman/tide-import-test
[tss.log](https://github.com/chessman/tide-import-test/blob/master/tss.log)

**Comment by ananthakumaran** [comment]
```
response: {"seq":0,"type":"response","command":"definition","request_seq":"8","success":true,"body":[]}
```

Looks like a problem with tsserver. Tide can't do much if tsserver returns empty `body`. Could you open an issue in `microsoft/Typescript` repo

**Comment by chessman** [comment]
Ok, I will try to do that. Thanks for your help!
