### ISSUE TITLE
Change C-c d binding for show documention

### ISSUE THREAD

**Issue by CSRaghunandan** [ananthakumaran/tide#111]
All key bindings which start with the prefix `C-c` followed by a letter(s) are reserved for the end users of emacs and its standard for packages to not bind any keys with this prefix. I have a few key bindings which start with `C-c d` all those are overwritten by tide :(

Maybe it's better to bind it to something like `C-c C-d` or `C-c C-t`.

**Comment by ananthakumaran** [comment]
agree, it was a mistake. I am not a fan of super long default key bindings. Let's leave the decision to the user.
