### ISSUE TITLE
Add support for code-actions/code-fixes

### ISSUE THREAD

**Issue by josteink** [ananthakumaran/tide#116]
`tsserver` supports doing various "code actions" (or [code fixes](https://github.com/Microsoft/TypeScript/blob/master/src/server/protocol.ts#L94) depending on whether you read the TypeScript source or the TypeScript blog). These can be anything the server deems useful.

Starting with [TypeScript 2.2](https://blogs.msdn.microsoft.com/typescript/2017/02/22/announcing-typescript-2-2/) there's now a bunch of new and **very interesting** code actions available:

* Adding missing imports
* Adding missing properties
* Adding forgotten `this.` to variables
* Removing unused declarations
* Implementing abstract members

If getting all these features into `tide` is only a matter of adding a new command or two, that seems like a very worthwhile effort.

**Comment by josteink** [comment]
Scimming the source it seems the following needs to be done:

* We need to issue a [`CodeFixesRequest`](https://github.com/Microsoft/TypeScript/blob/master/src/server/protocol.ts#L400-L403) with our current location in the solution.
* The [response](https://github.com/Microsoft/TypeScript/blob/master/src/server/protocol.ts#L1393-L1396) will contain zero or several [`CodeAction`](https://github.com/Microsoft/TypeScript/blob/master/src/server/protocol.ts#L1398-L1403)-instances. We'll need to present these to the user. Good for us each action has a server-provided `description` field :)
* Once a particular action is chosen by the user, we need to execute the associated [`FileCodeEdits`](https://github.com/Microsoft/TypeScript/blob/master/src/server/protocol.ts#L1388-L1391) (note: not one! plural!)
* Each `FileCodeEdit` contains the changes needed to be made to a single file. These are encoded in a array of [`CodeEdit`](https://github.com/Microsoft/TypeScript/blob/master/src/server/protocol.ts#L1363-L1386)-instances.
* The `CodeEdit`-instance basically tells us to replace the text between `start` and `end` with a new one (`newText`), which should be trivial.

All in all, this looks like more than a 2-liner, but nothing fundamentally hard. This is definitely doable. So who's volunteering for eternal Emacs fame and glory? :D

**Comment by josteink** [comment]
To anyone who wants to doodle further at this, this was my doodle-code:

````elisp
(defun tide-command:getCodeFixes ()
  (tide-send-command-sync "getCodeFixes" `(:file ,buffer-file-name
                                  :startLine ,(tide-line-number-at-pos)
                                  :startOffset ,(tide-current-offset)
                                  :endLine ,(tide-line-number-at-pos)
                                  :endOffset ,(+ 0 (tide-current-offset))
                                  :errorCodes ,(list 2304 2339 2377 2420 2503 2515 2653 2663 2686 2689 6133 6138 17009))))


(defun my-tide-sublist (plist prop)
  (let ((result))
    (dolist (item plist)
      (setq result (append result (list (plist-get item prop)))))
    result))

(defun my-tide-test-get-codefixes ()
  (interactive)
  (let ((response (tide-command:getCodeFixes)))
    (setq my-test-get-fixes response)

    (completing-read "Select type to navigate to: " (my-tide-sublist (plist-get response :body) :description))))
````

**Comment by josteink** [comment]
@cc: AndyMoreland

Any chance you can help me out and tell me what I'm doing wrong here? :)

**Comment by josteink** [comment]
cc: @AndyMoreland

Any chance you can help me out and tell me what I'm doing wrong here? :)

**Comment by josteink** [comment]
I don't get what I'm doing wrong here. At all.

If I start tsserver from the command line and manually issue a "configure", "open" and then a "getCodeFixes" for my single file, on a single point (+1), for the single error 2663, which should be present at that point.. *Then* I get the codefix. All is fine.

When I try to force the same above.... Using tide-send-command-sync, I always just get an empty response.

Anyone have any good advice on how to proceed here?

**Comment by josteink** [comment]
Following code actually gets a list back. Yay!

````elisp

(defun tide-command:getSupportedCodeFixes ()
  (tide-send-command-sync "getSupportedCodeFixes" '()))

;; (setq tide-supported-codefixes nil)
(defvar tide-supported-codefixes nil)
(defun tide-get-supported-code-fixes ()
  (when (not tide-supported-codefixes)
    (setq tide-supported-codefixes
          (plist-get (tide-command:getSupportedCodeFixes) :body)))
  tide-supported-codefixes)

(defun tide-command:getCodeFixes ()
  (tide-send-command-sync "getCodeFixes" `(:file ,(buffer-file-name)
                                                 :startPosition ,(point)
                                                 :endPosition ,(+ 1 (point))
                                                 :errorCodes ,(tide-get-supported-code-fixes))))


(defun my-tide-sublist (plist prop)
  (let ((result))
    (dolist (item plist)
      (setq result (append result (list (plist-get item prop)))))
    result))

(defun my-tide-test-get-codefixes ()
  (interactive)
  (let ((response (tide-command:getCodeFixes)))
    (setq my-test-get-fixes response)
    ;; (prin1 response)
    (completing-read "Select your awesome fix: " (my-tide-sublist (plist-get response :body) :description))))
````

It's not all good news though. When executing `tide-command:getSupportedCodeFixes` I get the following two results: `("2377" "17009")`.

When issuing the same command from the terminal for the same project... I get this:

````
["2304","2339","2377","2420","2503","2515","2653","2663","2686","2689","6133","6138","17009"]
````

What's up with that massive difference? Why am I not getting all code-fixes?

**Comment by josteink** [comment]
**New update:** The following code actually seems to work, but I need to patch `tide` to make it happen. Woo!

````elisp

;; PATCHED TIDE FUNCTION:
(defun tide-parse-error (response checker)
  ;; (setq my-tide-error-response response)
  (-map
   (lambda (diagnostic)
     (let* ((start (plist-get diagnostic :start))
            (line (plist-get start :line))
            (column (tide-column line (plist-get start :offset))))
       (flycheck-error-new-at line column 'error (plist-get diagnostic :text)
                              :checker checker
                              ;; this is the TIDE patch. add an error-code to error.
                              :id (plist-get diagnostic :code))))
   (let ((diagnostic (car (tide-plist-get response :body))))
     (-concat (plist-get diagnostic :syntaxDiag)
              (plist-get diagnostic :semanticDiag)))))

;; rest is new code

(defun tide-get-flycheck-errors-ids-at-point ()
  (-map #'flycheck-error-id (flycheck-overlay-errors-at (point))))

(defun tide-command:getCodeFixes ()
  (tide-send-command-sync "getCodeFixes" `(:file ,(buffer-file-name)
                                                 :startPosition ,(point)
                                                 :endPosition ,(+ 1 (point))
                                                 :errorCodes ,(tide-get-flycheck-errors-ids-at-point))))


(defun my-tide-sublist (plist prop)
  (let ((result))
    (dolist (item plist)
      (setq result (append result (list (plist-get item prop)))))
    result))

(defun my-tide-test-get-codefixes ()
  (interactive)
  (let ((response (tide-command:getCodeFixes)))
    (setq my-test-get-fixes response)
    ;; (prin1 response)
    (completing-read "Select your awesome fix: " (my-tide-sublist (plist-get response :body) :description))))
````

To process the actual codefix, I think we can re-use some existing [tsunami-code](https://github.com/AndyMoreland/tsunami/blob/master/tsunami-emacs/tsunami-code-fix.el).

Maybe this feature won't be too hard to add?

**Comment by josteink** [comment]
**Update:**

I have cooked together some code which for me seems to work. Issuing a PR, and then all the picky people can start ripping my code apart :)

**Comment by KevinVillela** [comment]
Does this actually add support for performing the code fixes? When I try it in examples/test.ts for any the examples at https://blogs.msdn.microsoft.com/typescript/2017/02/22/announcing-typescript-2-2/, I just get "No code-fixes available". Sometimes, the compiler error will even say "Did you mean <code-fix>", such as "Did you mean the class variable isAdmin?", but M-x tide-fix still returns "No code-fixes available". Am I doing something wrong here?

**Comment by josteink** [comment]
In theory "everything" should be supported. 

There's limitations in the current  implementatio though: it will only provide code fixes for things which are represented as errors by flycheck. You may need to save your buffer to trigger the error-check, which enables the fix. 

This technicality will probably also exclude some of the fixes mentioned in the blog like removing unused imports. 

When I've fooled around with this for a while, and have a better feeling for what works and not, I might try to find a way around this limitation.

Until then anyone else is free to take a stab at this problem too. But for now this should be a major improvement over no support at all :)

**Comment by KevinVillela** [comment]
Totally agree that some support is better than none! 

I was actually able to get this to work by updating the local copy of TSServer that we use at work. Sorry for the false alarm. Thanks, really appreciate this functionality!
