### ISSUE TITLE
Formatting/indentation issue w/ TSX + generics

### ISSUE THREAD

**Issue by faber** [ananthakumaran/tide#119]
First and foremost: Thank you! Tide is amazing!

I've noticed that certain combinations of TSX and generics seem to break the indentation.  Based on the syntax coloring, I think what happens is that it incorrectly is classifying `{}` as "interpolated js inside of a TSX block", rather than regular braces... here's an example screen shot:

![screen shot 2017-02-25 at 11 58 34 am](https://cloud.githubusercontent.com/assets/43680/23334381/d9f73d8e-fb51-11e6-8388-a2d8d0f066d4.png)

(Sorry for the contrived example, I was trying to reproduce it with as little code as possible.)

Notice the closing bracket of the `MyThing` class aligns w/ the opening bracket, rather than all the way to the left.  It's the type annotation w/ a generic on the final line that triggers this case, if you either remove that line, or just do `export default MyThing;` without the annotation, the issue doesn't manifest.

Also, tho its not shown in that screen shot, if I auto indent the buffer, that final export line will be two spaces in from the left.

I can try to find some other scenarios that trigger this if its helpful, I know i've encountered others but it's been hard to see exactly what causes it.

In case its helpful for testing, here's the code above copy/pastable:

```typescript
import * as React from 'react';

interface Props {
  name: string
}

class MyThing extends React.Component<Props, {}> {
  render() {
    return <span>hi</span>;
  }
}

export default MyThing as React.ComponentClass<Props>;
```

My setup includes:
```
  tide               20170224.2227 installed             Typescript Interactive Development Environment
  typescript-mode    20161130.1944 installed             Major mode for editing typescript
```
and 

```elisp
(setq typescript-indent-level 2)
(defun setup-tide-mode ()
  (interactive)
  (tide-setup)
  (flycheck-mode +1)
  (setq flycheck-check-syntax-automatically '(save mode-enabled))
  (eldoc-mode +1)
  (tide-hl-identifier-mode +1))

(add-hook 'typescript-mode-hook #'setup-tide-mode)

(add-hook 'web-mode-hook
          (lambda ()
            (when (string-equal "tsx" (file-name-extension buffer-file-name))
              (setup-tide-mode))))

;; format options
(setq tide-format-options
      '(:insertSpaceAfterFunctionKeywordForAnonymousFunctions
        nil
        :placeOpenBraceOnNewLineForFunctions
        nil))
```

**Comment by ksjogo** [comment]
tide is not the major-mode doing indentation etc. 
That is either typescript-mode or web-mode.
IMO web-mode is superior for all tsx? stuff.
You could try web-mode out and just continue using tide-mode.

**Comment by ananthakumaran** [comment]
as @ksjogo mentioned, web-mode is better for editing tsx files than typescript-mode. You could try to use `tide-format` and see if it does better.

**Comment by faber** [comment]
Gotcha ok, actually I am using web-mode on tsx files, wasn't sure which mode was responsible for the indentation.  I guess I should raise this issue w/ them in that case then, yea?

**Comment by ananthakumaran** [comment]
Also, to clarify, tide by itself doesn't do any formatting. It provides `tide-format`, which in turn delegates the work to [tsserver](https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-(tsserver)). The issue should either be opened at typescript-mode(which doens't support tsx at the moment) or Typescript repo incase `tide-format` doesn't work

**Comment by faber** [comment]
Cool, sounds like in my case it may be web-mode that's providing the formatting, I believe I have tide-format turned off.  I'll raise it w/ them.  Sorry for the noise! Marking this as closed.
