### ISSUE TITLE
option for setting tsserver path

### ISSUE THREAD

**Issue by subash-a** [ananthakumaran/tide#12]
At present the `tsserver` is the one which comes with the project, can there be a mechanism provided to explicitly set the `tsserver` path? The reason this would be helpful is I work on a project which uses the latest tsserver (`typescript@next` version) and some of the features are not detected by the stock `tsserver` provided along with the package. I am aware that I can set the `tide-tsserver-directory` directly and restart to make it work, but would be better if there was a way to do that without changing package specific variables.

P.S. If you are short of time I can help by creating a PR*

(* - I am not very good at writing elisp programs)

**Comment by ananthakumaran** [comment]
Couple of issues with providing a way to configure tsserver path.
1. The error api comes with tsserver is async and it doesn't play well with the current design of tide and flycheck and introduces lot of edge cases, so I have settled on a patch to make it sync https://github.com/ananthakumaran/tide/blob/master/geterr.patch.
2. Providing a config option is  indirect way of saying that a single version of tide will support different version of tsserver, which is a lot more work than just supporting a single version.

**Comment by subash-a** [comment]
Thanks for the explanation @ananthakumaran let me see if I can spend some time over the weekend trying to play around with your code and will let you know if we can accomplish something. Thanks for taking the time. Closing this issue for now until further progress from my end.

**Comment by jbms** [comment]
This is supported by pull request #21.
