### ISSUE TITLE
how to fix "generators are only available  when targeting ECMAScript 2015 or higher"

### ISSUE THREAD

**Issue by xcwen** [ananthakumaran/tide#124]
my tsconfig.json

```json 

{
    "compilerOptions": {
        "module": "commonjs",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "es2015"
    },
    "files": []
}
```

**Comment by xcwen** [comment]
![deepinscrot-1824](https://cloud.githubusercontent.com/assets/1539162/23576047/f866f114-00d4-11e7-9d30-7e6d5ef18af8.png)

**Comment by josteink** [comment]
As far as I can see, this may not really be a tide-issue specifically, but more of a general TypeScript issue (with TypeScript installations often being several on a single machine..).

If you in a console, go to the project directory and type `tsc`, do you get the same error?

A few other questions, to help us narrow things down:

* What version of typescript are you using? Latest?
* What version of tide are you using? Latest? MELPA stable? An older version?

Let us know what you find out, and maybe we can help :)

**Comment by xcwen** [comment]
thanks , i add the file to tsconfig.json . and it's ok .
```
{
    "compileOnSave": true,
    "compilerOptions": {
        "jsx": "React",
        "module": "commonjs",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "ES6",
        "outDir": "../app/"
    } ,


    "include": [
        "controller/*.ts",
        "*.d.ts",
        "*.ts"
    ],
    "files":[
        "egg_global.d.ts"
    ]
}

```
