### ISSUE TITLE
can't use tide with symlinked folders

### ISSUE THREAD

**Issue by nahuel** [ananthakumaran/tide#126]
Starting with TS 2.1 you can use symlinks to organize your code. (See https://github.com/Microsoft/TypeScript/issues/9552 and https://github.com/Microsoft/TypeScript/pull/12020 ). This is useful for example to share a common folder between browser and server projects. But when you open a file in a symlinked folder using tide, tide tries to find a `tsconfig.json` by backtracking from the resolved symlink destination. I think this is wrong, see the following example:

```sh
cd /tmp
mkdir -p shared proy/src
echo 'import * as M from "moment"'            > shared/m-shared.ts
echo 'import * as S from "./shared/m-shared"' > proy/m-proy.ts

cd proy
ln -s ../shared shared

npm init -y
npm install --save-dev typescript moment
./node_modules/.bin/tsc --init

./node_modules/.bin/tsc  # => OK
```

If you now open `/tmp/proy/m-proy.ts` in emacs, everything goes ok, but if you open `/tmp/proy/shared/m-shared.ts` , then tide will complain it can't open tsserver. 

Note I'm using:

```elisp
(setq tide-tsserver-executable "node_modules/typescript/bin/tsserver"	
      tide-tsserver-directory  "node_modules/typescript/lib")
```

If you use a global tsserver, tide will show the `moment` library cannot be resolved (because tide started an extra tsserver only for `/tmp/shared`, which has no dependencies).

I think the symlink mangling can be improved.

**Comment by josteink** [comment]
Thanks for the very detailed error-report. That kind of stuff is appreciated.

Now, with that said, I think the tide-codebase is almost 100% consistent in how it resolves file-names (which includes paths): It uses emacs's built in buffer-local variable [`buffer-file-name`](https://github.com/ananthakumaran/tide/blob/master/tide.el#L477).

I did some quick testing and this does *not* mangle the symlinked subfolders, and I thought whatever goes wrong is probably happening in [`tide-project-root`](https://github.com/ananthakumaran/tide/blob/master/tide.el#L141-L152). But I went testing, and it all behaves as it should.

Finally I went back and replayed your exact scenario (except in `~/test-tide`) and for me it all works perfectly. For reference: I've tested this on Fedora Linux with Emacs 25.1.

Are you using a Mac or some other OS where there's a chance of the underlying C-functions we rely on having another, platform-specific implementation?

**Comment by nahuel** [comment]
Sorry, I tested this wrong. I had `/tmp/shared/m-shared.ts` already open in a non visible buffer, then when I opened `/tmp/proy/shared/m-shared.ts` , emacs switched to the existing buffer by detecting it was the same file, and keep `buffer-file-name` as `/tmp/shared/m-shared.ts`. Now retesting this from a clean emacs session and opening only `/tmp/proy/shared/m-shared.ts` seems like tide is working ok! And `buffer-file-name` is set to `/tmp/proy/shared/m-shared.ts`. You can close this issue. Thanks for your quick reply.

(I'm using Ubuntu 16.10)

**Comment by josteink** [comment]
Thanks for the quick feedback! Guess this is good to close then :)
