### ISSUE TITLE
tide not seeing my node binary

### ISSUE THREAD

**Issue by jrab89** [ananthakumaran/tide#13]
```elisp
(getenv "PATH")
;; "/Users/jeffrabovsky/.nvm/versions/node/v5.5.0/bin/:/usr/bin/:/bin/:/usr/sbin/:/sbin/:/opt/homebrew-cask/Caskroom/emacs/24.5-1/Emacs.app/Contents/MacOS/bin-x86_64-10_9/:/opt/homebrew-cask/Caskroom/emacs/24.5-1/Emacs.app/Contents/MacOS/libexec-x86_64-10_9/"

(shell-command "node -v")
;; "v.5.5.0"
```

But when I run `M-x tide-restart-server` in a buffer within my Typescript project I get: `Searching for program: no such file or directory, node`

Any ideas what's going on here? Thanks

**Comment by ananthakumaran** [comment]
I guess the `exec-path` doesn't include node's bin directory. checkout http://www.emacswiki.org/emacs/ExecPath for how to set it.

**Comment by jrab89** [comment]
Yep turns out my node's bin directory wasn't in `exec-path`, after adding it tide works as expected. Thanks for your help!
