### ISSUE TITLE
tide-document-at-point (wrong-number-of-arguments (1 . 1) 0) ?

### ISSUE THREAD

**Issue by hexa00** [ananthakumaran/tide#136]
Hi,
When trying tide-document-at-point I get:

Debugger entered--Lisp error: (wrong-number-of-arguments (1 . 1) 0)
  tide-command:quickinfo()
  tide-documentation-at-point()
  funcall-interactively(tide-documentation-at-point)
  call-interactively(tide-documentation-at-point record nil)
  command-execute(tide-documentation-at-point record)
  execute-extended-command(nil "tide-documentation-at-point" "tide-docu")
  funcall-interactively(execute-extended-command nil "tide-documentation-at-point" "tide-docu")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

emacs --version
GNU Emacs 25.1.1
melpa:  tide               20170406.2103 

Any ideas ?

Thanks,

**Comment by ananthakumaran** [comment]
fixed in master

**Comment by hexa00** [comment]
Yep seems like with 
 tide               20170412.541

It's fixed too.

Thanks!
