### ISSUE TITLE
Debugging support ?

### ISSUE THREAD

**Issue by hexa00** [ananthakumaran/tide#137]
That's the only thing missing for me with tide.

Something on top of realgud + trepanjs ?

**Comment by josteink** [comment]
Yes please. Pull requests accepted :)

**Comment by arichiardi** [comment]
We could also adapt [indium Repl support](https://indium.readthedocs.io/en/latest/repl.html#code-evaluation-context) to works in here, probably only phrase/statement detection is going to change from [their interaction file](https://github.com/NicolasPetton/Indium/blob/master/indium-interaction.el).

**Comment by josteink** [comment]
Closing this one because of lack of activity.

If someone wants to discuss how to get this done, feel free to re-open this issue to facilitate further discussion.
