### ISSUE TITLE
[New feature] tide-reference shows preview of code

### ISSUE THREAD

**Issue by skormel** [ananthakumaran/tide#138]
To make a great user experience, I suggest to include a navigation mode from the \*tide-references\* results, like rgrep does. When n or p are keypressed, it should navigate through \*tide-references\* list (as nowadays) but in the other window, change to corresponding file position of the pre-selected reference (like a preview) and only when you press  Enter o mouse click change to the selected reference.

What do you think about this feature?

Best Regards
Antonio.

**Comment by josteink** [comment]
It should already do this using the `next-error` and `previous-error` mechanism (same as `flycheck`). I've mapped that to `F7` and `F8`.

Have you tried those?

**Comment by skormel** [comment]
> It should already do this using the next-error and previous-error mechanism (same as flycheck). I've mapped that to F7 and F8.

If I do M-x next-error I get `No more Flycheck errors`

**Comment by josteink** [comment]
Are you doing that in the `*references*` buffer or a regular `typescript-mode` buffer?

**Comment by skormel** [comment]
At \*references\* buffer

**Comment by josteink** [comment]
What happens if you just select a reference (to move into the `typescript-mode` buffer) and try to navigate using  `next-error` and `previous-error` then?

**Comment by josteink** [comment]
If so, that's no good, and really should be considered a bug... Although I can see how `flycheck` may interfere with our references-result, and how resolving that conflict can be difficult.

Going back to your original post...

> When n or p are keypressed, it should navigate through *tide-references* list (as nowadays) but in the other window, change to corresponding file position of the pre-selected reference (like a preview) and only when you press Enter o mouse click change to the selected reference.

Isn't this behaviour the typical behaviour one expects from [follow-mode](https://www.gnu.org/software/emacs/manual/html_node/emacs/Follow-Mode.html)? (Which I just recently learned about)

It would be interesting to see how much work it would be to properly implement support for `follow-mode` in `tide`.

**Comment by kreedz** [comment]
The same thing with `No more Flycheck errors`.
Works only if I disable flycheck with `flycheck-mode` and then you can do `next-error`, now you can enable flycheck with `flycheck-mode` and `next-error` now is working too.

**Comment by josteink** [comment]
> Works only if I disable flycheck with flycheck-mode and then you can do next-error which will work at this time, now you can enable flycheck with flycheck-mode and next-error now is working too.

Interesting. Where do you turn of flycheck? In the references buffer? Or all other buffers?

Would it be possible for us to do this in our own code, to make references work?

**Comment by kreedz** [comment]
>Where do you turn of flycheck? In the references buffer? Or all other buffers?
Not in the references buffer, I'm turn off flycheck in the buffer where I starting to search references by typing command `tide-references`.

> Would it be possible for us to do this in our own code, to make references work?
I don't know, I know lisp a little bit.

Addition information.
When I type `tide-references` then references window (2) is open, but my cursor still in the same window (1) from where I call `tide-references`. So if I move to references window then I haven't to turn off flycheck to be able use `next-error` command, it is working without that. And If I move back to window 1, then again I haven't to turn off flycheck - `next-error` works here and shows next references.

**Comment by josteink** [comment]
Thanks for the feedback @kreedz.

These days I'm a bit short on time, but I'll be glad to review a PR if anyone wants to put in some effort here to either

1. make what we have work properly.
2. create a new minor-mode (or whatever) on top of tide to handle global navigation of references.

If so, let me know 😄

**Comment by ananthakumaran** [comment]
Tide now supports xref. This feature is available via `M-x xref-find-references`
