### ISSUE TITLE
Highlight unused import

### ISSUE THREAD

**Issue by cescoferraro** [ananthakumaran/tide#139]
Thanks for the library! its awesome!
There is only one thing I am missing here. I wonder if there is a way emacs could show me all unused import, just like Intellij.

**Comment by ananthakumaran** [comment]
There are linters like [tslint](https://palantir.github.io/tslint/) which already supports this and more. flycheck has support for tslint.

**Comment by cescoferraro** [comment]
### tslint.json
```
{
  "rules": {
    "no-unused-variable": true
  }
}
```

@ananthakumaran  First I had to enable typescript-tslint on web-mode. It took me a while.



```
       (with-eval-after-load 'flycheck
         (flycheck-add-mode 'typescript-tslint 'web-mode))
```


But  when I compile it with M-x  _flycheck-compile RET typescript-tslit RET_ it tells me those are typescheking values, and I dont get to see any unused errors showing up!


```
-*- mode: compilation; default-directory: "~/go/src/github.com/cescoferraro/craigs/src/" -*-
Compilation started at Mon Apr 24 10:30:59

tslint --format json --config /home/cescoferraro/go/src/github.com/cescoferraro/craigs/src/tslint.json /home/cescoferraro/go/src/github.com/cescoferraro/craigs/src/app.tsx
Warning: The 'no-unused-variable' rule requires type checking
[]
Compilation finished at Mon Apr 24 10:31:00

```

**Comment by josteink** [comment]
I'm also having trouble getting the suggested workaround working.

I've tried a similar config as @cescoferraro. I've tried to enable type-checking, but this requires you to also pass in a `--project` parameter to tslint (something I doubt `flycheck` is currently able to resolve). Even when I run everything "manually" in a controlled test, I cannot get tslint to report unused imports as a unused variable.

@ananthakumaran If you have a setup you've tested and know works, I think documenting it would be a good idea.

**Comment by cescoferraro** [comment]
@josteink I have just found out about flycheck-tslint-args I havent managed to get it to work yet.
I have posted a question on Emacs Exchange https://emacs.stackexchange.com/questions/32951/how-to-enable-type-check-rules-with-flycheck-tslint
@ananthakumaran can you chime in?

**Comment by cescoferraro** [comment]
@josteink made a lil more progress on this matter.

**Comment by cescoferraro** [comment]
```
(defun cesco/tide-checker ()

  (flycheck-def-option-var flycheck-typescript-tsconfig
      nil typescript-tslint-cesco
    "The path of tsconfig.json ."
    :type '(choice (const :tag "No custom tsconfig file" nil)
		   (directory :tag "Custom tsconfig.json"))
    :safe #'stringp
    :package-version '(flycheck . "27"))

  (flycheck-define-checker typescript-tslint-cesco
    "TypeScript style checker using TSLint."
    :command ("tslint" "--format" "json"
	      (config-file "--config" flycheck-typescript-tslint-config)
	      (config-file "--project" flycheck-typescript-tsconfig)
	      (option "--rules-dir" flycheck-typescript-tslint-rulesdir)
	      (eval flycheck-tslint-args)
	      source-inplace)
    :error-parser flycheck-parse-tslint
    :modes (typescript-mode web-mode))
  )

(defun cesco/custom-tslint ()
  (setq flycheck-tslint-args . ("--type-check"))
  (if (projectile-project-p)
      (setq flycheck-typescript-tsconfig . ( (concat projectile-project-root "tsconfig.json" )))
    )
  (flycheck-select-checker 'typescript-tslint-cesco)
  )

(defun cesco/tslint ()
  (setq flycheck-tslint-args . (nil))
  (flycheck-add-mode 'typescript-tslint 'web-mode)
  (flycheck-select-checker 'typescript-tslint)
  )

(defun cesco/tide-mode ()
  (interactive)
  (tide-setup)
  (cesco/custom-tslint)
  (eldoc-mode +1)
  (tide-hl-identifier-mode +1)
  (add-hook 'before-save-hook 'tide-format-before-save)
  (setq flycheck-check-syntax-automatically '(save mode-enabled))
  (add-to-list 'company-backends '(company-tide :with company-yasnippet))
  )

(defun cesco/tide-evil ()
  (evil-leader/set-key-for-mode 'web-mode
    "j" (lambda () (interactive)(tide-jump-to-definition))
    )
  )


(use-package tide
  :diminish tide-mode
  :after (flycheck evil-leader)
  :config
  (cesco/tide-evil)
  (cesco/tide-checker)
  (add-hook 'typescript-mode-hook #'cesco/tide-mode) )


```

**Comment by josteink** [comment]
While that looks like a good "my-config" style patch, wouldn't it be better if you could get some of those settings included in flycheck itself?

It would be real nice if you tried to prepare this is a general PR for flycheck. I'd love to see these changes upstream. :)

**Comment by cescoferraro** [comment]
@josteink I will! 
But I think flycheck people consciently took type-check rules of the default checker because this is still a bit buggy like https://github.com/palantir/tslint/issues/2809 but things  will get better as soon as https://github.com/palantir/tslint/pull/2773 lands.

For right now we still need to parse tslint a bit better like stated here
https://github.com/flycheck/flycheck/issues/1253

**Comment by josteink** [comment]
Good digging and good job. It will be nice to get this landed. Hopefully it wont take too long :)
