### ISSUE TITLE
Support other sources of formatting settings

### ISSUE THREAD

**Issue by Eoksni** [ananthakumaran/tide#148]
tsfmt is able to use settings specified in various places - `tsfmt.json`, `tsconfig.json`, `.editorconfig`, `tslint.json`, `.vscode/settings.json`

It seems tide formatting only supports settings in `tsfmt.json` and those directly specified in elisp (at least thats what it is said in readme and I checked that `.vscode/settings.json` and `.editorconfig` do not indeed work, don't know about others files). I thought tide was using tsfmt for formatting, wasn't it?

For now I'm going to write a function to parse `.vscode/settings.json` and put it into .dir-locals and I'll post it here if anybody is interested, but I would love to see support for those config files in the tide itself.

**Comment by ananthakumaran** [comment]
Tide doesn't use `tsfmt` directly(it uses `tsserver`), but both end up using typescript language service. As I mentioned in another issue, I am happy to accept PR for `tsconfig.json, .editorconfig, tslint.json`. But not for `.vscode/settings.json`, because it's an internal format used by vscode and not standard across all editors and if we go down that route, we might need to support too many formats.

**Comment by Eoksni** [comment]
Well it's too bad because I'm willing to make pull request sometime but I care exactly about `.vscode/settings.json` as I'm the only emacser in the team of vscoders :) I guess I could write a new package as an extension to tide which provides support for vscode config, I assume you wouldn't be against it, but for now I only have time for an as dirty and as simple as possible .dir-locals parser function.

**Comment by Eoksni** [comment]
So here is my quick solution https://gist.github.com/Eoksni/96f30d0bef01ca1acb63a42f22553b93.
I just put `.dir-locals.el` from the gist in the root of my project, next to the .vscode directory, and it populates `tide-format-options` with options found in `.vscode/settings.json`. This solution is not clean, not optimized and not efficient, but it works for me :) So it's not an issue for me anymore hence I close it.
