### ISSUE TITLE
tide filters valid completion entries

### ISSUE THREAD

**Issue by ananthakumaran** [ananthakumaran/tide#149]
I ran into an issue with the new filter logic today

```js
import * as cardHelper from './cardHelper'
cardHelper.|
```

```
response: {"seq":0,"type":"response","command":"completions","request_seq":"69","success":true,
"body":[
  {"name":"CardType","kind":"const","kindModifiers":"export","sortText":"0"},
  {"name":"bankLabel","kind":"const","kindModifiers":"export","sortText":"0"},
  {"name":"binValidation","kind":"const","kindModifiers":"export","sortText":"0"},
  {"name":"cardHelper","kind":"warning","kindModifiers":"","sortText":"1"},
  {"name":"describe","kind":"warning","kindModifiers":"","sortText":"1"},
  {"name":"detectDebitCard","kind":"const","kindModifiers":"export","sortText":"0"},
  {"name":"detectIssuingBank","kind":"const","kindModifiers":"export","sortText":"0"},
  {"name":"detectPrincipal","kind":"const","kindModifiers":"export","sortText":"0"},
  {"name":"eql","kind":"warning","kindModifiers":"","sortText":"1"},
  {"name":"expect","kind":"warning","kindModifiers":"","sortText":"1"},
  {"name":"getCardType","kind":"const","kindModifiers":"export","sortText":"0"},
  {"name":"it","kind":"warning","kindModifiers":"","sortText":"1"},
  {"name":"luhnValidation","kind":"const","kindModifiers":"export","sortText":"0"},
  {"name":"maskCard","kind":"const","kindModifiers":"export","sortText":"0"},
  {"name":"to","kind":"warning","kindModifiers":"","sortText":"1"}]}
```

Even though tsserver responds with useful completions, tide seems to be filtering it out. I am ok with sorting but kind of skeptical about this filtering approach because there is always a possibility that tide removes useful completions. tsserver also supports languge service plugin and this kind of filtering could get in the way of plugins which tries to do framework/domain specific things. 

/cc @katspaugh @josteink

**Comment by josteink** [comment]
For me the most important aspect of this recent change was getting items sorted in a way which give priority to scopes the more local they were.

I can tell we're [filtering out valid completions](https://github.com/ananthakumaran/tide/blob/master/tide-tests.el#L35-L52), and in retrospect I agree that this is probably universally not a wanted behaviour.

As such not catching/stopping that during review was my mistake, and I'm sorry about that.

I guess that leaves us two options:

* do not filter entries at all
* try to be more intelligent about the filtering we do (write even more code, which may or may not be right)

I'll be blunt and say that for now I'm  too in favour of the first one, unless someone can come up with some very compelling arguments.

**Comment by ananthakumaran** [comment]
> As such not catching/stopping that during review was my mistake, and I'm sorry about that.
nobody can forsee all the problems. You are doing a nice job of keeping the ball rolling.

I agree with you. We should disable or if there is no consensus, at least provide a flag to disable/enable it.

**Comment by katspaugh** [comment]
Yeah, exports are something I didn't think about. Let me remove the filtering. The lack of filtering on the tsserver's side is affecting only JavaScript files, anyway. For TypeScript code, the completions come filtered already. So maybe they'll fix this bug in future. Will send a PR.
