### ISSUE TITLE
How does tide-documentation-at-point work?  How do I give it documentation to use?

### ISSUE THREAD

**Issue by bryanbecker** [ananthakumaran/tide#156]
Apologies if this is a basic question, but the README doesn't seem to say anything about this feature besides how to invoke it.

When I use it anywhere, I just get "No documentation available", which I guess is expected since I didn't configure anything.  But how do I do that?

**Comment by josteink** [comment]
It's basic Jsdoc annotations in your (or your libraries') code. 

This is standard across typescript: https://github.com/Microsoft/TypeScript/wiki/JsDoc-support-in-JavaScript

**Comment by bryanbecker** [comment]
Ah, thank you!
