### ISSUE TITLE
Use filesGlob if available

### ISSUE THREAD

**Issue by SerialVelocity** [ananthakumaran/tide#16]
Hey Tide maintainer :D,

More and more tools are using the ```filesGlob``` property, if available, instead of ```files```. It has gotten to the point where our repos wipe the ```files``` property from ```tsconfig.json``` when committing. Is it possible to modify the server to use filesGlob if it is available?

Cheers,
SerialVelocity

**Comment by ananthakumaran** [comment]
Tide is just an emacs frontend. It depends on `tsserver` for all the features. So filesGlob will be available when implemented in TypeScript, link to the relevant issue https://github.com/Microsoft/TypeScript/issues/1927
