### ISSUE TITLE
Documentation at point 

### ISSUE THREAD

**Issue by Grimscythe1983** [ananthakumaran/tide#160]
Could we have a feature that moves the point to the `documentation-at-point` help buffer automatically? Some people would definitely like to have the option to switch the feature on and off, kinda like the `help-window-select` variable to trigger the automatic point movement to the help buffers.

**Comment by josteink** [comment]
I agree about that and support the idea.

I also think using `help-window-select` would be a natural way to solve this. People who want help window selected for elisp or whatever, probably want it for Typescript too.

If someone makes a PR for this, I'll be happy to review and merge.

**Comment by Grimscythe1983** [comment]
I really need to learn elisp so I could write the code and thus contribute to the package. Thanks for supporting the idea @josteink

**Comment by vshender** [comment]
@ananthakumaran @josteink https://github.com/ananthakumaran/tide/pull/259

**Comment by Grimscythe1983** [comment]
@vshender Great work, thank you!
