### ISSUE TITLE
Server Crash with an unhelpful error message when Typescript is not installed in the project

### ISSUE THREAD

**Issue by Dessix** [ananthakumaran/tide#163]
I had TSC available globally, but it seems that I experienced failure on startup of the server when it was not installed within the project's `node_modules` directory. It gave an error message about an invalid argument, but that wasn't particularly helpful in diagnosis of the problem.

Minimal Repro (No project needed to reproduce):
Create an empty directory and open it. Create a new `.ts` file within it, and then view `*Messages*` to see the error message. Here's my related log output for reference:
```
(ttest-e9a1b7a690) Starting tsserver...
(ttest-e9a1b7a690) tsserver server started successfully.
File mode specification error: (file-error Writing to process Invalid argument tsserver)
File local-variables error: (file-error Writing to process Invalid argument tsserver)
Error while checking syntax automatically: (file-error "Writing to process" "Invalid argument" #<process tsserver>)
```

**Comment by josteink** [comment]
I think the problem here is actually not the lack of typescript, but the lack of a `tsconfig.json`. Tide looks for this file to locate what it assumes is the project root.

Could you try to create an empty/default `tsconfig.json` and see if that solves your problem?

**Comment by Dessix** [comment]
I was doing so in a project with a `tsconfig.json` when I first encountered the problem.

**Comment by josteink** [comment]
I'm not able to reproduce that.

When I open a ts-file in a folder with a project.json, but no other typescript files or modules, I get the following (IMO helpful) message:

> Couldn’t locate project root folder with a tsconfig.json or jsconfig.json file. Using ’d:/Throwaway/test-tide/’ as project root.

What version of tide are you using?

**Comment by Dessix** [comment]
It seems to have been resolved after an update. I'll reopen with more details if I see it again.
