### ISSUE TITLE
insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces Not working

### ISSUE THREAD

**Issue by ivikash** [ananthakumaran/tide#164]
Hey, I am using spacemacs with ` (setq tide-format-options '(:indentSize 2 :tabSize 2 :insertSpaceAfterOpeningAndBeforeClosingBraces :json-false))` in `dotspacemacs/user-config` but it seems its not working. Everytime I try to auto align it inserts space within the object.

For eg `import {x} from 'X'` gets converted to `import { x } from 'x'`.

**Comment by ananthakumaran** [comment]
Please check the logs and see if tide is sending the correct value during the configure command https://github.com/ananthakumaran/tide#debugging. If that's the case it's probably a bug in tsserver. You can post the log here if it's not clear.

**Comment by ivikash** [comment]
Thanks. But I am closing this PR. I am using `prettier` now 👍
