### ISSUE TITLE
Question how to jump from references buffer to code?

### ISSUE THREAD

**Issue by cescoferraro** [ananthakumaran/tide#166]
The tide references is really cool. But I could not figure out how to jump from the list to the actual code. Am I missing something here?

**Comment by MarcusRiemer** [comment]
You jump from reference to reference using `n` and `p` and then hit `Enter` once you have the reference you want to follow.

**Comment by cescoferraro** [comment]
Enter does not work for me. Probably evil's fault. What's enter bound to?

**Comment by josteink** [comment]
Or just click on the highlighted symbols using your mouse.

**Comment by cescoferraro** [comment]
@josteink clicking works. Its bound to tide-goto-references.
