### ISSUE TITLE
Auto imports

### ISSUE THREAD

**Issue by ivikash** [ananthakumaran/tide#167]
Hey, I wanted to know if there is a way for `autoimports`, something like `Optimizing Imports` available in webstorm https://www.jetbrains.com/help/webstorm/2017.1/optimizing-imports.html

**Comment by josteink** [comment]
This really needs to be implemented in tsserver in the form of a code-fix. 

If/when it does it should be possible to implement support for this in tide, but not before.

**Comment by krksgbr** [comment]
Fixing missing imports is supported [since TS 2.2](https://blogs.msdn.microsoft.com/typescript/2017/02/22/announcing-typescript-2-2/). I just tried it with tide-fix and it works. There seem to be [more improvements](https://github.com/Microsoft/TypeScript/issues/7849) coming as well.

**Comment by josteink** [comment]
Auto imports works. I know that because I implemented code-fixes and that was my first test-case :)

What @ivikash ask for is removing imports which are not being used. That is AFAIK currently unsupported.

**Comment by ananthakumaran** [comment]
There is an open issue for `Organize Imports` https://github.com/Microsoft/TypeScript/issues/10020. 

@josteink  https://github.com/Microsoft/TypeScript/issues/7849 is linked to auto-complete feature, I guess the idea is to add the import automatically once the user select entry via autocomplete.

**Comment by josteink** [comment]
I guess this question can be considered answered by now, so I'm closing it.

If someone feels like working on this, we're very friendly to PRs :)
