### ISSUE TITLE
Allow tide-fix to supress semicolon

### ISSUE THREAD

**Issue by cescoferraro** [ananthakumaran/tide#168]
I use `tide-fix` all the time is great! But I usually work on project that uses `"semicolon": [true, "never"]`on tslint.json. So I always get the to do the extra step of removing the semicolon. Any workarounds?

**Comment by ananthakumaran** [comment]
@cescoferraro have you tried this plugin? https://github.com/angelozerr/tslint-language-service

**Comment by cescoferraro** [comment]
no luck with the plugin yet @ananthakumaran 
Do you use it?

**Comment by ananthakumaran** [comment]
No, I haven't used it. I have run into similiar problems with eslint, I usually run `eslint-fix-file` manually after `tide-fix`

```elisp
(defun eslint-fix-file ()
  (interactive)
  (shell-command (concat "eslint --fix " (buffer-file-name)))
  (revert-buffer t t))
```

Perhaps we could add a `-hook` that will run after `tide-fix` and users could run linters/prettifiers etc to normalize the file?

@josteink any thoughts?

**Comment by josteink** [comment]
> Perhaps we could add a -hook that will run after tide-fix and users could run linters/prettifiers etc to normalize the file?

Sounds good to me.

**Comment by ananthakumaran** [comment]
There is a open issue in TypeScript repo https://github.com/Microsoft/TypeScript/issues/13270. Let's wait for them before we make any further changes.
