### ISSUE TITLE
Function documentation does not use correct line terminators for platform

### ISSUE THREAD

**Issue by raxod502** [ananthakumaran/tide#169]
When I request the documentation for `lodash.indexOf`, I get the following:

![image](https://user-images.githubusercontent.com/6559064/27306529-cc7a3a14-54fa-11e7-9108-403bc646604a.png)

Note the `^M` carriage-return characters at the end of each line. It seems to me this is a bug, although I'm not sure where since I'm not familiar with the workings of tsserver.

System information:

```
                -/+:.           rrosborough@[redacted]
               :++++.           -----------------------------
              /+++/.            OS: macOS Sierra 10.12.5 16F73 x86_64
      .:-::- .+/:-``.::-        Model: MacBookPro11,4
   .:/++++++/::::/++++++/:`     Kernel: 16.6.0
 .:///////////////////////:`    Uptime: 20 days, 4 hours, 37 mins
 ////////////////////////`      Packages: 130
-+++++++++++++++++++++++`       Shell: zsh 5.3.1
/++++++++++++++++++++++/        Resolution: 1920x1200, 1440x900
/sssssssssssssssssssssss.       DE: Aqua
:ssssssssssssssssssssssss-      WM: Quartz Compositor
 osssssssssssssssssssssssso/`   Terminal: iTerm2
 `syyyyyyyyyyyyyyyyyyyyyyyy+`   Terminal Font: InputMono-Medium 12
  `ossssssssssssssssssssss/     CPU: Intel i7-4980HQ (8) @ 2.80GHz
    :ooooooooooooooooooo+.      GPU: Intel Iris Pro
     `:+oo+/:-..-:/+o+/-        Memory: 4768MiB / 16384MiB
```

**Comment by josteink** [comment]
Last time I checked into a seemingly [related bug](https://github.com/ananthakumaran/tide/issues/122), I found that no matter what the platform-specific line-ending is, Emacs always expects `\n` and `\n` **only**.

Could it be we need to do some cleanup/normalization of the doc-string returned from tsserver as well?

**Comment by ananthakumaran** [comment]
If we go down that route, we should probably introduce `tide-insert` which normalizes line ending and use it everywhere instead of `insert`

**Comment by josteink** [comment]
We'd only need to use it whenever we are inserting data returned by tsserver where we expect line-shifts though.

Using it everywhere regardless of the data-context might incur a needless performance cost, and I'd like to avoid that.

**Comment by ananthakumaran** [comment]
> Using it everywhere regardless of the data-context might incur a needless performance cost, and I'd like to avoid that.

agree without you, by everywhere I meant the places where the text comes tsserver

**Comment by raxod502** [comment]
My question is why tsserver returns output with CRLF line terminators. It seems like a related issue was reported at https://github.com/Microsoft/TypeScript/issues/13183, but maybe responses from the server are different from code reformatting.

**Comment by josteink** [comment]
> My question is why tsserver returns output with CRLF line terminators.

My guess would be that this is the line-shift format of the file which the docs were extracted from.

**Comment by raxod502** [comment]
Hmm… I did a simple `npm install lodash @types/lodash` and checked all the files in `node_modules` that had the docstring in my original post using [this elisp](https://stackoverflow.com/a/234557/3538165). They all appeared to have Unix line endings. But I certainly am not an expert here.
