### ISSUE TITLE
tide causing flycheck to throw error

### ISSUE THREAD

**Issue by qdot** [ananthakumaran/tide#175]
Not sure if this is flycheck or tide, but after a melpa package update, I'm now getting no highlighting in my typescript buffers. Errors look like:

Error from syntax checker typescript-tide: Wrong type argument: flycheck-error-p, [cl-struct-flycheck-error #<buffer HapticVideoPlayer.ts> typescript-tide "/home/qdot/project/src/components/HapticVideoPlayer/HapticVideoPlayer.ts" 49 3 "A function whose declared type is neither 'void' nor 'any' must return a value." error 2355]

tide version 20170712.638
flycheck version 20170717.2300

**Comment by qdot** [comment]
Ok, rolled tide back to 20170621.1159 with current flycheck, still broken. Rolled flycheck back to 20170601.608, things work again. So it looks like flycheck changed something that makes tide not work. Still not sure which side of the line the bug is on. :/

**Comment by ananthakumaran** [comment]
@qdot have you tried to restart emacs after installation? I was able to reproduce the error, but once I restarted emacs, it is working again.

**Comment by qdot** [comment]
Yup, restarted a few times, kept happening. I'll give it another shot.

**Comment by qdot** [comment]
Ok. This is weird. I updated to current packages. Restarted. Things worked. Restarted again, started getting the error again. Now I'm getting it no matter what.

**Comment by qdot** [comment]
Ok. Deleted *.elc files, restarted, things started working again, did a byte compile by hand, things continue to work. I'll call this config issues on my end for now and close out. Sorry to bother, and thanks for tide, it's super handy. :D

**Comment by rtm** [comment]
This happened to me too. Nuking the *.elc files solved it for me also. FWIW.

**Comment by hirocaster** [comment]
This happened to me too.
