### ISSUE TITLE
Started getting these errors 

### ISSUE THREAD

**Issue by simpers** [ananthakumaran/tide#183]
The error (can't mark it as it just disappears on the next keypress or mouse click): 
https://ptpb.pw/xR0l

I'm running Arch Linux with Emacs version 25.2.1
I have the latest packages from the melpa repo and I tried reinstalling tide, typescript-mode and flycheck.

Versions in my environment:
node -v: 8.2.1
npm -v: 5.3.0
tslint -v: 5.5.0
tsc -v: 2.4.2

Just tell me if there's anything else you need to know and I shall add the information.

**Comment by ananthakumaran** [comment]
> can't mark it as it just disappears on the next keypress or mouse click
All the message echoed in the mini buffer will also be logged in a buffer named `*Messages*`

From the stack trace, it looks like a problem with flycheck/tslint. Try to run tslint directly on the file from command line.

**Comment by simpers** [comment]
@ananthakumaran It seems like it was codelyzer that indeed was out of date, so I'm sorry for the trouble. You may delete this issue.

**Comment by josteink** [comment]
Ah ok. Glad you figured it out. Closing.
