### ISSUE TITLE
http://melpa.org/packages/typescript-mode-20170424.2231.el: Not found

### ISSUE THREAD

**Issue by kjcole** [ananthakumaran/tide#187]
Following the installation instructions in the README.md, I see:

`http://melpa.org/packages/typescript-mode-20170424.2231.el: Not found`

after issuing `M-x package-install [ret] tide` in emacs.

**Comment by kjcole** [comment]
Manually searching for, and installing typescript-mode reveals it is currently version 20170823.1000

**Comment by ananthakumaran** [comment]
Looks like the same issue https://github.com/ananthakumaran/tide/issues/103. Melpha deletes old versions, so there is a possibility of cached URLs to return 404.
