### ISSUE TITLE
Update exec path

### ISSUE THREAD

**Issue by yifu** [ananthakumaran/tide#19]
I'm just installing tide on my Mac. I've installed node, which goes into /usr/local/bin directory. The global PATH is updated thanks to my bashrc.

When I launch the emacs app from the Dock neither the PATH nor the exec-path var contains the correct path, that is /usr/local/bin. If we do not update the snippet of code for the quick install, it would be great to mention it in the README.md file. As you wish. :-)

> (setq exec-path (append exec-path '("/usr/local/bin")))

**Comment by ananthakumaran** [comment]
I myself had ran into this problem years ago and use the following to keep the exec-path and PATH same

```lisp
  ;; set the PATH properly
  (let* ((path (shell-command-to-string "/bin/zsh -c 'source ~/.zshrc && printf $PATH'")))
    (setenv "PATH" path)
    (mapc (lambda (p)
	    (add-to-list 'exec-path p))
	  (split-string path ":")))
```

That said, I am not sure whether to add this info in README, because it is a much more generic problem and not related much to tide.
