### ISSUE TITLE
Look for a typescript package and use tsserver from that package; keep the stock tsserver as a fallback

### ISSUE THREAD

**Issue by lddubeau** [ananthakumaran/tide#190]
It would be nice if `tide` could look for a locally installed `typescript` package and use the `tsserver` from that package instead of using the `tsserver` installed with `tide`. Perhaps the latter could be used as a fallback, without being the default.

The current behavior of `tide` with regards to selecting a `tsserver` has been a significant problem for me every since I started using `tide`. AFAIK, it's never been the case that the `tsserver` shipped with `tide` and the `typescript` version I used to compile any of my projects were at the same version number. I got a lolwut moment early on when I saw that the errors reported in Emacs and outside Emacs were different until I realized the problem was the `tsserver` used by `tide`. (And I suspect this is going to continue to bite users of `tide` time and again.)

So I quickly decided to override the default behavior with the following code. I'm not putting this as a PR because it is probably too idiosyncratic, but it can serve as a start for discussion at least. This is part of my `setup-tide-mode` function:

```
      ;; If there is a directory with "package.json" in it, we take that
      ;; as the location from which to search for a tsserver and set
      ;; tide-tsserver-executable to it, if it exists.
      (let* ((package-root (locate-dominating-file default-directory
                                                   "package.json"))
             (path
              (and package-root
                   (expand-file-name "node_modules/typescript/bin/tsserver"
                                     (expand-file-name package-root)))))
        (when (and path
                   (file-exists-p path))
          (make-local-variable 'tide-tsserver-executable)
          (setq tide-tsserver-executable path)
        ))
```

I've used this code for months now. Never had a problem.

**Comment by leo-shopify** [comment]
This looks much more sustainable.
Checking for a global installation after `node-modules` would make sense. `which tsserver` (and the windows equivalent)?

Would it still make sense to embed a static version?
It's a good out of the box experience but at the same time anyone using typescript is likely capable of installing it independently :)

A function to log version and configuration could be useful for reporting issues, but this should provably a separate discussion.

**Comment by ananthakumaran** [comment]
Tide used to ship modified version tsserver.js in the start, which is probably the reason for prefering it. Another good property of this setup is, the chance of encountering problems because of protocol mismatch between tide and tsserver is very less. But nowadays we try to keep tide backward compatibility with any 2.x version.

That said, we should probably try to give more preference to node_modules/ in the project root.

1) if tide-tsserver-executable is set, just use it.
2) use node_modules/typescript/bin/tsserver if available (I am not sure if this is the canonical path across all OS & package managers (npm, yarn). I have also seen `node_modules/.bin/tsserver` in the past)
3) use the shipped version.

I am not sure if we should give preference to global install. It's not related to the project and it might be a old version as well, so I prefer to use the bundled one instead of this.

Please open a PR if you have time. (if possible just change the tide-start-server function)


> Would it still make sense to embed a static version?
> It's a good out of the box experience but at the same time anyone using typescript is likely capable of installing it independently :)

There are some who use tide to edit single js/ts file. I personally use tide to edit js files in projects which don't have typescript dependency.


> A function to log version and configuration could be useful for reporting issues, but this should provably a separate discussion.

I really want this, but I can't find any easy way to figure it out. `tsserver` doesn't support any kind of version command AFAIK. Probably we should provide something like `flycheck-verify-setup`

**Comment by MarcusRiemer** [comment]
Yes, please use either the `tsserver` that resides somewhere in `node_modules` or keep bundling the "binary". I have no globally installed typescript but always rely on the concrete version that is bundled with my projects via `npm`.

**Comment by josteink** [comment]
> use `node_modules/typescript/bin/tsserver` if available (I am not sure if this is the canonical path across all OS & package managers (npm, yarn). I have also seen `node_modules/.bin/tsserver` in the past)

On windows it needs a `.cmd`-suffix. This is what I use for my setup: `node_modules/.bin/tsserver.cmd`. The globally installed version on Windows can be found using this expression:

````elisp
(expand-file-name (substitute-in-file-name "$APPDATA\\npm\\tsserver.cmd"))
````

If you have those covered as well, this should all be good.

**Comment by josteink** [comment]
In lieu of @lddubeau comment:

> However, if the choice is between:
>
> A. Supporting common simple layouts at decent speed, and
>
> B. Supporting less common layouts but a the cost of significantly slowing down initialization for everyone, then
>
> I'd take A over B every time.

I decided to investigate how work this would really be... And the fastest way to estimate coding time is obviously by doing :)

So I created this: https://github.com/ananthakumaran/tide/tree/lightweith-locate-tsserver-executable

And specifically, on top of everything @leo-shopify has done so far, I wrote this really simple stuff: https://github.com/ananthakumaran/tide/commit/503b17c6404214c5f53879eaf4984046f5c3f8ef (ironically I haven't tested the Windows-code yet :) )

Would anyone like to fool around with that, and see if that works better for them? I'm especially interested if you have anything against it, @lddubeau, seeing as you're one of the more serious contributors we have around here, and your opinion does carry weight. 

If we can all agree that this is "good enough" and works, I guess we don't need to spend too much time discussing other alternate approaches.

**Comment by josteink** [comment]
And with [that](https://github.com/ananthakumaran/tide/commit/77ba28cf6e66814fd8fb206f01aa22c122692f71) it should work on Windows too.

**Comment by josteink** [comment]
Since comments on the linked commit doesn't show here, I'll just copy/paste @lddubeau's repsonse for the sake of discussion:

> ..... lots of discussion .....
>
> I'd be okay with moving forward and see if we get a request for more flexibility.

So I'll take that as one vote for moving forwards. Anyone else have an opinion?

**Comment by leo-shopify** [comment]
I still think it's worth keeping the current interface. Concretely:

1. Keep `tide-locate-tsserver-executable` as it was.
2. Move the locate server functionality to a new function:
```elisp
(defun tide-find-tsserver-script ()
  "Find the typescript server executable.
Check in the npm local package directory, in the project root as defined by projectile, 
and in the npm global installation."
  (or
   (tide--locate-tsserver (tide--npm-local))
   (tide--locate-tsserver (tide--project-package))
   (tide--locate-tsserver (tide--npm-global))))
```
3. Change the [configuration example](https://github.com/ananthakumaran/tide#typescript) to:
```elisp
(defun setup-tide-mode ()
  (interactive)
  (setq tide-tsserver-executable (tide-find-tsserver-script))
  (tide-setup)
  ...
```

### Advantages
- Backward and *forward* compatible.
   Lets us change or add new strategies to find tsserver without disrupting existing user's setups.
- Easier for contributors to add new search strategies for uncommon use cases.
- Leaves the decision to the user when there are trade-offs.

*Sorry, I don't have my computer with me, can't make a pr.*

**Comment by josteink** [comment]
Thanks for your feedback Leo!

While I appreciate several *aspects* of the approach, and see how they most definitely represent a general improvement in areas I haven't addressed at all, I'm still not in full agreement about the full packages.

I think my disagreement is mostly focused around two things.

> Change the configuration example to:
>
>     (setq tide-tsserver-executable (tide-find-tsserver-script))

I'm just not very happy about that approach. Most major/minor modes I use, can be fully setup and activated by a simple `M-x mode-name-mode` and bam, done. No code or nonsense required.

I see no reason for `tide` to be overly special in that regard, and I already feel we are way "heavier" than the average minor-mode. I can't be the only one feeling like that, can I?

Ideally I'd like for activating `tide` only consist of `(tide-mode)`, but I guess that's another discussion. For now though, I'd like to avoid taking tide in the opposite direction, if possible.

And in my opinion a change like this represents such a move. So yeah. I'd like a different kind of solution.

With that said: I do like the general idea of empowering and providing the user of the mode with an easy way to switch to alternative strategies, and provide an entry-point for others (contributors, end-users, etc) to complement or replace the general search algorithm with their own though.

Maybe we could use something like `(tide-setup #'my-custom-tsserver-locator-function)` where the absence of an argument will be interpreted as `#'tide-find-tsserver-script`? I'd be happy be that. That's a nice addition.

Which brings me to my next point:

> Lets us change or add new strategies to find tsserver without disrupting existing user's setups.

Right now... Users don't really have a strategy at all, besides setting a `defcustom` which will continue to override anything we do. In the absence of that, they've piggybacked on the built in version. There's not really much there now to build a flow on at all.

And I'd hate for this *general improvement* to be something users would have to opt in to take advantage of.

Maybe I'm mistaken, but I believe most users are just going to update tide through the Emacs package-manager and never re-read the Github README, they won't know about the improvements we've made. And thus they won't use them.

Unless a change is *so overly opinionated* and not representing a general improvement (in which case... I doubt we will be making it), I'd rather have all the improvements we do make to be served on a silver platter, automatically, to all users.

Except ofcourse for those who decide to put themselves in control and opt out. These users needs to have their needs addressed by some sort of entry-points. Like the one we discussed above. 

Without diving into how that looks in code... What opinion do you other guys have about such an approach?

**Comment by lddubeau** [comment]
> I see no reason for `tide` to be overly special in that regard, and I already feel we are way "heavier" than the average minor-mode. I can't be the only one feeling like that, can I?

You're not the only one. I've so far taken the `setup-tide-mode` as being mostly a *suggestion* of how things can be done when someone wants to use tide with *optional* minor modes that can be used to augment tide, or for which tide provides optional logic. It would be a shame if it became a *necessity* to craft a `setup-tide-mode` to get reasonable behavior out of tide.

I realize that if we make the it the default to look for a local `tsserver`, a global one, and then resort to the one bundled with `tide`, people who do not act will get a different behavior in the sense that they may be using a different `tsserver` than they used to. Problem though is that if using the bundled `tsserver` worked fine for them, that was chance, not design.

I'll also say I have a hard time seeing a setup where the new default behavior would cause breakage. In such hypothetical case, using the bundled `tsserver` *worked* but switching a locally or globally installed `tsserver` would *fail*. It seems to me for such case to exist, it would entail that the user was not ever compiling the TypeScript code outside of Emacs. So no `tsc`, no `tslint`, no `typedoc`, no `gulp`, Webpack, Mocha, Karma that would invoke the TypeScript compiler, etc. Otherwise, if the user used any of these, then the user would have already experienced the failures that the switch in `tsserver` would cause.

**Comment by josteink** [comment]
> Problem though is that if using the bundled tsserver worked fine for them, that was chance, not design.

Agreed. So I'm very much OK with not preserving a pixel-perfect as-things-were behaviour.

If this breaks something for someone, let them file a issue, and we'll steer them in the general right direction.

I'll tweak my changes a little to accommodate leo's suggestions, and will prepare a PR for review.

**Comment by josteink** [comment]
Closed via https://github.com/ananthakumaran/tide/pull/201.
