### ISSUE TITLE
Can't find node_modules/@types

### ISSUE THREAD

**Issue by longitude** [ananthakumaran/tide#192]
I updated to the latest tide version and my type definitions are not loading and I see squiggly lines under my external types

I use 
```    
"typeRoots": [
      "../node_modules/@types"
    ]
```
I reverted back to an older tide version before `TS 2.5.2` that works as expected.

This might be a typescript issue not sure.

**Comment by longitude** [comment]
I figured this, I did not point to my types folder properly. Updated path in `typeRoots` worked.

**Comment by josteink** [comment]
Sounds reasonable. Issues like these are usually tied to tsc and it's config and not so much any Emacs-specific code. 

Glad you figured it out.
