### ISSUE TITLE
Copy definition of type at point

### ISSUE THREAD

**Issue by bodhi** [ananthakumaran/tide#194]
I find the auto-display of the type at the current point really useful, but sometimes I'd like to copy the type definition somewhere so that I can reference it. Is there a way to do this? Even just printing the type out to `*messages*` would be enough (type errors are displayed in `*messages*` already...)

**Comment by josteink** [comment]
This seems like a bit of a specialist functionality, I don't see us adding this to be honest.

That said, it should be fairly easy to create your own `defun` to do this, based on the current eldoc-handler:

https://github.com/ananthakumaran/tide/blob/master/tide.el#L825-L833

Just rename it and replace `tide-eldoc-maybe-show` with `msg` or something like that.

**Comment by josteink** [comment]
This seems like a bit of a specialist functionality, and I don't see us adding this to be honest.

That said, it should be fairly easy to create your own `defun` to do this, based on the current eldoc-handler:

https://github.com/ananthakumaran/tide/blob/f1daf10e931858ac8d6ff676cf02ca73d3c62558/tide.el#L825-L833

Just rename it, strip out the outer eldoc wrapping and replace `tide-eldoc-maybe-show` with `msg` or something like that.

**Comment by bodhi** [comment]
Great! That's exactly the kind of pointer I was looking for. I had no idea where to start looking for the functionality.

I'll give it a go.

**Comment by bodhi** [comment]
```

(defun tide-eldoc-at-point ()
  "print Typescript's idea of the type at the current point"
  (interactive)
    (if (tide-method-call-p) 
         (tide-command:signatureHelp #'message) 
       (when (looking-at "\\s_\\|\\sw") 
         (tide-command:quickinfo 
          (tide-on-response-success-callback response t 
            (message (tide-doc-text (plist-get response :body)))))))) 
```

works a charm. Thanks for the lightning-fast help!

**Comment by ananthakumaran** [comment]
```
(setq tide-always-show-documentation t)
```
`M-x tide-documentation-at-point` with the above config will show the type info in a help buffer.

**Comment by bodhi** [comment]
Even better! Thanks @josteink and @ananthakumaran
