### ISSUE TITLE
Question: should tide start tsserver for every buffer?

### ISSUE THREAD

**Issue by troglotit** [ananthakumaran/tide#196]
I have a question: should tide start tsserver for every buffer?
And because of that emacs hangs a little bit for every new buffer.

I invoke it like this:
```elisp
  (add-hook 'js2-mode-hook #'setup-tide-mode)
```

**Comment by josteink** [comment]
I would assume only once per project. 

Are your JS-files part of a typescript project-structure?

**Comment by troglotit** [comment]
No, they're not.
I forgot to mention: project didn't had `jsconfig.json`

**Comment by josteink** [comment]
If so, what you’re seeing is probably what to expect from the current code. 

As a workaround, you can add a tsconfig.json to your project root. 

This issue may in the future be fixed by a currently evolving PR, or other changes associated with it: #193.

**Comment by ananthakumaran** [comment]
Closing this. Tide will create a `tsserver` process for each folder. We already provide a clear warning `"Couldn't locate project root folder with a tsconfig.json or jsconfig.json file. Using '" default-directory "' as project root."` when we can't locate the project root directory.
