### ISSUE TITLE
Warning (tide): A file backed buffer is required to start the tsserver.

### ISSUE THREAD

**Issue by xjt19890115** [ananthakumaran/tide#198]
when i run emacs in cygwin, "tide-setup" doesn't startup the tsserver

**Comment by josteink** [comment]
`tsserver` requires a file to operate on (and optimally within a project too). This is not a limitation created by `tide` itself.

This behaviour is only `tide` being pre-emptive about it to avoid other, more cryptic errors.

I'm sure people can suggest work-around by saving the file *somewhere*, but somewhere *where*? And to what project should it belong? Etc etc.

I think the current behaviour mostly works out well. Are there specific use-cases where you feel this gets in your way?

**Comment by robbert-vdh** [comment]
I've personally only encountered this when writing .vue components. As [vue-mode](https://github.com/AdamNiederer/vue-mode) uses mmm-mode and indirect buffers to support multiple languages, the typescript code shares a file with the component's markup and styling. You could work around this by simply by placing the script in another file, but that kind of defeats the purpose of single file components. It would be nice if tide supported this kind of behaviour, though I can't come up a way how (aside from writing the indirect buffers to another file, which probably breaks all kinds of behaviour).

**Comment by josteink** [comment]
> if tide supported this kind of behaviour, though I can't come up a way how

Indeed. And that's the crux of thematter.

If someone can find a way to bypass this issue in a way which doesn't cause issues or is a new source of confusion somehow... I'd be happy to consider it.

Until then, the current behaviour is unfortunately bound to stay.

**Comment by josteink** [comment]
Is there a case where you genuinely should be able to use tide (ie have a file) and it doesn’t work?

Or is it ok to close this?

**Comment by robbert-vdh** [comment]
The two use cases I can come up with are literate programming (for example in a .org file) and TypeScript embedded in HTML or single file components. I've looked into [VsCode's TypeScript plugin](https://github.com/Microsoft/vscode/blob/7807e1e1296eb6df0e05122d4e783c5db975c605/extensions/typescript/src/features/bufferSyncSupport.ts#L36) and they seem to work around this by manually passing the buffer's contents and any changes made to tsserver. I'll try to get it to work sometime next week.

**Comment by howdoicomputer** [comment]
Thanks so much for working on this! I have both those use cases!
