### ISSUE TITLE
[wish] when doing tide-rename-symbol auto-open all the files affected

### ISSUE THREAD

**Issue by nahuel** [ananthakumaran/tide#199]
When you do `tide-rename-symbol` only the already opened files are affected by the change, if a file exists in the project referencing the symbol and is not currently opened, then is not changed, rendering the code inconsistent. It will be better to automatically open the all the project files referencing the symbol and then do the effective rename on all.

**Comment by josteink** [comment]
That's not consistent with how tide is supposed to work, how it's code is structured for this command and I simply cannot reproduce this.

Specifically we open all edits in temporary buffers, to avoid littering Emacs with needless buffers doing the rename.

I've made a simple project like this:

````typescript
// file1.ts
export class Foo {
    bar() {
        return 1;
    }
}

// file2.ts
import { Foo } from "./file1";

var x = new Foo();
x.bar();
````

Doing rename `bar` in either of those files without the other one open reports `"Renamed 2 occurrences"`.

Can you provide instructions to reproduce? Maybe even a sample repo? Are you working with untyped code with only implicit structural typing, like JS-files?

**Comment by nahuel** [comment]
Sorry, I tested it wrongly (using symlinks), the behavior of `tide-rename-symbol` is the same I wished in this issue (all the affected files are changed), the one you described. Note, what I see is the extra files being opened in buffers and the buffers are still open after the "Renamed X occurrences" message, no temporary behavior (but is ok for me).

**Comment by josteink** [comment]
So ok to close then?

**Comment by nahuel** [comment]
yes, thank you

**Comment by josteink** [comment]
No problem :)
