### ISSUE TITLE
Tide not working on large project

### ISSUE THREAD

**Issue by caisah** [ananthakumaran/tide#2]
I'm working on a large TypeScript project and I don't have a custom `tsconfig.json` file, so I added an empty file at the root of the project.

The `tsserver` runs but the problem is *tide* doesn't seem to work. When I run a tide command, it freezes for a second or so and I get: 
`eldoc error: (error Sync request timed out quickinfo)`
 or
`eldoc error: (error Sync request timed out signatureHelp)`

How could I resolve this?

**Comment by ananthakumaran** [comment]
which version? 1.6 or 1.5 or both
did you try to add excludeProperty?
"Sync timed out" should happen only when tsserver takes too long to respond (2 seconds by default).

**Comment by caisah** [comment]
I'm using 1.4.1 and yeah, maybe I should use excludeProperty, it's just I would have to do some grooming which takes a lot of time.

The project works fine for my peers using Webstorm&Visual Studio so I thought it would work out of the box.

**Comment by ananthakumaran** [comment]
I am closing this issue. If you still encounter the problem please check the [log](/ananthakumaran/tide#debugging) and reopen the issue with specific details.
