### ISSUE TITLE
How do I debug "No project"?

### ISSUE THREAD

**Issue by martine** [ananthakumaran/tide#20]
I have a directory containing a `tsconfig.json`.  If I create a `foo.ts` file in that directory and hit `M-.` on an identifier in it, I get: `Error processing request. No Project.`

Tide works for me on other projects so it's clearly something particular about this one, but how can I debug it?

**Comment by ananthakumaran** [comment]
```lisp
(setq tide-tsserver-process-environment '("TSS_LOG=-level verbose"))
```
I would look at the tsserver's log file. With the above setting, tsserver would create a log file in `path-to-elpa/tide-xxx/tsserver/.logxxx`

**Comment by ananthakumaran** [comment]
I have added a debugging section in the readme file. Can we close this issue?

**Comment by martine** [comment]
Thanks for responding!
