### ISSUE TITLE
doing tide-rename-symbol on a shared file by two projects only affects one project

### ISSUE THREAD

**Issue by nahuel** [ananthakumaran/tide#200]
If you open two TS projects sharing a common file with a symlink, and then do a `tide-rename-symbol` in the shared file, ONLY the files in the project were you did the operation will be affected by the rename, rendering the other project files inconsistent. Steps to reproduce:

1- Create `/tmp/a` and `/tmp/b` projects and `/tmp/c` shared directory

```
cd /tmp ; mkdir a b c
cd a ; npm init ; tsc --init
ln -s ../c c
cd ..
cd b ; npm init ; tsc --init
ln -s ../c c
```

2- Create files:

```ts
/* /tmp/c/fc.ts */
export const C = 8

/* /tmp/a/a.ts */
import {C} from "./c/fc"
console.log(C)

/* /tmp/b/b.ts */
import {C} from "./c/fc"
console.log(C)
```

3- Now open all the `.ts` files in Emacs, and do a `tide-rename-symbol` on the `fc.ts` / `C` symbol. Only the files at the `a` folder will be affected, the `b` files will not be updated with the new symbol (or viceversa, depending if you opened `/tmp/a/c/fc.ts` or `/tmp/b/c/fc.ts`).

**Comment by josteink** [comment]
I’m pretty sure this is how tsserver works and really tide’s fault. 

My guess is you will be able to reproduce this in vscode too. 

If such, you need to file this issue in the typescript repo.

**Comment by josteink** [comment]
Right. In which case I’m closing this one. 

Nothing *we* can do about it after all :)
