### ISSUE TITLE
tide-fix, tide-locate-tsserver-executable issues

### ISSUE THREAD

**Issue by longitude** [ananthakumaran/tide#202]
After the recent changes to `tide-locate-tsserver-executable` I see strange behavior 

I have two typescript repos, both use typescript version `2.1.6`, I use NVM on mac.
I have node_modules in both projects with typescript 2.1.6 installed.

For one of the projects `tide` is not able to locate project specific `tsserver.js`
it defaults to `elpa/tide/tsserver.js`, loads fine for the other project.

`tide-fix` doesn't work for both the projects, see below, I expect `tide-fix` to add missing imports

![tide-fix](https://user-images.githubusercontent.com/5510191/31478885-6e6200a6-aee1-11e7-83ed-90f27f2aaaad.gif)

I tried hardcoding `tsserver` to my  global typescript installation
```  
(setq tide-tsserver-executable 
  ".nvm/versions/node/v6.9.5/lib/node_modules/typescript/lib/tsserver.js")
```
I noticed strange behavior `tide-fix` started working only after I load a second project
or killing the first project and reopening project, looks like some required environments variables are not being loaded the first time

For now I would like to use `tsserver.js` that comes bundled with `elpa/tide` would this be the correct way to source it

```
  (setq tide-tsserver-executable (expand-file-name tide--tsserver tide-tsserver-directory))
```

**Comment by ananthakumaran** [comment]
I don't think 2.1.x supports code-fixes.

What's is your global version?

> For now I would like to use tsserver.js that comes bundled with elpa/tide would this be the correct way to source it
Yes, this should work.

**Comment by longitude** [comment]
on the same project previously it worked because of the default `tsserver` from `tide`

my global is 2.5.3

**Comment by josteink** [comment]
> I noticed strange behavior tide-fix started working only after I load a second project
or killing the first project and reopening project, looks like some required environments variables are not being loaded the first time

You either need to restart tsserver or Emacs after changing tsserver settings. 

It won’t affect already opened buffers. 

Unless I misunderstand something, this is how rude has always worked. 

Also I’m slightly curious: you want to use tide-functionality which depends on tsserver 2.5, but your projects use typescript 2.1. 

Do you have any particular reason for not upgrading? It seems to me, that would solve all your issues.

**Comment by longitude** [comment]
Yes I did that, restarted `emacs` closed all buffers reopened.

Ideally yes we should upgrade our project version, but we have so many dependencies and I don't see it happen anytime soon.

This functionality was working previously with older versions of `tide`. 

I got it to work now too, but looks like some variable is not being initialized on load after the recent code changes, which is why I have to open a second project.

**Comment by josteink** [comment]
> I got it to work now too, but looks like some variable is not being initialized on load of the first project after the recent code changes, which is why I have to open a second project.

Where are you setting this variable? Can you show us your typescript mode-hooks?

This is literally the first thing we look for when activating tide for a new buffer.

**Comment by longitude** [comment]
```
(defun setup-tide-mode ()
  "Setup tide mode."
  (interactive)
  (tide-setup)
  (setq tide-tsserver-executable (expand-file-name tide--tsserver tide-tsserver-directory))
  (setq flycheck-check-syntax-automatically '(save mode-enabled))
  (tide-hl-identifier-mode +1))

(use-package tide
  :diminish tide-mode
  :config
  (define-key tide-mode-map (kbd "C-c b") 'tide-format))

(add-hook 'typescript-mode-hook #'setup-tide-mode)
```

**Comment by josteink** [comment]
That's wrong. You need to have the `setq` before `tide-setup`, like this:

````elisp
(defun setup-tide-mode ()
  "Setup tide mode."
  (interactive)
  (setq tide-tsserver-executable (expand-file-name tide--tsserver tide-tsserver-directory))
  (tide-setup)
  (setq flycheck-check-syntax-automatically '(save mode-enabled))
  (tide-hl-identifier-mode +1))
````

In other words, this is an error in your setup, not in tide :)

**Comment by longitude** [comment]
@josteink  = MVP, thanks that works.

Other problem I ran into is `tide` defaulting to `elpa\tide\tsserver` even when there is project local `node_modules\tsserver`, this is not critical though :)

**Comment by josteink** [comment]
> Other problem I ran into is tide defaulting to elpa\tide\tsserver even when there is project local node_modules\tsserver, this is not critical though :)

This is not expected behaviour.

If you can create a sample repo which demonstrates this bug, and create a seperate issue for it, I would really appreciate that. Hopefully it shouldn't be too hard to fix. (Please also attach the relevant FULL paths to the relevant dirs)
