### ISSUE TITLE
View type of the entity at point in a new buffer

### ISSUE THREAD

**Issue by lorefnon** [ananthakumaran/tide#204]
On hovering over an entity its type is displayed in the [echo area](https://www.gnu.org/software/emacs/manual/html_node/elisp/The-Echo-Area.html).  However this is inconvenient for viewing complex generated/inferred types. 

![image](https://user-images.githubusercontent.com/1449492/32417306-6523c5ec-c27d-11e7-81c5-168a9c5db535.png)

It would be great if tide could expose a command to view the type of entity at point in a separate buffer.

It would be awesome if things like `tide-references`, `tide-documentation-at-point` etc. could also work in this buffer.

**Comment by ananthakumaran** [comment]
> It would be great if tide could expose a command to view the type of entity at point in a separate buffer.

with `tide-always-show-documentation` set to non-nil, You could view type information in another buffer using `tide-documentation-at-point`

> It would be awesome if things like tide-references, tide-documentation-at-point etc. could also work in this buffer.

This is not straightforward to do with the current tsserver model. All the information is obtained by passing the location of the symbol in the source file. The same could not be done for non-source file backed buffer like documentation buffer.

**Comment by lorefnon** [comment]
> with tide-always-show-documentation set to non-nil, You could view type information in another buffer using tide-documentation-at-point

This does exactly what I wanted. Thanks a lot. 

> This is not straightforward to do with the current tsserver model

I see. Please feel free to close this issue if you think this is outside the scope of what tide can/should do at present.

**Comment by ananthakumaran** [comment]
closing for now, I will re-open if I get any new ideas.
