### ISSUE TITLE
autocomplete suggestion of npm module and import named export

### ISSUE THREAD

**Issue by kandros** [ananthakumaran/tide#210]
Is it possible to enable suggestions of npm modules and import named export?   

  
![](https://d26dzxoao6i3hh.cloudfront.net/items/080l0P1b2g3u0s1N3t0t/Screen%20Recording%202017-11-18%20at%2004.54%20PM.gif?v=c06d99d7)
(vscode example)

**Comment by ananthakumaran** [comment]
tide uses the same backend as vscode, so theoretically everything that works in vscode should work here.
![](https://media.giphy.com/media/xUOxeVPKl1qMBJYIBa/giphy.gif)

But the UX might not be as good as vscode. Company usually starts auto-completion after you have typed 3 characters see the documentation for `company-minimum-prefix-length`. So you have to manually call `company-complete` to get the same effect

**Comment by kandros** [comment]
Perfect, thank you!
