### ISSUE TITLE
Documentation around use-package

### ISSUE THREAD

**Issue by ryanolsonx** [ananthakumaran/tide#212]
Is there any way that there could be some examples on how to setup tide using the `use-package` syntax? I haven't been able to find any resources anywhere on this subject.

Thanks!

**Comment by lddubeau** [comment]
Here's an example from my `.emacs` file, edited to remove rather idiosyncratic settings:

```
(use-package tide
  :load-path "~/src/git-repos/tide"
  :config
  (progn
    (defun setup-tide-mode ()
      (interactive)
      (tide-setup)
      (flycheck-mode +1)
      (eldoc-mode +1)
      ;; company is an optional dependency.
      (company-mode +1)
    )
    (add-hook 'typescript-mode-hook #'setup-tide-mode)
  ))
```

I use `:load-path ...` because I want to use whatever development version I have checked out rather than what is published. Otherwise, I'd have `:ensure t` there.

**Comment by ryanolsonx** [comment]
Oh thanks! I appreciate it.
