### ISSUE TITLE
Derive tide-project-errors and tide-references from special-mode

### ISSUE THREAD

**Issue by felipeochoa** [ananthakumaran/tide#216]
From the [info manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Derived-Modes.html):

> The recommended way to define a new major mode is to derive it from an existing one 
> using define-derived-mode. If there is no closely related mode, you should inherit from
> either `text-mode`, `special-mode`, or `prog-mode`. See [Basic Major Modes][1]. If none of
> these are suitable, you can inherit from `fundamental-mode` (see [Major Modes][2]). 

I think `tide-references-mode` and `tide-project-errors-mode` should inherit from `special-mode`.

This lets any tools/customizations which are activated only special modes to do this automatically without having to special-case these modes.

[1]: https://www.gnu.org/software/emacs/manual/html_node/elisp/Basic-Major-Modes.html#Basic-Major-Modes
[2]: https://www.gnu.org/software/emacs/manual/html_node/elisp/Major-Modes.html#Major-Modes

**Comment by josteink** [comment]
I didn't even know about `special-mode` until now, so I guess I don't really have an opinion either way. (And if I did, it certainly shouldn't be given much weight)

Do you have any example of such usage for me to dig into, just to develop some better understanding?

@ananthakumaran : Do you have an opinion on this? And can you foresee any adverse negative effects?

**Comment by felipeochoa** [comment]
`special-mode` doesn't add much behavior-wise; it's mostly just about convention. E.g., some tools enable/disable certain keybindings or hooks in special mode. My motivation for opening this issue was to have [`god-mode`](https://github.com/chrisdone/god-mode) automatically disable itself in these buffers without having to special-case them. (`god-mode` disables itself in modes derived from `special-mode` automatically)

The built-in `special-mode` behavior which these modes would inherit is:

> Special mode sets the buffer to read-only. Its keymap defines several common bindings, including `q` for `quit-window` and `g` for `revert-buffer`

It also provides a central point (`special-mode-map`) for users to define their own keybindings for modes that aren't about editing text

**Comment by josteink** [comment]
Sounds reasonable to me, at least as long as we don’t break anything else and maybe take the time to clean up redundant left overs obsoleted by this move. 

As always: PRs are welcome!
