### ISSUE TITLE
font-lock face for decorators?

### ISSUE THREAD

**Issue by schmeic** [ananthakumaran/tide#222]
Would it be possible to set a font-lock face for typescript decorators? This would be nice for editing angular code. I've been using ng2-mode, but it only supports certain decorators.

**Comment by lddubeau** [comment]
[`typescript-mode`](https://github.com/ananthakumaran/typescript.el) is where fontification code resides. So any issue about fontification has to be brought up there.

Also all contributors to `tide` and `typescript-mode` are pretty busy. The best way to get a feature added is to submit a PR that has the desired feature and unit tests for the new feature. We welcome PRs.
