### ISSUE TITLE
Disable code formatting

### ISSUE THREAD

**Issue by altschuler** [ananthakumaran/tide#224]
I'm using prettier to format typescript, and the tide formatter is conflicting sometimes. I removed the hook (`(add-hook 'before-save-hook 'tide-format-before-save)`), but the formatter is still trying to format the code on save. Is it on by default? If I "manually" remove it per session it seems to work.

**Comment by ananthakumaran** [comment]
nope, it's not enabled by default. Probably enabled in some other place?

**Comment by altschuler** [comment]
You are quite right. My bad :)
