### ISSUE TITLE
compileOnSave isn't inherited via extends

### ISSUE THREAD

**Issue by sbuzonas** [ananthakumaran/tide#225]
I believe `compileOnSave` should be inherited and possibly overridden with `extends`.

**src/tsconfig.base.json:**
```json
{
  "compileOnSave": true
}
```

**src/project1/tsconfig.json:**
```json
{
  "extends": "../tsconfig.base"
}
```

**src/project2/tsconfig.json:**
```json
{
  "extends": "../tsconfig.base",
  "compileOnSave": false
}
```

**src/project3/tsconfig.json:**
```json
{
  "extends": "../tsconfig.base",
  "compileOnSave": true
}
```

Given the above configuration, the *project1* and *project3* sources should compile on save, and the *project2* sources should not. Currently only *project3* respects `compileOnSave` because it is explicitly configured and `extends` is not respected.

**Comment by josteink** [comment]
I didn't know about this feature, but it seems [the docs](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) agree with you.

If you want improved support for cases like this, I suggest sending a PR with the relevant changes. That's usually the best way to get things done in the world of open-source :)
