### ISSUE TITLE
Lost company-files triggering

### ISSUE THREAD

**Issue by mbenedettini** [ananthakumaran/tide#226]
I've just updated tide and I've lost `company-files` autocompletion.

That is, I was able to type

`import { Example } from "./`

and a popup with the list of files in the current directory would get displayed (as it happens in js-mode and many others).

Can I get this behaviour back again somehow? I've tried customizing `company-backends` but it just didn't work.

Thanks,
Mariano.

**Comment by josteink** [comment]
Do you remember what version you were using when this last worked?

**Comment by timbovelander** [comment]
I also have this problem and could trace it back to this change:
https://github.com/ananthakumaran/tide/commit/c4ff72a

If I revert the change, I will get suggestions from company-files again.

I think the change is correct though, since you would want completion inside strings, but not in comments. However, Tsserver does not suggest files in an import statement, only installed node_modules.

**Comment by josteink** [comment]
Thanks @timbovelander. That good research!

> If I revert the change, I will get suggestions from company-files again.

...

> I am using tide some more now in my projects and it does actually suggest files that export stuff for me. As stated before, you need to type some part of it before it will be triggered.

Based on your above comment, what exactly do you propose as a fix? Do you still think this is something which needs fixing?

**Comment by ananthakumaran** [comment]
> EDIT: I am using tide some more now in my projects and it does actually suggest files that export stuff for me. As stated before, you need to type some part of it before it will be triggered
this length is actually controlled by company and could be reduced AFAIK
```elisp
(setq company-minimum-prefix-length 2)
```

**Comment by timbovelander** [comment]
> Based on your above comment, what exactly do you propose as a fix? Do you still think this is something which needs fixing?

I don't think this issue needs a fix. It is true that company-files is not giving any suggestions anymore, but tide is giving back modules (which is better for me anyway)

> this length is actually controlled by company and could be reduced AFAIK

Thx for the suggestion @ananthakumaran !

**Comment by it6** [comment]
I have `(setq company-minimum-prefix-length 3)` but I would still prefer autocomplete to show up as soon as my point is inside the quotes and I start typing `./` 

For example `sass` mode does this 

<img width="505" alt="screen shot 2018-03-29 at 7 20 31 am" src="https://user-images.githubusercontent.com/5510191/38086379-19ef9194-3322-11e8-9301-9e05aef01e59.png">

may be this is what @mbenedettini was asking for?

**Comment by mbenedettini** [comment]
As @it6 pointed out, I was talking about relative paths. It's correctly pulling installed modules but I'd like to get suggestions when I type `../` or `./` as it happens with most of major modes (I have already set `company-minimum-prefix-length` to 2). Otherwise it's pretty hard to write an import from a file within the same project.
