### ISSUE TITLE
Indentation not respecting tsfmt.json

### ISSUE THREAD

**Issue by kbdluv** [ananthakumaran/tide#229]
I set my `tsfmt.json` to:

```javascript
{
  "indentSize": 2,
  "tabSize": 2
}
```

But when I hit Enter, the new line is still indented 4 spaces in. Any way I can help debug this? Thanks!

**Comment by josteink** [comment]
This is strictly speaking not a `tide`-issue, but a `typescript-mode`-issue.

It could be argued though, that when tide is active and has resolved a `tsfmt.json` file (in `tide-command:configure`), it could try to override your `typescript-mode` defcustoms, not just pass the info along to `tsserver` for *its* formatting-rules.

Any opinions?

**Comment by kbdluv** [comment]
Sorry, didn't know about this interplay of packages. I'm using `tide`from the `typescript` layer of Spacemacs. Maybe I should report this there? Thank you for the reply.

**Comment by ananthakumaran** [comment]
Tide format only comes into play when you call `tide-format` or on save if you have `before-save-hook` set properly. `typescript-mode` doesn't support `tsfmt.json` now, probably you could open an issue there.

regarding the question of tide configuring typescript mode, I am not sure. tide also works with other mode like web-mode for tsx files, that means we also configure web-mode. `indentSize` is not the only option in tsfmt.json, there are options like `placeOpenBraceOnNewLineForControlBlocks` which might not have an equivalent in typescript-mode, so we might end up setting a wrong expectation.

**Comment by mvrbanec** [comment]
If you find it useful, I'm using this within my `setup-tide-mode` function (described in repository README). Basically if there is no _indentSize_ defined or _tsfmt.json_ doesn't exist, indent level is set to the default value of 4.

```elisp
(setq typescript-indent-level
        (or (plist-get (tide-tsfmt-options) ':indentSize) 4))
```

**Comment by kbdluv** [comment]
@mvrbanec thanks for the pointer to `typescript-indent-level`. Since it appears that `typescript-mode` doesn't use `tsfmt.json` either, I just went ahead and customized the `typescript-indent-level` variable to `2` and it worked.
