### ISSUE TITLE
Frozen on TypeDoc

### ISSUE THREAD

**Issue by janesser** [ananthakumaran/tide#231]
Hi,

i tried with http://typedoc.org/guides/doccomments/

whenever i type "/**" and then hit enter, emacs freezes and becomes unusable.
I've got to kill/restart it.

i can actually make that comment, but i must not push enter on that code-line.

Any hints?

**Comment by ananthakumaran** [comment]
do you invoke any `tide-*` commands? It's probably a problem with typescript-mode. Please open an issue there if it's typescript mode issue https://github.com/ananthakumaran/typescript.el/issues/new

**Comment by janesser** [comment]
Copied over to https://github.com/ananthakumaran/typescript.el/issues/65.
