### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by mzgnr** [ananthakumaran/tide#232]
Server not starting when i use https://github.com/rakanalh/emacs-dashboard and projectile . M-x pwd returns the path of project as expected.

![screen shot 2018-01-25 at 16 58 05](https://user-images.githubusercontent.com/6003317/35391892-0caeba4e-01f1-11e8-9953-17d6ec9076f2.png)

**Comment by mzgnr** [comment]
(setenv "PATH" (concat (getenv "PATH") ":/usr/local/bin"))
 (setq exec-path (append exec-path '("/usr/local/bin"))) fixes issue

**Comment by josteink** [comment]
Thanks for posting your findings.

If this works without `emacs-dashboard`, based on your posted fix, I would assume this is something which should be fixed in `emacs-dashboard` and in how it initializes its runtime environment.

**Comment by mzgnr** [comment]
The way I use emacs recently is "Keep in Dock " stuff because I don't like emacs takes one iterm tab just for running it . I open emacs from dock and change project or open project with emacs-dashboard. I also had issue with ansi-term ( I like terminal inside emacs ) with this approach. helm-projectile was working fine I think emacs has an issue with this approach. The snippet above fixes tide and ansi-term issues.
