### ISSUE TITLE
We need to provide more guidance for issue reporting.

### ISSUE THREAD

**Issue by lddubeau** [ananthakumaran/tide#246]
We've been having a number of issue reports lately that fell in these categories:

1. Issues reporting bugs that did not include the minimal information that should be present. In my view, common developer courtesy requires that issue reports include at a minimum: the relevant version numbers, a series of steps to reproduce the issue, actual results, expected results. I strive to always include this in my all my bug reports.

2. Problems that might go away by performing a series of minimal diagnostic steps. Or might be traceable to other tools than tide itself through diagnostic steps.

I see two things necessary:

1. A template for submitting issues to this project. (`ISSUE_TEMPLATE.md`). The template will contain a checklist of diagnostic steps to perform before submitting the issue, but I don't want to load that list with lots of details, so this brings up the next point...

2. A wiki page that explains the rationale for the diagnostic steps in greater details. I want to provide those details separately so that people who already know how it all works can just go through the checklist. People who don't already know can follow a link and read why, for instance, we're asking to issue `tide-restart-server` before deciding that there's a bug in tide.

I see the README has a [debugging](https://github.com/ananthakumaran/tide#debugging) section. I'm thinking that kind of debugging should not be part of the initial checklist but instead be brought up by us on a case by case basis.

I'm going to create the wiki page and the `ISSUE_TEMPLATE.md`, and I'm going to assign myself to this issue, which only means I'm not expecting anyone else to take the lead. Comments, concerns, suggestions are all welcome.

**Comment by josteink** [comment]
Great initiative! I agree about the problem and the general framework you’ve proposed as a decent improvement over what we have now. 

If we see that it doesn’t work out, we can tweak it along the way.
