### ISSUE TITLE
tide-on-response-success is defined and/or called incorrectly

### ISSUE THREAD

**Issue by lddubeau** [ananthakumaran/tide#248]
## Checklist

- [x] I have searched both open and closed issues and cannot find a duplicate.
- [x] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [x] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [x] I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.
- [ ] ~~If [tide *is reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should not be reported*, I can run `tsc` (and `tslint`, if applicable) without the error or warning I'm seeing in tide.~~
- [ ] ~~If [tide is *not reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should be reported*, `tsc` (or `tslint`, if applicable) reports the error or warning I was expecting to see.~~
- [x] I am [positive](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

## Relevant Version Numbers

- Tide: 8e5db30596627ad250caab75cecf56c175f6542f
- TypeScript: 2.8.1
- Emacs: 25.1.1

## Steps to Reproduce the Bug

1. Plop this in a typescript buffer:

```
function q(a: string, b: string): void {
}
```

2. Move to the start of the `function` keyword.

3. Issue `M-x tide-jsdoc-template`.

## Expected Behavior

The following template should be inserted before the function:

```
/**
 * 
 * @param a
 * @param b
 */
```

## Actual Behavior

The caret moves forward to the second `n` in the `function` keyword. No template is inserted.

## Observations.

The problem is how `tide-on-response-success` has been changed in a08c6999acf3ba06962c208770803c521c263d3c. I quickly looked at the old code and the code after the change. The old code **required** an argument before the executable body. Since the argument was always required, the calls to `tide-on-response-success` there was no possibility for confusion regarding what's what. The commit changed `tide-on-response-success` so that the first argument is optional, and this creates problems. In particular, the following code in `tide-jsdoc-template` is no longer correct:

```
    (tide-on-response-success response
      (save-excursion
        (tide-insert (tide-plist-get response :body :newText)))
      (forward-char (tide-plist-get response :body :caretOffset))))
```

The above call *means*  to have both `save-excursion` and `forward-char` be part of the executable body but `save-excursion` is interpreted as the optional argument and only `forward-char` is part of the body. So the only thing executed on success is `forward-char`. The code above can be trivially corrected by adding a `nil` argument after the `response` argument, or by wrapping `save-excursion` and `forward-char` in a `progn` block.

`tide-jsdoc-template` is just one case where there's a problem with the call to `tide-on-response-success`. A cursory inspection of tide's code reveals other places where the problem happens.

There are multiple possible fixes here and I'm not sure which one should be privileged. I'm not a fan just adding `progn` to work around the issue because it is just too easy imho to forget the need for `progn` where it is needed for the code to run correctly. So the two options I'd see are:

1. Make the optional argument mandatory, which means that even where the argument is not needed, `nil` must be passed.

2. Use `cl-defmacro` to make the optional argument a keyword argument so it is unambiguous when it is specified in a call.

**Comment by ananthakumaran** [comment]
> 2. Use cl-defmacro to make the optional argument a keyword argument so it is unambiguous when it is specified in a call.

I had tried this at the start, but `&key` & `&rest` couldn't be used in the same function, so settled on this version.

> 1. Make the optional argument mandatory, which means that even where the argument is not needed, nil must be passed.

Yes, we could do this, but our current version of jsdoc-template would still be accepted as a valid function call. What do you think of adding a validation for options? This would I guess catch all the invalid calls. I will open a PR and we could discuss there.
