### ISSUE TITLE
Symbol's function definition is void: tide-plist-map

### ISSUE THREAD

**Issue by nokilli** [ananthakumaran/tide#250]
When submitting issues to this project, please include the following information.

## Checklist

- [x] I have searched both open and closed issues and cannot find a duplicate.
- [x] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [ ] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [x] I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.
- [x] If [tide *is reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should not be reported*, I can run `tsc` (and `tslint`, if applicable) without the error or warning I'm seeing in tide.
- [x] If [tide is *not reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should be reported*, `tsc` (or `tslint`, if applicable) reports the error or warning I was expecting to see.
- [x] I am [positive](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

## Relevant Version Numbers

- Tide:
- TypeScript:
- Emacs:

(The list above is minimal. Make sure to include any other version numbers relevant to your report.)

## Steps to Reproduce the Bug

The more details you provide, the better your chance of getting a speedy resolution.

## Expected Behavior

The more details you provide, the better your chance of getting a speedy resolution.

## Actual Behavior

The more details you provide, the better your chance of getting a speedy resolution.

**Comment by nokilli** [comment]
Title says it all but here's the full line from *Compile-log*:

> Compiling file /home/somebody/.emacs.d/elpa/tide-20180420.431/tide.el at Sat Apr 21 18:31:12 2018
> tide.el:712:1:Error: Symbol’s function definition is void: tide-plist-map

FWIW, I had this working perfectly under Gentoo several weeks ago.  I just moved to Ubuntu in the last couple of days.  Confusing matters is that patches are being submitted in this same time frame.

I fully removed emacs and then also the contents of ~/.emacs.d and then reinstalled and the problem continues to persist.

**Comment by ananthakumaran** [comment]
can you check if you have any old `.elc` files around?. Also, provide a full stacktrace of the error.

**Comment by nokilli** [comment]
This is full *Compile-Log*:

> Compiling no file at Sat Apr 21 18:31:12 2018
> Leaving directory ‘/home/somebody/.emacs.d/elpa/tide-20180420.431’
> 
> Compiling file /home/somebody/.emacs.d/elpa/tide-20180420.431/tide-lv.el at Sat Apr 21 18:31:12 2018
> Entering directory ‘/home/somebody/.emacs.d/elpa/tide-20180420.431/’
> 
> Compiling file /home/somebody/.emacs.d/elpa/tide-20180420.431/tide.el at Sat Apr 21 18:31:12 2018
> tide.el:712:1:Error: Symbol’s function definition is void: tide-plist-map

I'm sorry but I'm kind of new to this and I don't know how else to do a stacktrace.

I fully removed emacs, as in, not just using package manager, but confirming later with find.  Also, a rm -rf ~/.emacs.d/* was performed.  But I'll keep checking to see if I missed something.

**Comment by nokilli** [comment]
Repeated the process with toggle-debug-on-error enabled with precisely the same result, only there was a long pause before the Compile_Log came up.

**Comment by ananthakumaran** [comment]
@nokilli my latest commit should fix the issue. It will probably take some time for it to be updated in melpa https://melpa.org/#/tide

**Comment by nokilli** [comment]
Yes, the compile problem is fixed.

I'm having other problems though but I'm pretty certain it's something on my end.

Thanks for the fast fix.
