### ISSUE TITLE
tide-jsx checker auto-enabling

### ISSUE THREAD

**Issue by vidjuheffex** [ananthakumaran/tide#251]
When submitting issues to this project, please include the following information.

## Checklist

- [x] I have searched both open and closed issues and cannot find a duplicate.
- [x] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [X] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [ X I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.
- [] If [tide *is reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should not be reported*, I can run `tsc` (and `tslint`, if applicable) without the error or warning I'm seeing in tide.
- [ ] If [tide is *not reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should be reported*, `tsc` (or `tslint`, if applicable) reports the error or warning I was expecting to see.
- [X] I am [positive](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

## Relevant Version Numbers

- Tide: 20180421.802
- TypeScript: n/a
- Emacs: 26.1

(The list above is minimal. Make sure to include any other version numbers relevant to your report.)

## Steps to Reproduce the Bug
tide-jsx checker is enabled 

## Expected Behavior
Without configuring the fly-check checker, tide-jsx checker should not be enabled.

## Actual Behavior

 i removed `(flycheck-add-next-checker 'javascript-eslint 'jsx-tide 'append)` from my config
Is says in the readme
>Tide checkers javascript-tide and jsx-tide are not enabled by default for js & jsx files. It can be enabled by setting flycheck-checker

When I restart emacs, and go to a tide-mode file if I check my flycheck, it has eslint and tide-jsx enabled. (and sometimes wont let me disable tide-jsx)

The more details you provide, the better your chance of getting a speedy resolution.

Here is my config:
(defun setup-tide-mode ()
  "Custom Tide setup function."
  (interactive)
  (tide-setup)
  (flycheck-mode +1)
  (setq flycheck-check-syntax-automatically '(save mode-enabled))
  (eldoc-mode +1)
  (tide-hl-identifier-mode +1)
  (company-mode +1))

(use-package tide
  :ensure t
  :config
  (add-hook 'js2-mode-hook 'setup-tide-mode))

**Comment by josteink** [comment]
Thanks for the detailed report. That said, I still don't quite understand what your problem is.

* Is your problem that `tide-jsx` is enabled when working with JSX-files without you explicitly enabling it? (Is it?)
* Or is your problem that `tide-jsx` is enabled in other contexts? (Does it?)
* Is the problem that the current behaviour is inconsistent with the documentation?

Also: How do you verify that `tide-jsx` is enabled?

**Comment by vidjuheffex** [comment]
Sorry I just now saw this:
Is your problem that tide-jsx is enabled when working with JSX-files without you explicitly enabling it? (Is it?)
^This one. and it is. I didn't add it to the list of checkers.

Secondly, im using flycheck verify setup to check. And it says eslint is on, jshint is off, and tide-jsx is on

**Comment by ananthakumaran** [comment]
I guess the wording may be slightly incorrect. For tide, we put our checker in the front, so you will likely get tide checker enabled by default for typescript. For others(js, jsx), we add it to the end of the list. So if there are other checkers like eslint/jshint etc, they will get enabled by default. Check [registering the checker](http://www.flycheck.org/en/latest/developer/developing.html#registering-the-checker) here for flycheck documentation.

**Comment by ajbarber** [comment]
I found tsx-tide auto enabling when I really wanted jsx-tide. To get things working for reactjs I had to explicitly disable tsx-tide:

`(setq-default flycheck-disabled-checkers
 (append flycheck-disabled-checkers
        '(tsx-tide)))
`

I hope this helps someone.
