### ISSUE TITLE
tide-nav should navigate to all symbols, not just types

### ISSUE THREAD

**Issue by sandersn** [ananthakumaran/tide#265]
In a program like this, tide-nav should allow me to navigate to `f` as well as `A`.

```ts
interface A {
  a: number
}
function f(a: A) {
  return a.a + 1
}
```
## Expected Behavior

tide-nav returns `A` and `f` (plus possibly other symbols)

## Actual Behavior

tide-nav returns `A`

Note that commenting out the filter expression in tide-nav (`(setq navto-items (-filter ...))`) gives me the behaviour I want. It makes sense to query just for types sometimes, but I don't think it should be the default.

## Checklist

- [x] I have searched both open and closed issues and cannot find a duplicate.
- [x] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [x] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [x] I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.
- [x] I am [positive](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

## Relevant Version Numbers

- Tide:20180212.2229 from elpa, but the relevant code is the same in master
- TypeScript: 3.0, built from master
- Emacs: 25.2.2

**Comment by ananthakumaran** [comment]
I guess the reasoning was not to show too many items, though it's not in the readme,  the function is documented as `Search and navigate to named types.`.

I guess we could revisit the decision. Some of the approaches are

1) make the filter configurable and set a sane default (my vote is for container elements like class/module/type/interface/enum)
2) we could change the behavior when called with a prefix arg (aka disable the filter)


```elisp
(-filter
 (lambda (navto-item) 
   (member (plist-get navto-item :kind) '("class" "interface" "type" "enum")))
 navto-items)
```

```typescript
    /**
     * An item found in a navto response.
     */
    export interface NavtoItem {
        /**
         * The symbol's name.
         */
        name: string;

        /**
         * The symbol's kind (such as 'className' or 'parameterName').
         */
        kind: ScriptElementKind;

        /**
         * exact, substring, or prefix.
         */
        matchKind?: string;

        /**
         * If this was a case sensitive or insensitive match.
         */
        isCaseSensitive?: boolean;

        /**
         * Optional modifiers for the kind (such as 'public').
         */
        kindModifiers?: string;

        /**
         * The file in which the symbol is found.
         */
        file: string;

        /**
         * The location within file at which the symbol is found.
         */
        start: Location;

        /**
         * One past the last character of the symbol.
         */
        end: Location;

        /**
         * Name of symbol's container symbol (if any); for example,
         * the class name if symbol is a class member.
         */
        containerName?: string;

        /**
         * Kind of symbol's container symbol (if any).
         */
        containerKind?: ScriptElementKind;
    }
```

```typescript
    export const enum ScriptElementKind {
        unknown = "",
        warning = "warning",

        /** predefined type (void) or keyword (class) */
        keyword = "keyword",

        /** top level script node */
        scriptElement = "script",

        /** module foo {} */
        moduleElement = "module",

        /** class X {} */
        classElement = "class",

        /** var x = class X {} */
        localClassElement = "local class",

        /** interface Y {} */
        interfaceElement = "interface",

        /** type T = ... */
        typeElement = "type",

        /** enum E */
        enumElement = "enum",
        enumMemberElement = "enum member",

        /**
         * Inside module and script only
         * const v = ..
         */
        variableElement = "var",

        /** Inside function */
        localVariableElement = "local var",

        /**
         * Inside module and script only
         * function f() { }
         */
        functionElement = "function",

        /** Inside function */
        localFunctionElement = "local function",

        /** class X { [public|private]* foo() {} } */
        memberFunctionElement = "method",

        /** class X { [public|private]* [get|set] foo:number; } */
        memberGetAccessorElement = "getter",
        memberSetAccessorElement = "setter",

        /**
         * class X { [public|private]* foo:number; }
         * interface Y { foo:number; }
         */
        memberVariableElement = "property",

        /** class X { constructor() { } } */
        constructorImplementationElement = "constructor",

        /** interface Y { ():number; } */
        callSignatureElement = "call",

        /** interface Y { []:number; } */
        indexSignatureElement = "index",

        /** interface Y { new():Y; } */
        constructSignatureElement = "construct",

        /** function foo(*Y*: string) */
        parameterElement = "parameter",

        typeParameterElement = "type parameter",

        primitiveType = "primitive type",

        label = "label",

        alias = "alias",

        constElement = "const",

        letElement = "let",

        directory = "directory",

        externalModuleName = "external module name",

        /**
         * <JsxTagName attribute1 attribute2={0} />
         */
        jsxAttribute = "JSX attribute",

        /** String literal */
        string = "string",
    }
```

**Comment by josteink** [comment]
> I guess the reasoning was not to show too many items

Agreed.

For bigger files, with big classes, and lots of nested/internal functions and local variables... A full `tide-nav` becomes unmanageable, even with completion frameworks like `helm`.

Iirc we've had concrete discussions on this, where people have complained about the amount of stuff returned.

Clearly we can't make everyone happy at the same time, so making this configurable sounds like a good idea.

**Comment by sandersn** [comment]
I like the idea of a prefix argument, since I believe the top two nav actions are "find everything" and "find types" (or "find containers"). Plus it makes it easy to bind both to separate keys, like VS Code does.

**Comment by ananthakumaran** [comment]
I just realized the prefix argument is already used. I wonder how often it's actually used because if the symbol under the cursor is valid, you could jump to the definition or type easily.

that said, if we make the filter configurable, it's quite easy to define a function which uses dynamic binding to disable the filter.

```elisp
(defun tide-nav-all ()
  (interactive)
  (let ((tide-nav-item-filter nil))
    (call-interactively #'tide-nav)))
```

should we add such a function in tide or it's too specific it should be defined in user config?

**Comment by sandersn** [comment]
I'm biased, but I would be writing that function anyway. :)

**Comment by josteink** [comment]
As the one guy who actually implemented the *current* prefix argument behaviour I'm obviously biased too, but to be honest if other people see other uses for this overload, I'm not 100% married to it either.

> I just realized the prefix argument is already used. I wonder how often it's actually used because if the symbol under the cursor is valid, you could jump to the definition or type easily.

It's clearly *more work*, but obviously we can't have direct shortcuts for everything, at least not by default.

If we can find a reasonably configurable way which leaves room for other people to have their way too, I'm not going to object to any such changes.

**Comment by ananthakumaran** [comment]
I think we can just make the `tide-nav-item-filter` configurable for now and add `tide-nav-all` later if more people ask for it.

**Comment by ananthakumaran** [comment]
closing this as the fix is already merged
