### ISSUE TITLE
Question regarding "navto" protocol

### ISSUE THREAD

**Issue by cmccloud** [ananthakumaran/tide#266]
The [tsserver communication protocol](https://github.com/Microsoft/TypeScript/blob/master/lib/protocol.d.ts) describes '.*' as being an acceptable argument for the "navto" request, in lieu of a prefix. Despite that, `(tide-command:navto ".*")` returns an empty body. Any suggestions as to what I'm doing wrong? I am under the impression that the response to the above command should be the collection of all the valid navigation items in the project. 

Thanks!

**Comment by ananthakumaran** [comment]
could you check the logs which will have the exact request/response. I guess it's likely emacs is likely filtering out because the prefix `.*` doesn't match the results

**Comment by ananthakumaran** [comment]
I am not sure if the documentation is correct, I tried locally and get 0 results from tsserver
```
    {"command":"navto","seq":"183","arguments":{"file":"/Users/ananthakumaran/work/repos/TypeScript/src/compiler/types.ts","searchValue":".*","maxResultCount":100}}
Info 432  [9:39:44.663] response:
    {"seq":0,"type":"response","command":"navto","request_seq":"183","success":true,"body":[]}
```
Though using `*` after/between text works `asf*` or `asdf*ghe`

**Comment by ananthakumaran** [comment]
closing this, reopen if anything could be done in tide side.

**Comment by cmccloud** [comment]
Fair enough, thanks for the quick response.
