### ISSUE TITLE
Errors no longer highlighted in compilation-mode

### ISSUE THREAD

**Issue by KevinVillela** [ananthakumaran/tide#269]
When submitting issues to this project, please include the following information.

## Relevant Version Numbers

- Tide: Most Recent
- TypeScript: 2.7
- Emacs: 25

## Steps to Reproduce the Bug
Between TS 2.6 and 2.7 (so maybe around May 2018) they changed the format of the error messages, resulting in next-error not always working in compilation-mode.
I believe this needs to be updated: https://github.com/ananthakumaran/typescript.el/blob/a922c27e95948a13e6a72e2620ca592a744721a7/typescript-mode.el#L2529.

**Comment by josteink** [comment]
Issue filed in wrong repo, but yes I agree.

**Comment by KevinVillela** [comment]
Lol the best part is that I even linked to the code. My mistake, will refile if it doesn't exist already.

**Comment by KevinVillela** [comment]
Filed https://github.com/ananthakumaran/typescript.el/issues/77.
