### ISSUE TITLE
Screen recentering causes tide-jump-to-definition to be slow in large buffers

### ISSUE THREAD

**Issue by sandersn** [ananthakumaran/tide#271]
## Relevant Version Numbers

- Tide: 2018 06 08
- TypeScript: 2.9.2 and master
- Emacs: 25.2.2

## Steps to Reproduce the Bug

Clone the Typescript repo and open src/compiler/checker, which is almost 30,000 lines long. Search for getSignatureFromDeclaration. Then when an invocation of it is found, do tide-jump-to-definition. On my machine it takes about a second. Some other declarations take even longer to navigate to.

## Expected Behavior

Jump to definition takes <200 ms.

## Actual Behavior

Jump to definition takes >1 s.

## Discussion

Turning off tide-recenter-after-jump makes jumping to definition fast again. I don't know much about elisp, but maybe `count-screen-lines` or `line-number-at-pos` are linear/log-linear in the size of the buffer? I experimented with the following function and count-screen-lines did seem to be slow in checker.ts, but I'm not sure it accounts for the entire slowdown. I haven't traced the tsserver logs to make sure that the slowdown isn't there. However, since the slowdown goes away entirely when I turn off tide-recenter-after-jump, I think the evidence points strongly to it as the culprit.

```elisp
(defun maybe-slow (&optional arg)
  (interactive "P")
  (count-screen-lines)
  (message "doesn't seem to appear")
  (line-number-at-pos)
  (message "doing something"))
```

## Checklist

- [x] I have searched both open and closed issues and cannot find a duplicate.
- [x] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [x] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [x] I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.
- [x] I am [90% certain](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

**Comment by josteink** [comment]
Sorry about the slow reply. I've been on vacation (still am actually), so haven't been able to keep up much.

Thanks for the detailed analysis.

I think we pretty honestly can admit that none of us tested or considered a 30k line file when doing this feature. Historically Emacs have had more performance-issue with long lines rather than many, so this may be a reason why we didn't give it any particular concern.

I agree that this is bad for a good flow though, especially when trying to dig into foreign code.

If there is a better way to determine the recenter'ed-ness of the jump, I'm all for it.

**Comment by josteink** [comment]
We have this code which we use in tide to determine "recenteredness":

https://github.com/ananthakumaran/tide/blob/62e171d226d5e67f40ca1eb47d3c521482070e6b/tide.el#L779-L782

Looking at that algorithm the core of it is the boolean check below:

````elisp
(> line-diff (count-screen-lines))
````

Seeing this, I automatically assumed it checked `line-diff` against the number of *lines on screen* (which should be fairly fast to compute). I assume he who wrote this code, @invokesus , may have assumed the same.

However when testing this function interactively using `M-: (count-screen-lines)` inside `checker.ts` it's immediately obvious to me that this counts the *total number* of "screen-lines" in the file. Basically it needs to process the whole buffer.

And you can tell. It's slow. (Conversely, just checking `M-: (line-number-at-pos)` is significantly faster.)

The documentation for count-screen-lines makes this abundantly clear as it says this function can be used even when a buffer is not displayed in any window.

> Like ‘vertical-motion’, ‘count-screen-lines’ always uses the current buffer,
> regardless of which buffer is displayed in WINDOW.  This makes possible to use
> ‘count-screen-lines’ in any buffer, whether or not it is currently displayed
> in some window.

So to me, this actually seems to be 2 bugs:

* logic bug: code does not check what we assumed it checked
* performance bug: things are slow.

Hopefully fixing the first should be easy, and should in the process also fix the second.

Or have I missed something?

cc: @lddubeau @ananthakumaran

**Comment by josteink** [comment]
Based on [the documentaiton](https://www.gnu.org/software/emacs/manual/html_node/elisp/Window-Sizes.html), I think the function we should be using instead of `(count-screen-lines)` is `(window-body-height)`.

(Which for the record is very, very fast.)

Or does anyone else have a better candidate?
