### ISSUE TITLE
Autocompletion doesn't work in ts in template strings

### ISSUE THREAD

**Issue by kreedz** [ananthakumaran/tide#272]
Is it possible to add the autocompletion in template strings?

Or should I ask about it in company-mode issues?

**Comment by ananthakumaran** [comment]
<img width="383" alt="screen shot 2018-07-22 at 6 20 33 pm" src="https://user-images.githubusercontent.com/149238/43045762-5588573a-8ddc-11e8-8d43-bb1911f9a9c1.png">

seems to work for me, could you minimal example where auto completion is not working? Note, company only triggers autocomple after you type atleast 3 characters by default.

**Comment by kreedz** [comment]
I didn't mention that I've experienced the problem in *.ts file.
Now I've just find out that in *.js the problem is not present.

Minimal init.el:
```elisp
;; list the packages you want
(setq package-list
      '(company
	js2-mode
        tide))

;; list the repositories containing them
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ("marmalade" . "https://marmalade-repo.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")))

;; activate all the packages (in particular autoloads)
(package-initialize)

;; fetch the list of packages available 
(unless package-archive-contents
  (package-refresh-contents))

;; install the missing packages
(dolist (package package-list)
  (unless (package-installed-p package)
    (package-install package)))


;; tide
(defun setup-tide-mode ()
  (interactive)
  (tide-setup)
  (eldoc-mode +1)
  (tide-hl-identifier-mode +1)
  (company-mode +1))

;; formats the buffer before saving
(add-hook 'before-save-hook 'tide-format-before-save)
(add-hook 'typescript-mode-hook #'setup-tide-mode)

;; js
(require 'js2-mode)
(require 'tide)
(add-to-list 'auto-mode-alist '("\\.js\\'" . js2-mode))
(add-hook 'js2-mode-hook #'setup-tide-mode)
```

**Comment by ananthakumaran** [comment]
btw, the screenshot I had shared is from a ts file

**Comment by kreedz** [comment]
Have you checked if autocompletion work with my provided init.el?

**Comment by ananthakumaran** [comment]
![screen shot 2018-07-25 at 10 49 49 am](https://user-images.githubusercontent.com/149238/43180960-8c6b0d92-8ff8-11e8-9454-446dcc946a0e.png)

In the repo, you can find a make task to start emacs in a sandbox mode with tide pre-installed. I installed company via package-install and tested a buffer, it works without issue.

**Comment by ananthakumaran** [comment]
Closing this, reopen if you can reproduce it in with a sandboxed emacs
