### ISSUE TITLE
Error from syntax checker typescript-tide: End of buffer

### ISSUE THREAD

**Issue by jcubic** [ananthakumaran/tide#276]
When submitting issues to this project, please include the following information.

## Checklist

- [x] I have searched both open and closed issues and cannot find a duplicate.
- [x] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [x] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [x] I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.
- [ ] If [tide *is reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should not be reported*, I can run `tsc` (and `tslint`, if applicable) without the error or warning I'm seeing in tide.
- [ ] If [tide is *not reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should be reported*, `tsc` (or `tslint`, if applicable) reports the error or warning I was expecting to see.
- [x] I am [positive](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

## Relevant Version Numbers

- Tide: 3.0.1
- TypeScript: (can't find tslib installed by npm using nvm)
- Emacs: GNU Emacs 25.0.50.1
- OS: windows 7

(The list above is minimal. Make sure to include any other version numbers relevant to your report.)

## Steps to Reproduce the Bug

I've installed tslib from npm globally set tsconfig.json to (project I'm working on don't have that file, don't know why, without this file I got error that tslib was not found).

```
{
    "moduleResolution": "node"
}
```

I have this in .emacs file:

```lisp
;; ----------------------------------------------------------
;; TypeScript
(defun setup-tide-mode ()
  (interactive)
  (tide-setup)
  (flycheck-mode +1)
  (setq flycheck-check-syntax-automatically '(save mode-enabled))
  (eldoc-mode +1)
  (tide-hl-identifier-mode +1)
  ;; company is an optional dependency. You have to
  ;; install it separately via package-install
  ;; `M-x package-install [ret] company`
  (company-mode +1))

;; aligns annotation to the right hand side
(setq company-tooltip-align-annotations t)

;; formats the buffer before saving
(add-hook 'before-save-hook 'tide-format-before-save)

(add-hook 'typescript-mode-hook #'setup-tide-mode)
```

If I open the ts file or reload it I've got error:

> Error from syntax checker typescript-tide: End of buffer

the file is valid typescript because I don't get error when I compile it using tsc.

commenting out flycheck in setup function hide the error.

## Expected Behavior

it should open file without error

## Actual Behavior

it show error in messages

**Comment by ananthakumaran** [comment]
> I've installed tslib from npm globally set tsconfig.json to (project I'm working on don't have that file, don't know why, without this file I got error that tslib was not found).

I don't understand this sentence. Tide will try to find `tsserver` executable in well-known locations and if not found it will try to fall back to the bundled tsserver. Not sure where the problem lies. You could try to 

1) set the variable explicitly like `(setq tide-tsserver-executable "node_modules/typescript/bin/tsserver")`
2) make sure the `tsserver` binary can be started without errors from the command line `$> tsserver`

if that doesn't solve the issue, please provide more info like any errors thrown by tide etc.

**Comment by jcubic** [comment]
Sorry, I don't know what I did but the error go away. And I had tsconfig.json somewhere up in directory tree, I've deleted that file and it work.

Sorry once more and thanks for this awesome project.
