### ISSUE TITLE
compilation-mode for `tsc -w`

### ISSUE THREAD

**Issue by vemv** [ananthakumaran/tide#285]
Hey there,

I'd like to throw an idea. Can give it a shot myself if it sounds desirable.

## The problem

running `tsc -w` inside a Emacs-owned terminal emulator isn't the best UX.

## Possible solution

Use `compilation-start` and friends, as in: https://github.com/rubocop-hq/rubocop-emacs/blob/0ab1329a8634762bec5bdf5f415c05b32f990248/rubocop.el#L129

Dunno if compilation-mode is adequate for constantly-running processes (as opposed to one-off compilations), but it seems likely to me.

WDYT?

Victor

**Comment by josteink** [comment]
So basically... You want better support for continuous, always watching compilation?

I can't speak for everyone, but most of my TS-projects have a pretty complex build pipeline, where tsc is only a small part of the build, and sometimes I don't even invoke it directly (it goes through browserify/webpack plugins instead).

Also if I edit anything with tide enabled, and I enter something which IS a syntax- or type-error, tide (through tslint/flycheck) will instantly highlight these errors, without any need for `tsc -w`.

So for me, dedicated support for `tsc -w` would not provide much value, but I'm obviously only talking for myself. Is use of this mode common in the rest of the typescript universe?

**Comment by vemv** [comment]
Hey folks,

thanks for the input. You are right in pointing out that `tsc -w` isn't a good workflow beyond a sample project. TS newbie here.

Worth noting that I had ommitted `flycheck` in my setup. I generally dislike red squiggly lines, but I think they make a lot of sense here (they don't as much in e.g. Clojure).

Assuming flycheck will give me the same useful errors `tsc` gives me, then this issue seems good to close.
