### ISSUE TITLE
Saving a given TS buffer should refresh other buffers' flycheck status

### ISSUE THREAD

**Issue by vemv** [ananthakumaran/tide#286]
Given two TypeScript buffers A and B:

* If I save A, _breaking B with that change_, then I'd immediately expect buffer B's flycheck markers to become red. However this doesn't appear to happen.
* Similarly, if I save A _in order to fix B_, then I'd immediately expect buffer B's flycheck red markers to disappear.

Is this a known issue? Or a flaw in my setup maybe?

For the record, I reproduced the issue looking at A and B at the same (i.e using 'splits').

**Comment by ananthakumaran** [comment]
Flycheck decides when to run the check. You have certain level of control over the trigger process http://www.flycheck.org/en/latest/user/syntax-checks.html#variable-flycheck-check-syntax-automatically, But I don't know if what you ask could be done in any way. Normally I use `tide-project-errors` in these situations

**Comment by vemv** [comment]
Thanks for the reply!

I see. Unfortunate one.

Perhaps some hack is possible, e.g. On every `save-buffer` of a given TS file, all other TS files belonging to the same project will be re-analyzed.

**Comment by vemv** [comment]
Given this issue isn't specific to Tide (see e.g. https://github.com/flycheck/flycheck-rust/issues/56), the right thing seems to close this issue.

I implemented my described hack in https://github.com/vemv/.emacs.d/commit/09a7d43fcc907dc65526f7a0f8c93deb205436ea . My .emacs isn't ready for external consumption, but the algo is simple:

1.- If I save buffer B belonging to project P, save all other buffers under P too. Saves are scheduled for 3.5 seconds from now, to give time `tsc` to complete its work
2.- On every save, files are `touch`ed
3.- Infinite recursion in step 1 should be avoided.
