### ISSUE TITLE
Deciding when to drop support for old Emacs versions.

### ISSUE THREAD

**Issue by lddubeau** [ananthakumaran/tide#292]
@josteink and I began talking about it on #279 but I think this deserves its own discussion. Specifically, I'd like @ananthakumaran to chime in.

When a contributor produces a PR, and the PR fails on an old version of Emacs, then in order to get the PR to run on the old version, the contributor has to research the failure and pour in more time into amending the PR to run on the old version of Emacs.

If we can find a limit to how old a version of Emac `tide` supports, then we can limit the time cost of supporting old versions. *And it would be nice to have a simple rule that collaborators can apply, rather than have to discuss it over and over.*

The initial discussion in #279 centered on checking what version of Emacs various distributions ship. Ubuntu 16.04 LTS ships 24.5. Debian 9 (the latest stable Debian release) ships 24.5 too, but I had forgotten that Debian 8 is a LTS, which ships 24.4. However, Ubuntu 14.04 is also an LTS that has not reached end of life yet (this happens in April 2019) and it ships 24.3, as far as I can tell.

We could have for rule that 

> `tide` is guaranteed to run on an Emacs version as old as the oldest version currently shipped by default by the latest two active LTSes of `[some distribution(s)]`. (An "active LTS" being one that has not yet reached end-of-life.) 

We have to decide on `some distribution(s)`. As a practical matter we cannot check all distributions out there so we have to limit the list. It could be just Ubuntu though I'm biased and would like Debian included because I use Debian everywhere. Though I think practically I'd be able to get by if we track only Ubuntu, through installing Emacs from the `...-backports` distribution.

"the latest two active LTSes" has for effect to limit how far back we look. Looking at Ubuntu today, it would limit the check to 18.04 and 16.04, and exclude 14.04.

Or maybe there's a better rule than the one above. Or maybe no rule and we have to raise an issue every time we consider dropping an old version, but I'd rather have some basic rule that we can also put in the README so users know what to expect.

----

Since the issue came up in #279, I'll mention that my desire to fix the backward compatibility issue there would be to drop testing on 24.3. I'm expecting that modifying the code for 24.5 will also make it work for 24.4, but 24.3 requires more work, and requires uglier modifications than for 24.5.

**Comment by ananthakumaran** [comment]
I checked 3 other packages, flycheck 24.3, company-mode 24.3, magit 25.1. Seems like most of the packages requires atleast 24.3. Given that tide will be mostly used in developer workstation, I am ok with dropping 24.3 if it would lead to less work on development side.

> the latest two active LTSes

This sounds like a good guideline to me.

**Comment by lddubeau** [comment]
I'm going to close this. It's been addressed in #293 and [explained in this wiki page](https://github.com/ananthakumaran/tide/wiki/Supported-Emacs-Versions).
