### ISSUE TITLE
Allow configuring tide to avoid starting tsserver immediately

### ISSUE THREAD

**Issue by lddubeau** [ananthakumaran/tide#294]
This is a suggestion for a new feature.

### The Problem

I use session management to record my Emacs session and restore it when I start Emacs again. I've used this setup for years. The only time I've had a problem before was with flymake but I fixed that by switching to flycheck. However, recently tide has started giving me issues, indirectly. I have a hand in a lot of different TypeScript projects. Restoring a session has become really slow due to all the `tsserver` instances that are immediately started and compete for CPU. It has been a problem for a long time but recently it's become unbearable. Maybe TS 3 has features that cause `tsserver` to need more processing power. I don't know. I've definitely been doing things that require me to restart Emacs more often lately. Right now, when I restart Emacs I have `pkill -f tsserver` at the ready to kill all `tsserver` instances. (Fortunately, Emacs is the only tool I use that starts `tsserver`.) Then I start them manually as needed.

### The Proposal

I'd like to be able to set a configuration variable such that the variable can be set to tell `tide-setup` to skip starting `tsserver` immediately. I'd be perfectly happy with having to issue `tide-restart-server` manually (like I'm doing now) whenever I need it. I thought about starting `tsserver` lazily: whenever tide needs it and `tsserver` is absent, then tide would start it automatically, but I'd be happy even without this functionality.

I volunteer for implementing this, but if there are concerns or flat out objections I'd rather hear about them ahead of time.

**Comment by josteink** [comment]
I would assume there are various kinds of invocations which I would assume only occurs on actual end-user interaction:

* completion at point
* fetching eldoc
* looking up documentation

Etc.

Maybe we can try to lazy-load tsserver (and "configure" the buffer) when these kind of functions get invoked?

And that works out well... Maybe we won't need a preference at all?

**Comment by lddubeau** [comment]
Oops... forgot to close this when #303 was merged.
