### ISSUE TITLE
 tide-completion-ignore-case not work

### ISSUE THREAD

**Issue by psychehao** [ananthakumaran/tide#295]
When submitting issues to this project, please include the following information.

## Checklist

- [x] I have searched both open and closed issues and cannot find a duplicate.
- [x] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [ ] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [ ] I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.
- [ ] If [tide *is reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should not be reported*, I can run `tsc` (and `tslint`, if applicable) without the error or warning I'm seeing in tide.
- [ ] If [tide is *not reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should be reported*, `tsc` (or `tslint`, if applicable) reports the error or warning I was expecting to see.
- [ ] I am [positive](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

## Relevant Version Numbers

- Tide:
- TypeScript:
- Emacs:

(The list above is minimal. Make sure to include any other version numbers relevant to your report.)

## Steps to Reproduce the Bug

The more details you provide, the better your chance of getting a speedy resolution.

## Expected Behavior

The more details you provide, the better your chance of getting a speedy resolution.

## Actual Behavior

The more details you provide, the better your chance of getting a speedy resolution.

**Comment by psychehao** [comment]
i set tide-completion-ignore-case to t ,but it seems not working

**Comment by ananthakumaran** [comment]
Please include a minimal test case.

**Comment by psychehao** [comment]
in the tide config file i use this expression: (setq** tide-always-show-documentation t), and use expression: (setq company-minimum-prefix-length 1) to auto complete when i type any char at beginning. but when i type a lower-case char, company completion with case sensitive at point.

![peek 2019-01-21 17-05](https://user-images.githubusercontent.com/970710/51463735-f42ae180-1d9e-11e9-8c09-38bfe59dc7e5.gif)

**Comment by psychehao** [comment]
> Please include a minimal test case.

in the tide config file i use this expression: (setq** tide-always-show-documentation t), and use expression: (setq company-minimum-prefix-length 1) to auto complete when i type any char at beginning. but when i type a lower-case char, company completion with case sensitive at point.

![peek 2019-01-21 17-05](https://user-images.githubusercontent.com/970710/51463735-f42ae180-1d9e-11e9-8c09-38bfe59dc7e5.gif)

**Comment by ananthakumaran** [comment]
refer #68. The completion will only disable case sensitive filtering on company-mode (emacs side). There is no option in the protocol to request case insentive results from tsserver.

**Comment by ananthakumaran** [comment]
I found one place where the config was not respected. https://github.com/ananthakumaran/tide/commit/7a6d6247ef6fbf534705ec6284a8594b48d4c00c I pushed a fix to master, this should fix your issue.

**Comment by psychehao** [comment]
@ananthakumaran 
okay, this push fix the issue.  thx!
