### ISSUE TITLE
Failing Compilation/Multiple Errors: Symbol’s function definition is void: -lambda

### ISSUE THREAD

**Issue by awood45** [ananthakumaran/tide#298]
When submitting issues to this project, please include the following information.

## Checklist

- [x] I have searched both open and closed issues and cannot find a duplicate.
- [x] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [x] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [x] I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.
- [x] If [tide *is reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should not be reported*, I can run `tsc` (and `tslint`, if applicable) without the error or warning I'm seeing in tide.
- [x] If [tide is *not reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should be reported*, `tsc` (or `tslint`, if applicable) reports the error or warning I was expecting to see.
- [x] I am [positive](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

## Relevant Version Numbers

- Tide: tide-20190121.1413
- TypeScript: 3.2.4
- Emacs: 26.1 (OSX)

(The list above is minimal. Make sure to include any other version numbers relevant to your report.)

## Steps to Reproduce the Bug

I got this straight off of installation, and it recurs repeatedly anytime I am in any TypeScript project.

## Expected Behavior

Error-free compilation.

## Actual Behavior

The following stacktrace:
```
Leaving directory ‘/Users/alexwood/.emacs.d/elpa/tide-20190121.1413’
^L
Compiling file /Users/alexwood/.emacs.d/elpa/tide-20190121.1413/tide-lv.el at Tue Jan 29 17:53:16 2019
Entering directory ‘/Users/alexwood/.emacs.d/elpa/tide-20190121.1413/’
^L
Compiling file /Users/alexwood/.emacs.d/elpa/tide-20190121.1413/tide.el at Tue Jan 29 17:53:16 2019
^L
Compiling no file at Tue Jan 29 17:53:17 2019
Warning (bytecomp): ‘(key value)’ is a malformed function
Warning (bytecomp): reference to free variable ‘key’
Warning (bytecomp): reference to free variable ‘value’
Error (bytecomp): Symbol’s function definition is void: -lambda
```

This does appear to be different than the previous issue noting the same error, but I am not 100% sure.

**Comment by ananthakumaran** [comment]
This looks like a macro compilation issue. Could you make sure you have
recent version of dash and there are no compiled code (.elc files) of old
version of dash in the load path.

**Comment by awood45** [comment]
Yep, it looks like there was an old version of dash that needed a good cleaning. Which probably also explains why this was seamless on exactly one of my machines. Cheers!
