### ISSUE TITLE
Support web-mode

### ISSUE THREAD

**Issue by martine** [ananthakumaran/tide#3]
I use web-mode to edit TypeScript files, due to its support of JSX (see https://github.com/ananthakumaran/typescript.el/issues/4 ).

It would be nice to use tide's flymake support with these files.  Maybe tide could hook in when web-mode recognizes a TypeScript file?  (Alternatively, fixing https://github.com/ananthakumaran/typescript.el/issues/4 would solve this problem too.)

**Comment by ananthakumaran** [comment]
master now supports web-mode
