### ISSUE TITLE
Defining project root?

### ISSUE THREAD

**Issue by mathpunk** [ananthakumaran/tide#305]
I cannot attest to these two, which is my problem---

- [ ] I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.
- [ ] I am [positive](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

I have been using tide-mode with the documented configuration and no problem. I don't know what changed --- now tide-mode/tsserver is unable to find my project root, and selects one more or less at random. 

`tide-verify-setup` yields:
```
config file path: /dev/null/inferredProject1*
```
whereas `tide-setup` has no visible effect nor any output to *Messages*.

## Checklist

- [x] I have searched both open and closed issues and cannot find a duplicate.
- [x] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [x] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [x] If [tide *is reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should not be reported*, I can run `tsc` (and `tslint`, if applicable) without the error or warning I'm seeing in tide.
- [x] If [tide is *not reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should be reported*, `tsc` (or `tslint`, if applicable) reports the error or warning I was expecting to see.

## Relevant Version Numbers
- Tide: 20190215.648
- tsserver: 3.2.2
- TypeScript: 3.2.0
- Emacs: 26.1

**Comment by josteink** [comment]
We have the defcustom `tide-tsserver-locator-function` which relies on (among other things) projectile to find a project root, not to mention we look for the topmost ("dominating") `tsconfig.json` (or `jsconfig.json`).

What path does projectile report as the project root if you try to open files?

Also what does the following command output?

````sh
cd $actual_project_root
find . -iname tsconfig.json
````

Is more than one instance listed?

**Comment by geoffp** [comment]
I have the same issue. I've confirmed that projectile knows what's going on, and I get this:
```
./node_modules/jest-runtime/tsconfig.json
./node_modules/jest-matcher-utils/tsconfig.json
./node_modules/jest-docblock/tsconfig.json
./node_modules/sift/tsconfig.json
./node_modules/opentracing/tsconfig.json
./node_modules/diff-sequences/tsconfig.json
./node_modules/jest-worker/tsconfig.json
./node_modules/@jest/test-sequencer/tsconfig.json
./node_modules/@jest/types/tsconfig.json
./node_modules/@jest/core/tsconfig.json
./node_modules/@jest/fake-timers/tsconfig.json
./node_modules/@jest/environment/tsconfig.json
./node_modules/@jest/source-map/tsconfig.json
./node_modules/@jest/test-result/tsconfig.json
./node_modules/@jest/reporters/tsconfig.json
./node_modules/@jest/transform/tsconfig.json
./node_modules/@jest/console/tsconfig.json
./node_modules/chrome-trace-event/tsconfig.json
./node_modules/jest-cli/tsconfig.json
./node_modules/babel-jest/tsconfig.json
./node_modules/apollo-link/node_modules/ts-invariant/tsconfig.json
./node_modules/jest-resolve/tsconfig.json
./node_modules/jest-watcher/tsconfig.json
./node_modules/react-draggable/typings/tsconfig.json
./node_modules/webpack-cli/node_modules/rxjs/src/tsconfig.json
./node_modules/jest-serializer/tsconfig.json
./node_modules/jest-runner/tsconfig.json
./node_modules/jest-leak-detector/tsconfig.json
./node_modules/synchronous-promise/tsconfig.json
./node_modules/xstate/tsconfig.json
./node_modules/xstate/editor/tsconfig.json
./node_modules/jest-haste-map/tsconfig.json
./node_modules/jest-environment-node/tsconfig.json
./node_modules/jest-util/tsconfig.json
./node_modules/jest-get-type/tsconfig.json
./node_modules/uri-js/tsconfig.json
./node_modules/jest-snapshot/tsconfig.json
./node_modules/jest-message-util/tsconfig.json
./node_modules/jest-validate/tsconfig.json
./node_modules/rxjs/src/tsconfig.json
./node_modules/emotion-theming/types/tsconfig.json
./node_modules/pretty-format/tsconfig.json
./node_modules/jest-each/tsconfig.json
./node_modules/jest-mock/tsconfig.json
./node_modules/babel-plugin-jest-hoist/tsconfig.json
./node_modules/@storybook/addons/tsconfig.json
./node_modules/@storybook/core-events/tsconfig.json
./node_modules/@storybook/theming/tsconfig.json
./node_modules/@storybook/addon-notes/tsconfig.json
./node_modules/@storybook/channels/tsconfig.json
./node_modules/@storybook/client-logger/tsconfig.json
./node_modules/@storybook/router/tsconfig.json
./node_modules/@emotion/styled-base/types/tsconfig.json
./node_modules/@emotion/stylis/types/tsconfig.json
./node_modules/@emotion/styled/types/tsconfig.json
./node_modules/@emotion/core/types/tsconfig.json
./node_modules/@emotion/cache/types/tsconfig.json
./node_modules/@emotion/css/types/tsconfig.json
./node_modules/@emotion/serialize/types/tsconfig.json
./node_modules/@emotion/utils/types/tsconfig.json
./node_modules/@emotion/is-prop-valid/types/tsconfig.json
./node_modules/@emotion/sheet/types/tsconfig.json
./node_modules/jest-changed-files/tsconfig.json
./node_modules/jest-jasmine2/tsconfig.json
./node_modules/jest-diff/tsconfig.json
./node_modules/devcert-san/tsconfig.json
./node_modules/jest-resolve-dependencies/tsconfig.json
./node_modules/ts-invariant/tsconfig.json
./node_modules/jest-config/tsconfig.json
./node_modules/jest-regex-util/tsconfig.json
./node_modules/jest-environment-jsdom/tsconfig.json
./node_modules/jest/tsconfig.json
./node_modules/expect/tsconfig.json
./packages/redacted-react/node_modules/@storybook/ui/tsconfig.json
./packages/redacted-react/node_modules/@storybook/channel-postmessage/tsconfig.json
./packages/redacted-react/node_modules/@storybook/node-logger/tsconfig.json
./packages/storybook-addon-hostile/node_modules/@storybook/addons/tsconfig.json
./packages/storybook-addon-hostile/node_modules/@storybook/core-events/tsconfig.json
./packages/storybook-addon-hostile/node_modules/@storybook/channels/tsconfig.json
./packages/storybook-addon-hostile/node_modules/@storybook/client-logger/tsconfig.json
./tsconfig.json
```

**Comment by cpjolicoeur** [comment]
Just to add on, `tsconfig.json` isn't the only allowable config file name.  For example, I have some client projects that use `.tsconfig.json` .  Is there a way to configure the tsconfig file name to search for?

**Comment by josteink** [comment]
@cpjolicoeur

Is this solved by https://github.com/ananthakumaran/tide/pull/321 ?

**Comment by ananthakumaran** [comment]
@cpjolicoeur you could read the comments on https://github.com/ananthakumaran/tide/issues/242 for supporting custom config file. Essentially, if tsc supports it, we could add support here. But if there is another layer that creates tsconfig.json, then it would be hard to add support in tide.

A minimal project which demonstrates the issue would be helpful. With these kinds of problem, it hard to speculate where the reason is, without having any way to reproduce it locally.

**Comment by cpjolicoeur** [comment]
> @cpjolicoeur
> 
> Is this solved by #321 ?

@josteink Not sure, but I'll try to check it out and let you know when I have some time this week.

**Comment by cpjolicoeur** [comment]
> @cpjolicoeur you could read the comments on #242 for supporting custom config file. Essentially, if tsc supports it, we could add support here. But if there is another layer that creates tsconfig.json, then it would be hard to add support in tide.
> 
> A minimal project which demonstrates the issue would be helpful. With these kinds of problem, it hard to speculate where the reason is, without having any way to reproduce it locally.

I can try to make a small project sample, but `tsc` definitely supports it via the `--project` flag: [https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#using-tsconfigjson](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#using-tsconfigjson)

Using `-p` you can point directly to a valid json configuration file.

**Comment by ananthakumaran** [comment]
Please read https://github.com/ananthakumaran/tide/issues/242#issuecomment-408995380 which explains the issue with the custom project file. It might be possible to add support in tide, but nobody has stepped up and done the work so far.

**Comment by paxperscientiam** [comment]
@ananthakumaran I'm using the same version. `tide-project-root` is correctly defined -- which suggests that tide *is* finding tsconfig.json; however, `tide-verify-project` still yields something like "/dev/null/inferredProject1*"

**Comment by ananthakumaran** [comment]
@paxperscientiam check the tsserver [logs](https://github.com/ananthakumaran/tide#debugging), which might have some information. Otherwise, we need a minimal project that we can use to reproduce the issue.

**Comment by paxperscientiam** [comment]
@ananthakumaran Hm, well. i just made a minimal project and tide is working. So, it seems the problem is *not* tide (hooray), but instead the problem is my project (d'oh!).

Sorry about my confusion.

**Comment by wol81** [comment]
I think I'm having something like this problem in my project.  It's my first contact with TypeScript, and I installed tide for editing the files in emacs.  When trying to use tide-jump-to-implementation, I got the error message "No implementations available".  So I searched and came accross this issue, and indeed, tide-verify-setup answers 

`tsserver version: 3.9.7

config file path: /dev/null/inferredProject1*`

which probably (correct me if I'm wrong) explains my original problem above.  tss.log up to the point where the /dev/null/inferredProject1 shows up the first time (and anonymized a bit) contains
[tss.log](https://github.com/ananthakumaran/tide/files/5161901/tss.log)

This file contains a subset of the output of tree at the shell, showing the project structure.
[tree.txt](https://github.com/ananthakumaran/tide/files/5161956/tree.txt)

As you can see, tsconfig.json is located in src/main/webapp, and that location is one showing up in tss.log:
`Info 11   [13:54:8.920] ConfigFilePresence:: Current Watches: :: File: /home/xxx/workspace/foo.web/src/main/webapp/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: /home/xxx/workspace/foo.web/src/main/webapp/foo-web/admin/AdminPage.ts Status: File added to open files impacted by this config file`

Do I make some obvious mistake (easily possible, as I'm new to TypeScript and tide (I personally wasn't the one having set up the project), or is this another instance of the problems described in this and related bugs?

If you need more information, I can try to debug things further, just tell me what I need to do.

My emacs version is 27.0.50.

**Comment by ananthakumaran** [comment]
Check if you are able to compile the project correctly from the command line using tsc. `/dev/null/inferredProject` normally means the file is not considered part of the project by tsserver. Check if tsconfig.json is correct (specially `include` field.)

**Comment by wol81** [comment]
Thank you, indeed the tsconfig.json was the problem.

At that time, the "include" field was missing completely.

Maybe adding a hint like you wrote in https://github.com/ananthakumaran/tide/issues/305#issuecomment-685737212 to the output of tide-verify-setup would be a good idea?  /dev/null/inferredProject1 only tells one that something is wrong, but not what the first places to look at are...

**Comment by ananthakumaran** [comment]
refer #242
