### ISSUE TITLE
README's configuration instructions are not beginner-friendly

### ISSUE THREAD

**Issue by Valbrand** [ananthakumaran/tide#306]
Hello.

I've been trying to configure tide for `.tsx` and `.ts` files, to no avail. When trying to follow `README`'s instructions, there's no hint as to where should I put the code snippet available there. I tried putting the `defun setup-tide-mode` just above `dotspacemacs/user-config` and the rest of the code inside `dotspacemacs/user-config`, but I keep getting errors like `(Spacemacs) Error in dotspacemacs/user-config: Cannot open load file: No such file or directory, web-mode`, even though I did install `web-mode` (btw, if this is needed, the instructions are missing as well). Am I missing something? I can open a PR for the README as soon as I get this solved.

Thanks in advance 😄

**Comment by josteink** [comment]
I'd love to help, but I *literally* know nothing about how to do anything in spacemacs. 

Hopefully someone else can clear things up.

**Comment by Valbrand** [comment]
Hey Jostein,

Thanks for the attention. What would I have to do if I were using a plain emacs installation? I wouldn’t be able to figure it out on my own either (as you can see I’m a emacs rookie 😥)

Daniel Oliveira

BSc in Computer Science – CIn-UFPE
Software Engineer – Nubank

**Comment by josteink** [comment]
> there's no hint as to where should I put the code snippet available there. 

> hat would I have to do if I were using a plain emacs installation? 

What you're looking for is typically known as your `.emacs`-file or `init.el`.

Look for documentation on those, and you should be on a whole new path in your Emacs-career :smiley:

**Comment by Valbrand** [comment]
Thank you. I eventually figured out I just had to deal with `.spacemacs` but I was doing it incorrectly. Closing this...
