### ISSUE TITLE
Display types via autocompletion window

### ISSUE THREAD

**Issue by mk0x9** [ananthakumaran/tide#307]
![Screenshot 2019-03-14 at 16 22 39](https://user-images.githubusercontent.com/387358/54369094-9f586880-4675-11e9-8870-491f6561c8cc.png)
Is it possible anyway to show complete types instead of symbol type? Or add type to the completion?

**Comment by ananthakumaran** [comment]
could you set [tide-completion-detailed](https://github.com/ananthakumaran/tide#tide-completion-detailed-nil) to `t`? This would display detailed information in the completion list. Note that, it might be slower than the default as extra calls would be necessary to fetch the information

**Comment by mk0x9** [comment]
@ananthakumaran wow, that's great actually. Would be nice to have sample screenshot in README.

Also it is a little bit too verbose IMO, but I'll try to hack something configurable in the next weeks probably.
