### ISSUE TITLE
TypeScript 3.4 incremental support

### ISSUE THREAD

**Issue by bbigras** [ananthakumaran/tide#309]
TypeScript 3.4 was recently released with incremental compiling.

Will this benefit tide?

Do we only need to set those options to get it when the bundled tsserver is updated?

```json
// tsconfig.json
{
    "compilerOptions": { 
        "incremental": true,
        "outDir": "./lib"
    },
    "include": ["./src"]
}
```
https://devblogs.microsoft.com/typescript/announcing-typescript-3-4/#faster-subsequent-builds-with-the---incremental-flag

**Comment by ananthakumaran** [comment]
You can have a look at the [debugging](https://github.com/ananthakumaran/tide#debugging) section which outlines the architecture of tide. In essence, tsserver already works like that.

**Comment by bbigras** [comment]
Thanks
