### ISSUE TITLE
Indentation of isolated brace after function declaration

### ISSUE THREAD

**Issue by JohnL4** [ananthakumaran/tide#31]
Howdy. Trying to get started w/both TypeScript and tide.

I'm one of those braces-on-lines-by-themselves people, and when I define a function and put the brace on the next line, it gets indented, and then the next line gets indented even more:

```typescript
   identity<T>( anArray: Array<T>): Array<T> 
      {
         console.log( `Length of array is: ${anArray.length}`);
         return anArray;
      }
```

I don't see anything obvious in the customize settings, and I tried running c-set-style and got the message "Not a CC Mode buffer" or some such.

I could dust off my elisp debugging skills and drill into this, but I don't really have time, so... is there something simple I've missed?

My only config is this:

```lisp
(add-hook 'typescript-mode-hook
          (lambda ()
            (tide-setup)
            (flycheck-mode +1)
            (eldoc-mode +1)
            (company-mode-on)
            (setq typescript-indent-level 3)
            ))
```

GNU Emacs 24.3.1 (x86_64-apple-darwin, NS apple-appkit-1038.36) of 2013-03-13 on bob.porkrind.org

Thanks.

**Comment by ananthakumaran** [comment]
Have you tried `tide-format`. Go through the readme and checkout `tide-format-before-save` and  `tide-format-options` and see if it solves your problem.

**Comment by JohnL4** [comment]
Yes, looks like that was the trick, thanks.

```lisp
(add-hook 'typescript-mode-hook
          (lambda ()
            (tide-setup)
            (flycheck-mode +1)
            (eldoc-mode +1)
            (company-mode-on)
            ))

;; Note that the following don't work for me when set inside the mode hook.  Don't know why.
(setq typescript-indent-level 3)
(setq tide-format-options '(:placeOpenBraceOnNewLineForFunctions t :placeOpenBraceOnNewLineForControlBlocks t))
```
