### ISSUE TITLE
tide-hl-identifier bug

### ISSUE THREAD

**Issue by zedhugh** [ananthakumaran/tide#326]
after I upgrade tide.
when the cursor at a symbol which should highlight, emacs will **stuck for a moment**,
and show `error in process filter: Symbol's value as variable is void: for`.

so, I try recover the change of commit `97e779472b739ab31bd935f95debd80ec16262c9`,
this bug fix. please check and fix it.

**Comment by lddubeau** [comment]
Please provide the information requested in the [issue template](https://github.com/ananthakumaran/tide/blob/master/ISSUE_TEMPLATE.md).

**Comment by zedhugh** [comment]
## Relevant Version Numbers
- Tide: 20190704.2041
- TypeScript: not installed
- node: 11.14.0
- Emacs: 26.2 27.0.50 

## Steps to Reproduce the Bug
`const str = "|";`
you can reproduce when type slowly in string like above code.

**Comment by lddubeau** [comment]
Thank you for the information. 

I have a commit on [this branch](https://github.com/ananthakumaran/tide/tree/fix-cl-issue), which I think should fix the problem. Can you please try the code on that branch and let me know whether it takes care of the issue?

**Comment by zedhugh** [comment]
excellent, this bug fixed in [your branch](https://github.com/ananthakumaran/tide/tree/fix-cl-issue)

**Comment by lddubeau** [comment]
Thank you for testing the fix. It has been pushed to the master branch, which will trigger MELPA's build and should shortly result in a new version available on MELPA, with the fix.
