### ISSUE TITLE
Disable popup?

### ISSUE THREAD

**Issue by ianpan870102** [ananthakumaran/tide#327]
From time to time I experience this **crazy** big popup no matter where I put my cursor in the buffer (as long as it's a word). I wonder how I may disable this, or is this a **server-side** problem?

<img width="1920" alt="Screenshot 2019-07-12 at 2 16 21 PM" src="https://user-images.githubusercontent.com/36686900/61106550-1846c000-a4b0-11e9-805f-ae334ef25bfa.png">

**Comment by ianpan870102** [comment]
I found a way to reproduce: in a tide-enabled buffer (e.g. a JS file), `M-x tide-mode` to disable tide, then `M-x tide-mode` to reenable tide. The popup will show up wherever you move the cursor, as if tide did not correctly reenable?

**Comment by ananthakumaran** [comment]
the [debugging section](https://github.com/ananthakumaran/tide#debugging) gives a high-level overview of how things work. The pop is basically the error message from tsserver, you could enable the log and see which command fails.

**Comment by ianpan870102** [comment]
**Workaround**: When I do `tide-restart-server`, the error message goes away and display the normal Eldoc that tsserver was supposed to. Does this mean one couldn't just reenable tide-mode, but also have to manually restart the tsserver?
