### ISSUE TITLE
flycheck not working with typescript@next

### ISSUE THREAD

**Issue by deontologician** [ananthakumaran/tide#33]
Not sure what's broken, I'm not getting a lot of error messages. I would assume the error output has changed in some way

**Comment by ananthakumaran** [comment]
How did you change the tsserver code to typescript@next? Tide comes with its own [tsserver](https://github.com/ananthakumaran/tide/tree/master/tsserver) and it can't be  switched to other versions as of now.

**Comment by deontologician** [comment]
I just installed typescript@next and suddenly I stopped getting any error highlighting. The tslint part still worked though. Does tsserver look for `tsc` on the PATH or does it have the typescript compiler as part of itself?

**Comment by ananthakumaran** [comment]
It is self-contained and doesn't depend on tsc.

**Comment by deontologician** [comment]
Maybe it's an invalid tsconfig.json option that's causing tsserver to bail out. How hard would it be to just swap out the tsserver for the one from typescript@next ? Are there a lot of things that would need to be modified, or could I just swap that one file?

**Comment by ananthakumaran** [comment]
I am waiting for 2.0 which should provide a simpler error api, #22 contains the details. You could also try to compile the tsserver yourself. Look at the Makefile for how it is being done right now.

**Comment by webus** [comment]
+1

**Comment by ananthakumaran** [comment]
It will be supported once TypeScript 2.0 is released. If you want now, you can try typescript-2.0 branch in tide. see #38

**Comment by webus** [comment]
Thanks!
