### ISSUE TITLE
tide-format-before-save slow, Sync request timed out format

### ISSUE THREAD

**Issue by mstorus** [ananthakumaran/tide#333]
Summary: tide-format-before-save is very slow in my repo, and times out when saving twice in a short period of time.

## Relevant Version Numbers

- Tide: 3.6.2
- TypeScript: 3.6.2
- Emacs: 26.2

## Steps to Reproduce the Bug

- Open a .ts source file in my repo
- enter a newline
- save the file
- enter another newline
- save the file

## Expected Behavior

I expected the 2nd save to complete quickly.

## Actual Behavior

After saving the 2nd time, emacs hangs on "Saving file ..." for about 7 seconds, and then reports the error
```
Debugger entered--Lisp error: (error "Sync request timed out format")
  signal(error ("Sync request timed out format"))
  error("Sync request timed out %s" "format")
  tide-send-command-sync("format" (:file "/Users/me/src/repo/filename.ts" :line 1 :offset 1 :endLine 21 :endOffset 1))
  tide-format-region(1 528)
  tide-format()
  tide-format-before-save()
  run-hooks(before-save-hook)
  basic-save-buffer(t)
  save-buffer(1)
  funcall-interactively(save-buffer 1)
  call-interactively(save-buffer nil nil)
  command-execute(save-buffer)
```

## More Details
It seems like the slowness only happens on every 2nd save. After the 2nd save times out, I'm able to save again (3rd try) and it completes quickly. Then if I attempt a 4th save, it times out again, and so on.

Note that invoking `tide-format` on a region behaves as expected (it completes quickly).

If I remove `(add-hook 'before-save-hook 'tide-format-before-save)` from my `.emacs` file, then I no longer experience any slowness upon save.

If I set `(setq tide-tsserver-process-environment '("TSS_LOG=-level verbose -file /tmp/tss.log"))`, then I get the following output in `/tmp/tss.log` after the 2nd save:

```
Info 1250 [19:2:9.95] Finishing updateGraphWorker: Project: /Users/me/src/repo/tsconfig.json Version: 15 structureChanged: true Elapsed: 7602ms                                                      
Info 1251 [19:2:9.95] Project '/Users/me/src/repo/tsconfig.json' (Configured)                                                                                                                        
Info 1252 [19:2:9.95]   Files (1644)  


... (list of files) ....


Info 1253 [19:2:9.95] -----------------------------------------------                                                                                                                                              
Info 1254 [19:2:9.97] Running: *ensureProjectForOpenFiles*                                                                                                                                                         
Info 1255 [19:2:9.97] Structure before ensureProjectForOpenFiles:                                                                                                                                                  
Info 1256 [19:2:9.97] Project '/Users/me/src/repo/tsconfig.json' (Configured) 0                                                                                                                      
Info 1256 [19:2:9.97]   Files (1644)  


... (list of files) ...


Info 1256 [19:2:9.98] -----------------------------------------------                                                                                                                                              
Info 1256 [19:2:9.98] Open files:                                                                                                                                                                                  
Info 1256 [19:2:9.98]   FileName: /Users/me/src/repo/filename.ts ProjectRootPath: undefined                                                    
Info 1256 [19:2:9.98]       Projects: /Users/me/src/repo/tsconfig.json                                                                                                                               
Info 1256 [19:2:9.98] Structure after ensureProjectForOpenFiles:                                                                                                                                                   
Info 1257 [19:2:9.98] Project '/Users/me/src/repo/tsconfig.json' (Configured) 0                                                                                                                      
Info 1257 [19:2:9.98]   Files (1644) 


... (list of files) ...


Info 1257 [19:2:9.98] Open files:                                                                                                                                                                                  
Info 1257 [19:2:9.98]   FileName: /Users/me/src/repo/filename.ts ProjectRootPath: undefined                                                    
Info 1257 [19:2:9.98]       Projects: /Users/me/src/repo/tsconfig.json                                                                                                                               
Info 1257 [19:2:9.98] got projects updated in background, updating diagnostics for /Users/me/src/repo/filename.ts                              
Info 1258 [19:2:9.98] event: 

```

the `(list of files)` includes .ts, .js, and .jsx source files, as well as .d.ts files from node_modules.

**Comment by ananthakumaran** [comment]
tsserver watches file changes and rebuild the project if necessary. could you check which file triggers the slow operation? There are two things I want to rule out before starting to look into details

1) make sure it's not because of interlocking files https://github.com/ananthakumaran/tide/issues/320.  You can verify by disabling lock files `(setq create-lockfiles nil)`
2) it's not because of temp flycheck files. Look for file of the format name_flycheck.ts. You could disable other flycheck checkers like eslint, tslint etc (use flycheck-verify-setup and flycheck-disable-checker) to confirm the issue

**Comment by mstorus** [comment]
hi @ananthakumaran,
- `(setq create-lockfiles nil)` had no effect on save speed
- I have the following checkers reported by `flycheck-verify-setup`
tsx-tide
javascript-eslint
typescript-tslint
jsx-tide

after `flycheck-disable-checker typescript-tslint`, I am able to save quickly again!

On a related note, I have an rsync running in the background to sync my files to a remote server, and it occasionally quits and reports that `flycheck_index.tsx` has vanished before it could be synced

**Comment by ananthakumaran** [comment]
I am afraid there is nothing tide can do about this. This could be fixed either by not creating temp file https://github.com/flycheck/flycheck/blob/master/flycheck.el#L11030 or tsserver should ignore flycheck's temp files https://github.com/microsoft/TypeScript/issues/31916#issuecomment-502773780.
