### ISSUE TITLE
‘font-lock-function-name-face’ is being applied to methods and function calls?

### ISSUE THREAD

**Issue by ahungry** [ananthakumaran/tide#336]
Is this a recent update to something in tide mode, or another package has inadvertently ruined the syntax highlighting/face application?

Previously a function definition would highlight the function's name with the 'font-lock-function-name-face' as is conventional in all languages:

```
function foo () {
}

class Bar {
  public baz () { }
}
```
In that sample, `foo` would receive the face, as well as `baz`.

However, within the last week or 2, I have had an issue where calling these functions result in the face being applied as well, so that when I call:

```
const b = new Bar()
b.baz()
```
baz would have the face applied (whereas previously it would be `default` face, as it should be).

Was this a known / intentional change?

**Comment by josteink** [comment]
This is a deliberate change. 

We’ve introduced a new font-lock-keywords level (4). 

If you prefer the old behaviour you can just set your Emacs to use level 3 instead.

**Comment by ahungry** [comment]
Thank you @josteink  - that solved my issue by setting:

```
(setq font-lock-maximum-decoration '((typescript-mode . 3)))
```

https://www.gnu.org/software/emacs/manual/html_node/elisp/Levels-of-Font-Lock.html

Could I recommend that it may be useful for there to be a distinction between function definition face and function call/invocation face?  tide hl extends the base highlight face.  If this new face was under tide-font-lock-function-name-face, it would make it very convenient to customize it to a slightly more unique face (as a theme maintainer, it would help a lot).

What do you think?

**Comment by josteink** [comment]
There is an Emacs-devel discussion I started about that topic a few weeks ago. 

Feel free to chime in: https://lists.gnu.org/archive/html/emacs-devel/2019-09/msg00211.html

**Comment by ahungry** [comment]
Very nice, I'll try to chime in tonight.  Couldn't your proposed font-lock-function-call-face just inherit (https://www.gnu.org/software/emacs/manual/html_node/elisp/Face-Attributes.html) from font-lock-function-name-face and avoid the only real problem identified?  (that some modes may not have customizations for a new face type)?

**Comment by josteink** [comment]
> avoid the only real problem identified? (that some modes may not have customizations for a new face type)?

I'm not sure I understand. That sounds a bit backwards to me.

Creating a new face will not automatically make it so that all major-modes employ it, or have the necessary code to identify the section which should be fontified using the new face.

Modes not written to use the new font-lock faces will obviously keep using the old ones.

And customization should anyhow be done by the user, not the major-mode.

**Comment by josteink** [comment]
Either way this is only related typescript-mode. If you want to further the discussion please do it there or in emacs-devel.

Closing as not relevant to tide.
