### ISSUE TITLE
tide-hl-identifier-mode does not highlight correct area on line when tab indenting is used

### ISSUE THREAD

**Issue by zanemayo** [ananthakumaran/tide#337]
## Checklist

- [x] I have searched both open and closed issues and cannot find a duplicate.
- [x] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [x] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [x] I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.
- [] If [tide *is reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should not be reported*, I can run `tsc` (and `tslint`, if applicable) without the error or warning I'm seeing in tide.
- [] If [tide is *not reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should be reported*, `tsc` (or `tslint`, if applicable) reports the error or warning I was expecting to see.
- [x] I am [positive](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

## Relevant Version Numbers

- Tide: 20190829.1315
- TypeScript: 20190918.1042
- Emacs: 26.3

## Steps to Reproduce the Bug

Use  tide with: (tide-hl-identifier-mode +1)

Open a typescript file with tab indenting.

## Expected Behavior

Identifiers are highlighted correctly.

## Actual Behavior
The incorrect area is highlighted on lines that include the tab character. It gets worse the more tabs there are (see screenshot).

The bug seems to have been introduced here (https://github.com/ananthakumaran/tide/commit/97e779472b739ab31bd935f95debd80ec16262c9?diff=unified)

If I undo that change in my local tide.el the highlighting works correctly.

It seems to be related by move-to-column which doesn't seem to take tabs into account.

In the following screenshot my cursor is on the 'r' of 'myvar'. The highlighting is working correctly on the first line, but not the other lines that are indented.

![Screenshot 2019-10-03 at 16 33 24](https://user-images.githubusercontent.com/273095/66141485-adfb7280-e5fb-11e9-9382-723ae4747bdd.png)

**Comment by josteink** [comment]
Thanks for the report, a simple reproducible example and proper bisecting!

That’s way above average for a bug-report 😀

@lddubeau: since this change supposedly was introduced by some optimisations you did, would you be willing to look into this issue? You already seem to know the code fairly well :)

**Comment by lddubeau** [comment]
The PR is in: #338

**Comment by josteink** [comment]
Well that was fast 😮 

Great job!

**Comment by zanemayo** [comment]
Thank you @lddubeau! I've tried your PR on my project and it works perfectly!

**Comment by lddubeau** [comment]
I was able to put this together speedily in great part because the issue report answered the questions we need answered in a report. Thank you for using the template, @zanemayo
