### ISSUE TITLE
[Question] Disable auto import on completion?

### ISSUE THREAD

**Issue by qhuyduong** [ananthakumaran/tide#339]
Thanks for your great work!

I have a question: is there any way to disable auto import on completion? I already used `import-js` to import things on buffer save so I don't want to turn off this feature from tide.

**Comment by ananthakumaran** [comment]
could you try to remove `includeCompletionsWithInsertText` from [tide-user-preferences](https://github.com/ananthakumaran/tide/blob/b8ce1d8c224cf72ccc3491787a1222be63603127/tide.el#L110). This will disable auto import, but I am afraid might potentially break other things around auto-complete.
