### ISSUE TITLE
Error on tide-setup

### ISSUE THREAD

**Issue by shanavas786** [ananthakumaran/tide#34]
Throws
```
 File mode specification error: (error "typescript-tslint is not a valid Flycheck syntax checker") 
```
while opening file
I have the following hook
```
(add-hook 'typescript-mode-hook
          '(lambda ()
             (tide-setup)
             (eldoc-mode +1)
             ))
```
and have global-flycheck-mode enabled

**Comment by ananthakumaran** [comment]
can you check your flycheck version?

**Comment by shanavas786** [comment]
Sorry was outdated. Issue solved after update. Thanks.

**Comment by ananthakumaran** [comment]
how did you install tide? I thought `package-install` would take care of this issue.

**Comment by shanavas786** [comment]
flycheck was installed long before. I think new package installation doesn't update installed dependencies.

**Comment by ananthakumaran** [comment]
hm, then it might break for other people also
