### ISSUE TITLE
Difference between tide-format, tide-fix and tide-refactor

### ISSUE THREAD

**Issue by Eeemil** [ananthakumaran/tide#343]
Hello!

There are three `tide`-commands that seem to perform similar actions, `tide-format`, `tide-fix` and `tide-refactor`. I'm confused by what the commands are supposed to do.

I expect at least one of the commands to automatically fix the tslint warning "This arrow function body can be simplified by omitting the curly braces and the keyword 'return'. [arrow-return-shorthand]", but none of the commands seems to do that.

What is the actual difference between the commands? I think this should be more clearly specified in the readme, perhaps with code examples to demonstrate the functionality.

## Checklist

- [x] I have searched both open and closed issues and cannot find a duplicate.
- [x] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [x] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [x] I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.
- [x] If [tide *is reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should not be reported*, I can run `tsc` (and `tslint`, if applicable) without the error or warning I'm seeing in tide.
- [x] If [tide is *not reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should be reported*, `tsc` (or `tslint`, if applicable) reports the error or warning I was expecting to see.
- [x] I am [positive](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

## Relevant Version Numbers

- Tide: master
- TypeScript: *
- Emacs: *

(The list above is minimal. Make sure to include any other version numbers relevant to your report.)

## Steps to Reproduce the Bug

Read the readme

## Expected Behavior

To understand everything

## Actual Behavior

Get confused by the difference between `tide-refactor`, `tide-format` and `tide-fix`

**Comment by ananthakumaran** [comment]
tide-format - will format the current buffer or selected region
tide-fix - will fix the current error. The cursor should be on top of error reported by `tide`
tide-refactor - when you trigger this command, you will be presented with a list of available refactor options. This is also context-specific and you have to be at the right position / have to select the right region.

tslint warning is usually not fixable by default unless you use something like https://github.com/microsoft/typescript-tslint-plugin

**Comment by ananthakumaran** [comment]
closing this, feel free to re-open if you find any issue or open a PR if you want to update the README
