### ISSUE TITLE
Capitalize tabSize/indentSize

### ISSUE THREAD

**Issue by Jumblemuddle** [ananthakumaran/tide#354]
Should the parameters in `tide-file-format-options` be capitalized?
https://github.com/ananthakumaran/tide/blob/master/tide.el#L787
It seems to work (`tide-command:configure` uses 2 spaces) if I capitalize them to `(:TabSize ,tab-width :IndentSize ,(tide-current-indentsize))`. Perhaps something changed with the TypeScript server?

- Tide: `v3.2.3`
- TypeScript: `v0.3`
- Emacs: `26.3`

**Comment by Jumblemuddle** [comment]
I created a PR. I'm still not sure this is the right fix though.

Can someone explain the difference between `TabSize` and `IndentSize`?

**Comment by ananthakumaran** [comment]
strange, the spec https://github.com/microsoft/TypeScript/blob/master/src/server/protocol.ts#L2968 still uses camelCase format. Could you share the output of `M-x tide-verify-setup`

**Comment by Jumblemuddle** [comment]
This is all that gave me:
```
tsserver version: 3.7.3

config file path: <tsconfig.json>
```
<tsconfig.json>:
```
{
  "compilerOptions": {
    "strict": true,
    "esModuleInterop": true,
    "jsx": "react",
  }
}
```

**Comment by Jumblemuddle** [comment]
I'm not sure the difference between `EditorOptions` and `EditorSettings` here: https://github.com/microsoft/TypeScript/blob/4212484ae18163df867f53dab19a8cc0c6000793/src/services/types.ts#L720

**Comment by Jumblemuddle** [comment]
Strangely resetting to the lowercase settings seems to work now. Tide is formatting with the correct spacing now. :man_shrugging:

I'm going to close this for now. I'll reopen it if I run into the same issue again.
