### ISSUE TITLE
the code completion popup doesn't appear if there is a very large number of candidates

### ISSUE THREAD

**Issue by emmanueltouzery** [ananthakumaran/tide#357]
When submitting issues to this project, please include the following information.

## Checklist

- [x] I have searched both open and closed issues and cannot find a duplicate.
- [x] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [x] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [x] I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.
- [x] I am [positive](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

## Relevant Version Numbers

- Tide: 20200103.1159
- TypeScript: 3.5.3
- Emacs: 26.3
- Company: 20200102.2354

## Steps to Reproduce the Bug

In our typescript source code at work, we have some generated code. In that case, the completion popup can end up displaying several thousand entries. VS code has no issue with that. The completion in tide works fine for all that I tried except one specific, pretty pathological case. In that case the completion popup doesn't appear at all. There is also no warning that I can see.

I have enabled debug logs and with that, it's clear that tide does get a list of completions, and it even quite fast:

```
Info 750  [15:3:51.431] getCompletionsAtPosition: getCompletionEntriesFromSymbols: 4
Perf 751  [15:3:51.440] 128::completions: elapsed time (in milliseconds) 17.0064
Info 752  [15:3:51.442] response:
    {"seq":0,"type":"response","command":"completions","request_seq":"128","success":true,"body":[{"name":"_TO_","kind":"property","kindModifiers":"public","sortText":"0"},{"name":"ABSENCE","kind":"property","kindModifiers":"public","sortText":"0"},{"name":"ABSENCE_S_","kind":"property","kindModifiers":"public","sortText":"0"},{"name":"ABSENCE_TITLE","kind":"property","kindModifiers":"public","sortText":"0"},{"name":"ABSENCE_TYPE","kind":"property","kindModifiers":"public","sortText":"0"},{"name":"ABSENCES","kind":"property","kindModifiers":"public","sortText":"0"},{"name":"ABSOLUTE_FARE","kind":"property","kindModifiers":"public","sortText":"0"},{"name":"ACCOUNT","kind":"property","kindModifiers":"public","sortText":"0"},{"name":"ACCOUNT_DETAILS","kind":"property","kindModifiers":"public","sortText":"0"},{"name":"ACCOUNT_HOLDER","kind":"property","kindModifiers":"public","sortText":"0"},{"name":"ACCOUNT_S_","kind":"property","kindModifiers":"public","sortText":"0"},{"name":"ACCOUNT_SHORT_ID","kind":"property","kindModifiers":"public","sortText":"0"},{"name":"ACCOUNT_STATUS","kind":"property","kindModifiers":"public","sortText":"0"},{"name":"ACCOUNT_TYPE","kind":"property","kindModifiers":"public","sortText":"0"},{"name":"ACCOUNT_UID","kind":"property","kindModifiers":"public","sortText":"0"},{"name":"ACT","kind":"property","kindModifiers":"public","sortText":"0"},{"name":"ACTION","kind":"property","kindModifiers":"public","sortText":"0"},{"name":"ACTIONS","ki
...
rty","kindModifiers":"public","sortText":"0"},{"name":"ZONE_FROM_TO_MATRIX","kind":"property","kindModifiers":"public","sortText":"0"},{"name":"ZONE_NAME","kind":"property","kindModifiers":"public","sortText":"0"},{"name":"ZONE_S_","kind":"property","kindModifiers":"public","sortText":"0"},{"name":"ZONE_S_TRAVELED","kind":"property","kindModifiers":"public","sortText":"0"},{"name":"ZONE_TYPE","kind":"property","kindModifiers":"public","sortText":"0"},{"name":"ZONE_TYPE_S_","kind":"property","kindModifiers":"public","sortText":"0"},{"name":"ZONE_TYPES","kind":"property","kindModifiers":"public","sortText":"0"},{"name":"ZONES","kind":"property","kindModifiers":"public","sortText":"0"}]}
```

The log contains no further information. Now I don't know whether it's a company 'feature' of not showing the popup if there are too many entries, or if tide has some upper limit.. What setting can I change so that popup will appear?

**Comment by ananthakumaran** [comment]
Could you check if increasing [tide-server-max-response-length](https://github.com/ananthakumaran/tide#tide-server-max-response-length-102400) solves the issue? A large response from tsserver could freeze the emacs UI and this check was added sometime back to solve the issue.

**Comment by emmanueltouzery** [comment]
hmm i actually tried that before, but on a relatively low value. Didn't realize the default is such a huge number.

I now tried:

        (setq  tide-server-max-response-length 999999999)

and that DID help. What is that unit so that the default is 102400 and that it times out on a request taking 17 milliseconds (according to my logs)?

So anyway it seems this bug can be closed then :-) just waiting for your answer on the unit maybe

**Comment by emmanueltouzery** [comment]
ah yes these are bytes! I thought they were milliseconds :-) ok then that's it... I just misunderstood the docs. Thank you!
