### ISSUE TITLE
ElDoc in echo area is sometimes too small for type signatures

### ISSUE THREAD

**Issue by ironchicken** [ananthakumaran/tide#358]
Apologies for raising this as an issue if it turns out not to be something that requires a code fix. I can't find any other way to contact Tide developers, though.

When I hover over a symbol in a `tide-mode` buffer I get the type signature for that symbol in the echo area supplied by ElDoc. But sometimes the type signature is truncated, i.e. I can see the bottom 20 or so lines of it and the top lines are not visible because the echo area is too small to display the whole thing. I currently have `eldoc-echo-area-use-multiline-p` set to "Yes, but truncate symbol names...". I've also customised `max-mini-window-height` to `0.4` which improves the situation a little but there are still sometimes type signatures that I can't read in full.

I'd like to be able to have a way of viewing the whole type signature, and also a way of persisting that type signature view so that I can refer to it while writing code.

One possibility could be that `tide-mode` might have a function that puts the type signature of the symbol under the point into a new buffer and that function can be bound to a key. If this already exists I couldn't find it.

**Comment by ananthakumaran** [comment]
Could you set [tide-always-show-documentation](https://github.com/ananthakumaran/tide#tide-always-show-documentation-nil) to `t` and run `M-x tide-documentation-at-point`.

This is probably not a well-documented feature. Feel free to update the readme and raise a PR.

**Comment by ironchicken** [comment]
Ah yes, that works pretty nicely.
