### ISSUE TITLE
use-package config

### ISSUE THREAD

**Issue by MateuszLeo** [ananthakumaran/tide#360]
Hey! I ran into issue while configuring tide, I wasn't able to make it work with `use-package`.  I was following instruction which is included in `README.md`. Finally after reading documentation of `use-package` I was able to make it work, here is my config:

```
(use-package tide)

(use-package typescript-mode
  :hook ((typescript-mode . tide-setup)
         (typescript-mode . tide-hl-identifier-mode)
         (typescript-mode . company-mode)
         (typescript-mode . flycheck-mode)))

(use-package web-mode
  :mode ("\\.tsx" . web-mode)
  :hook ((web-mode . typescript-mode)))
```

Anyone have idea any why setup code from `README.md` isn't working?

**Comment by josteink** [comment]
I don't think any of the regular tide-maintainers use `use-package`.

If the documentation is wrong, feel free to send a PR fixing it.

**Comment by lddubeau** [comment]
> I don't think any of the regular tide-maintainers use `use-package`.

I was unavailable for a while, but I'm still here and I use `use-package`. :smiley_cat: First I'll note that my own `use-package` configuration is different from the one in the `README.md`. There's more than one way to get to the desired result. Mine works. Other folks can end up with a different configuration that gets them there. It's all good. I'd say though it is not realistic to come up with something succinct in the README that will always work for everyone in all circumstances.

Now, I'd like the `README.md` to not become a battleground for "the One True `use-package` Configuration (tm, r, patent pending)". If the documentation should be changed, then the request for a change should come with a substantial explanation of what is currently wrong with the documentation and how the change fixes it. And the change should have an eye towards general applicability. 

I've glanced at the OP's configuration and compared it with what's in the README, and did not come up with a reason why the OP's configuration should work but the README does not. Or more accurately: I repeatedly came up with hypotheses that I then disproved immediately.

So right now I don't see any reason to change the documentation.

**Comment by josteink** [comment]
Ooops. Sorry. Didn't know. Didn't mean to imply you had left us @lddubeau  :smiley:

**Comment by lddubeau** [comment]
It does not seem there's anything that needs changing for now. If there is something that needs to be done with tide's documentation, please post a comment that meets this request (quoting from [this comment](https://github.com/ananthakumaran/tide/issues/360#issuecomment-576230073)):

> If the documentation should be changed, then the request for a change should come with a substantial explanation of what is currently wrong with the documentation and how the change fixes it. And the change should have an eye towards general applicability.
