### ISSUE TITLE
Error while checking syntax automatically: (void-function record)

### ISSUE THREAD

**Issue by ikr** [ananthakumaran/tide#367]
The errors/warnings highlighting stopped working after a recent update.

In the tss.log I do see the errors reported:

```js
{
  command: 'documentHighlights',
  seq: '153',
  arguments: {
    file: '…/Form.tsx',
    line: 100,
    offset: 22,
    filesToSearch: [
      '/home/ikr/prj/parkingcard-app/npm/browser/admin-app/src/common/form/Form.tsx'
    ]
  }
}
```

Then, in the Emacs *Messages* I see:

```
Saving file …/Form.tsx...
Wrote /tmp/prettier28506uko.tsx
Applied prettier with args ‘nil’
Wrote …/Form.tsx
Error while checking syntax automatically: (void-function record)
Mark set
```

## Checklist

- [x] I have searched both open and closed issues and cannot find a duplicate.
- [x] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [x] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [x] I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.
- [x] If [tide *is reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should not be reported*, I can run `tsc` (and `tslint`, if applicable) without the error or warning I'm seeing in tide.
- [x] If [tide is *not reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should be reported*, `tsc` (or `tslint`, if applicable) reports the error or warning I was expecting to see.
- [x] I am [positive](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

## Relevant Version Numbers

- Tide: 20200308.259
- TypeScript: 3.7.2
- Emacs: 25.2.2

(The list above is minimal. Make sure to include any other version numbers relevant to your report.)

## Steps to Reproduce the Bug

Change a prop name to something undeclared.

## Expected Behavior

The misspelled property highlighted.

## Actual Behavior

No highlight. The `Error while checking syntax automatically: (void-function record)` appears in mini-buffer.

**Comment by ananthakumaran** [comment]
could you share the full stack trace. Run `M-x toggle-debug-on-error` to enable the debug mode

**Comment by ikr** [comment]
Sure. It's

```
Debugger entered--Lisp error: (void-function record)
  signal(void-function (record))
  flycheck-buffer()
  flycheck-buffer-automatically(save)
  flycheck-handle-save()
  run-hooks(after-save-hook)
  basic-save-buffer(t)
  save-buffer(1)
  funcall-interactively(save-buffer 1)
  call-interactively(save-buffer nil nil)
  command-execute(save-buffer)
```

**Comment by ananthakumaran** [comment]
Could you make sure you are using the latest version of flycheck and its dependencies etc. I don't see tide functions in the stack trace anywhere. Probably you can jump to the source of flycheck-buffer function and that might give some hint.

**Comment by lddubeau** [comment]
It is not looking good as a potential bug *in `tide` itself*. That error is a complaint that the symbol `record` has no value when used as a function. `tide` itself does not refer to the `record` symbol. I also grepped `flycheck` for good measure and did not find `record` there either.

If I got that error, I'd check whether any of the checkers that are active in my buffer make a reference to the symbol `record`. I'd also check `flycheck-before-syntax-check-hook` to see if it or anything it calls refers to `record`.

Given that `moo` is not defined on my system, I can reproduce the error message with:

```
(condition-case err
    (moo)
  (error
   (signal (car err) (cdr err))))
```

This reproduces the relevant parts of `flycheck-buffer`. Yes, it does convert the error like shown above.

Note however, that `record` is defined in my Emacs. **It is a built-in function.** Emacs 25 should not be a problem. @ikr  Perhaps there is something that overwrites or shadows `record` in your installation?

**Comment by lddubeau** [comment]
@ikr  Actually, I've just checked the NEWS file with my 26.1 installation and I read there that `record` was added in 26.1. Seems to me there must be code somewhere that assumes it is running in a 26.1 installation though your Emacs is 25.

**Comment by ikr** [comment]
@lddubeau Thank you very much! Indeed, it works in v26 for me.
