### ISSUE TITLE
feature request: make tide-format-before-save execution configurable

### ISSUE THREAD

**Issue by RohanHart** [ananthakumaran/tide#372]
## Checklist

- [x] I have searched both open and closed issues and cannot find a duplicate.
- [x] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [x] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [x] I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.
- [ ] If [tide *is reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should not be reported*, I can run `tsc` (and `tslint`, if applicable) without the error or warning I'm seeing in tide.
- [ ] If [tide is *not reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should be reported*, `tsc` (or `tslint`, if applicable) reports the error or warning I was expecting to see.
- [x] I am [positive](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

## Relevant Version Numbers

- Tide: 20200327.1218
- TypeScript: 3.7.5
- Emacs: 26.3

## Description of current state

I want to disable formatting for a specific project as I'm working with others who do not use emacs. As tide-format-before-save checks only for tide-mode I've tried removing the hook from before-save-hook in .dir-locals.el but that doesn't work unless I remove it globally.

## Desired Behaviour

Please add a variable which can be set buffer local which disables the formatting.

**Comment by ananthakumaran** [comment]
```elisp
(add-hook 'before-save-hook (lambda () (when (my-enable-tide-format)
                                    (tide-format-before-save))))
```
this could be easily achieved by using a lambda callback and adding your own predicate.

**Comment by RohanHart** [comment]
Fair point
