### ISSUE TITLE
Fallback to package.json location for project root?

### ISSUE THREAD

**Issue by laduke** [ananthakumaran/tide#377]
Hello,
tide is the best way to deal with javascript in emacs. 

But I'm not really a typescript user, and lot of the projects/forks I open don't have js/tsconfig.json files. So I get the "Couldn’t locate project root folder with a tsconfig.json or jsconfig.json file." message, and ignore it because that's not what I'm trying to deal with at that moment. Then I navigate around the project and end up with lots of tsserver processes running. 

Is there some way to get it to check for package.json or .git or use projectile to guess the project root, maybe just in my own tide setup/config? 

## Checklist

- [x] I have searched both open and closed issues and cannot find a duplicate.
- [x] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [x] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [x] I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.
- [ ] If [tide *is reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should not be reported*, I can run `tsc` (and `tslint`, if applicable) without the error or warning I'm seeing in tide.
- [ ] If [tide is *not reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should be reported*, `tsc` (or `tslint`, if applicable) reports the error or warning I was expecting to see.
- [ ] I am [positive](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

## Relevant Version Numbers

- Tide: tide-20200504.832   (not sure how to check, this is the elpa directory name)
- TypeScript: 3.9.2
- Emacs: 27.0.50

## Steps to Reproduce the Bug
- open js project with no jsconfig.json
- navigate around to different files in different  subdirectories

## Expected Behavior

1 tsserver per project

## Actual Behavior
1 tsserver per subdirectory

**Comment by ananthakumaran** [comment]
It's not possible to fallback to different folders, check https://github.com/ananthakumaran/tide/issues/242#issuecomment-408995380 for reason.

if you don't want to start tsserver unnecessarily, you could not enable tide if there is no tsconfig/jsconfig file available.

```elisp
(defun setup-tide-mode ()
  (interactive)
  (when (or (locate-dominating-file default-directory "tsconfig.json")
            (locate-dominating-file default-directory "jsconfig.json"))
    (tide-setup)
    (flycheck-mode +1)
    (setq flycheck-check-syntax-automatically '(save mode-enabled))
    (eldoc-mode +1)
    (tide-hl-identifier-mode +1)
    (company-mode +1)))
```

**Comment by laduke** [comment]
Thank you.
