### ISSUE TITLE
Support for authoring TypeScript targeted for Deno

### ISSUE THREAD

**Issue by zeusdeux** [ananthakumaran/tide#381]
Given that Deno v1 is out which supports typescript natively, is there a plan to add support for the way things are imported in a typescript file meant for the Deno runtime? (I.e., file extension for for imports and http imports)

**Comment by ananthakumaran** [comment]
Tide depends on [tsserver](https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-%28tsserver%29) for all editor functionalities. The feature request should be made to typescript repo

**Comment by zeusdeux** [comment]
I believe the version of tsserver internal to deno supports it. That’s what the [vscode deno plugin uses](https://github.com/denoland/vscode_deno/blob/master/README.md). Same could be leveraged here right?

**Comment by zeusdeux** [comment]
Wait, nope I’m wrong. It uses [the typescript-deno-plugin](https://github.com/justjavac/typescript-deno-plugin) to power autocomplete, etc.

**Comment by ananthakumaran** [comment]
Could you install the plugin and add it in the tsconfig file and check if
it works?

**Comment by zeusdeux** [comment]
Yeah, lemme give that go tonight! Will post here after.

**Comment by zeusdeux** [comment]
So, it Just Works!!
 
Wrote about it here -> https://til.mudit.xyz/47

**Comment by zeusdeux** [comment]
PR-Ed on deno docs as well.

**Comment by josteink** [comment]
Nice work!

To make it more discoverable for regular users, maybe you could open a PR for our readme here, add a Deno-section and make that link to the official docs you talk about?
