### ISSUE TITLE
Go to definition goes to *.d.ts when across project references

### ISSUE THREAD

**Issue by peter-wd-1** [ananthakumaran/tide#385]
It doesn't belong to bug or issue but rather a question. 
## Expected Behavior

As like [this question](https://github.com/microsoft/vscode/issues/73201) asked, I've set `"declarationMap": true` in my `jsconfig.json` file in root folder. But whenever I try to go to definition. It picks up `d.ts` file instead of js source file. 
 
Dose `"declarationMap": true` option not supported?

**Comment by ananthakumaran** [comment]
@peter-wd-1 could you confirm the behavior works in vscode for your project?

**Comment by peter-wd-1** [comment]
Hi, 

@ananthakumaran Okay. I'm using spacemacs and I've installed `faunadb` through `npm install faunadb`. 
The project works fine without any problem.

It works fine with the initial tsconfig.json file:
```
{
    "compilerOptions": {
        "target": "es2017",
        "allowSyntheticDefaultImports": true,
        "noEmit": true,
        "checkJs": true,
        "jsx": "react",
        "lib": [ "dom", "es2017" ]
    }
}
```

When I try to go to a definition from this code
<img width="509" alt="Screen Shot 2020-07-14 at 9 50 15 PM" src="https://user-images.githubusercontent.com/65737603/87494078-29269600-c61c-11ea-8aff-79603e931a84.png">

It directs me to `index.d.ts` in `faunadb` node module file instead of `index.js` file which has actual implementation.
<img width="221" alt="Screen Shot 2020-07-14 at 9 50 35 PM" src="https://user-images.githubusercontent.com/65737603/87494037-144a0280-c61c-11ea-90b1-1a622c15cb0b.png">

So I've tried the link I put above in the question:
tsconfig.json
```
{
    "compilerOptions": {
        "target": "es2017",
        "allowSyntheticDefaultImports": true,
        "noEmit": true,
        "allowJs": true,
        "checkJs": true,
        "jsx": "react",
        "lib": [ "dom", "es2017" ],
        "composite": true,
        "declarationMap": true
    }
}

```
Then it throws an error that it can't find the module `faunadb`:
<img width="779" alt="Screen Shot 2020-07-14 at 10 00 58 PM" src="https://user-images.githubusercontent.com/65737603/87494645-896a0780-c61d-11ea-9451-5fab066ef982.png">

**Comment by ananthakumaran** [comment]
I just verified this behaviour using https://github.com/RyanCavanaugh/project-references-demo. It was going to .d.ts file initially, but after I added `"declarationMap": true,` to tsconfig-base.json, it went to the source file. I guess tide works as expected, probably some issues with project config.
