### ISSUE TITLE
Does not  load require('modules') discription and node_modules d.ts files documentaion

### ISSUE THREAD

**Issue by Oscuro1111** [ananthakumaran/tide#389]
- Tide:current
- TypeScript: latest
- Emacs:25+

Its simple  tide does not load autocompletion for other files like node_modules @types

var fs = require(fs);

fs.   // nothing shown?

it workes for cases fine like

const arr = [];
arr.  //show all methods and props in popup 

why i cannot get this behavior with require(modules_name) and imports from other files ?

**Comment by josteink** [comment]
As mentioned in the issue-template you left mostly unmodified, you might get more response if you provide some more detailed reproduction steps.

A point-to-point list about things you need to do to trigger the error condition, and how this condition differs from what you expected would be helpful.
