### ISSUE TITLE
Is it possible to disable tooltip popup?

### ISSUE THREAD

**Issue by Invertisment** [ananthakumaran/tide#397]
I'm trying to set up so that popups wouldn't appear and cover my code and I can't find the variable for that.
It bothers me if I'm in the middle of refactoring and random popups keep appearing all the time.
I use spacemacs and they did configure LSP to work with auto-completion layer -- which is really great. And as tide is not configurable this way I have to find a workaround. 

Also the tooltips don't disappear instantaneously when switching from emacs to another window but the problem I want to solve is how to not have them.

I really got used to how LSP mode can display code fixing hints and other messages at the right side of the code window without covering my code:

tide:
![Screenshot at 2020-08-18 13-22-53](https://user-images.githubusercontent.com/1641263/90502452-856a6180-e156-11ea-8d5a-45aca9090cf6.png)

lsp-layer for spacemacs with auto-completion `auto-completion-enable-help-tooltip nil` and `lsp-ui-doc-enable nil`; [https://github.com/emacs-lsp/lsp-ui#lsp-ui-sideline](https://github.com/emacs-lsp/lsp-ui#lsp-ui-sideline)
![Screenshot at 2020-08-18 13-24-04](https://user-images.githubusercontent.com/1641263/90502503-987d3180-e156-11ea-9715-a7224b6c598c.png)

## Relevant Version Numbers

- Tide:
3.9.3; 20200811.2114
- Emacs:
26.3, spacemacs develop branch 346be15

**Comment by ananthakumaran** [comment]
Tide uses flycheck to display errors. You can find some customizable variables here https://www.flycheck.org/en/latest/user/error-interaction.html#display-errors. Also, this should only show up if you hover over the error with mouse. if you don't want this for any mode, you can disable `tooltip-mode` as well https://www.gnu.org/software/emacs/manual/html_node/emacs/Tooltips.html#Tooltips

**Comment by Invertisment** [comment]
Thanks.
