### ISSUE TITLE
Show full type definition of thing under cursor without truncation

### ISSUE THREAD

**Issue by sandric** [ananthakumaran/tide#399]
When submitting issues to this project, please include the following information.

## Checklist

- [x] I have searched both open and closed issues and cannot find a duplicate.
- [x] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [x] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [x] I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.
- [x] If [tide *is reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should not be reported*, I can run `tsc` (and `tslint`, if applicable) without the error or warning I'm seeing in tide.
- [x] If [tide is *not reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should be reported*, `tsc` (or `tslint`, if applicable) reports the error or warning I was expecting to see.
- [ ] I am [positive](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

## Relevant Version Numbers

- Tide: 20200823.524
- TypeScript: 3.8.2
- Emacs: 27.1

(The list above is minimal. Make sure to include any other version numbers relevant to your report.)

## Steps to Reproduce the Bug

Open typescript file and hover cursor over type definition with arguably big number of lines. Then call `tide-documentation-at-point`.

## Expected Behavior

I expect to see full type definition.

## Actual Behavior

The output is truncated if type is long - I see just a beginning, followed by `... <n lines> more ...`:

```
const context: {
    formikContext: FormikContextType<Id<Partial<Pick<object & {
        name: string;
        values: object;
    }, "name" | "values">> & Pick<object & {
        name: string;
        values: object;
    }, never>>>;
    ... 18 more ...;
    onSubmit: () => void;
}
```

![image](https://user-images.githubusercontent.com/966443/94967339-8806f780-0507-11eb-81a1-c15a27606b9e.png)

I investigated a bit `tide-documentation-at-point` and as far as  I understand - this behaviour comes from `tide-command:quickinfo` - I tried to change this to my custom function using `quickinfo-full` to take it out of equation, but get the same truncation when calling it:

```elisp
(defun sandric/tide-full-documentation-at-point ()
  "Show documentation of the symbol at point."
  (interactive)
  (tide-command:quickinfo-full
    (tide-on-response-success-callback response
      (-if-let (body (tide-construct-documentation (plist-get response :body)))
          (tide-display-help-buffer "documentation" body)
        (message "No documentation available.")))))
```

I can understand that is intentional though so that output can be truncated in minibuffer, but I would appreciate if someone points me to how to define my own function to show full type.

**Comment by ananthakumaran** [comment]
tide doesn't truncate the output, it's done at tsserver https://github.com/microsoft/TypeScript/issues/26238. Make sure to set `noErrorTruncation` to true, there is still a hard limit as explained in the https://github.com/microsoft/TypeScript/issues/26238#issuecomment-672086446
