### ISSUE TITLE
Conflicting indent style in switch statements

### ISSUE THREAD

**Issue by wizzomafizzo** [ananthakumaran/tide#40]
I think typescript-mode is having a fight with the tide formatter about how switch statements should look? When I am editing a file, typescript-mode will indent switch statements like this:

```
switch ($foo) {
case 123:
    break;
}
```

But when I save the file with formatting enabled, it changes it to this:

```
switch ($foo) {
    case 123:
        break;
}
```

And they will just keep going back and forth as I edit. Is there a config option somewhere I'm missing to change this? I'd prefer the second style for both.

Using these from the readme:
'(:insertSpaceAfterFunctionKeywordForAnonymousFunctions t :placeOpenBraceOnNewLineForFunctions nil)
typescript-mode ver: 0.1 / 20160616.2007

**Comment by ananthakumaran** [comment]
I guess tide can't do anything here. Either tsserver should provide a format option, or typescript-mode should match tsserver style. There is a open issue in typescript-mode to track this. https://github.com/ananthakumaran/typescript.el/issues/23

**Comment by josteink** [comment]
> Either tsserver should provide a format option, or typescript-mode should match tsserver style.

I think there's no doubt about this one: Typescript-mode should match whatever tsserver does.

Agreed about closing this issue as a tide-issue though.

**Comment by wizzomafizzo** [comment]
Makes sense to me. Thanks for looking into it!
