### ISSUE TITLE
Support separate face for interpolated part of template string

### ISSUE THREAD

**Issue by mordocai** [ananthakumaran/tide#41]
I'm going to look at hacking this in myself, but I have no experience writing emacs modes so it'll be difficult for me to figure out.

I would like a typescript template string:

    `I am a template string ${blargh} see me interpolate!`

To have a separate face on the ${blargh} part compared to the rest of the template string.

This makes it easier for the human to parse the template strings in my opinion.

See https://www.typescriptlang.org/docs/handbook/basic-types.html if you are unfamiliar with template strings (I think they were implemented fairly recently?)

**Comment by ananthakumaran** [comment]
@mordocai Thanks for your interest. This project doesn't deal with syntax highlighting. It is provided by https://github.com/ananthakumaran/typescript.el.

That said, I am already aware of the problem and I had made an initial attempt and my changes are in `interpolation` branch. It handles simple cases, but I haven't tested it much, so you can have a look at it and test it out and start from it. As for implementation goes, it is based on `ruby-mode`. so the easiest way would be to understand how `ruby-mode` does interpolation and implement it in `typescript-mode`.
