### ISSUE TITLE
Wrong type argument: flycheck-error-p

### ISSUE THREAD

**Issue by elibarzilay** [ananthakumaran/tide#417]
(I didn't go through the checklist, since I'm not sure whether this is even a bug on the tide side.)

I recently updated tide: the package directory is `tide-20210211.1055`, the version in `tide.el` is 4.0.5.

I often get warnings that look like the following:

> Error from syntax checker typescript-tide: Wrong type argument: flycheck-error-p, [cl-struct-flycheck-error #<buffer pr-trigger.ts> typescript-tide "/home/eli/ts/mergebot/src/pr-trigger.ts" 38 64 #("'WebhookPayloadCheckSuite' is deprecated" 0 1 (diagnostic (:start (:line 38 :offset 64) :end (:line 38 :offset 88) :text #1 :code 6385 :category "suggestion" :reportsDeprecated t))) info 6385 nil]

Is this something that is known?  If it is, I'll be happy for any idea on what's wrong.  If it isn't, then I'll try to hunt it down...

**Comment by ananthakumaran** [comment]
> Is this something that is known?
no

make sure it's not due to macro issue, probably try to reinstall flycheck/tide

**Comment by josteink** [comment]
Could it be related to use of native Emacs JSON serializer (`json-parse-buffer`) vs "the old" one?

**Comment by elibarzilay** [comment]
Looks like I somehow messed things up in the `elpa` directory.  (Not sure how, I had an old copy of everything moved into `.emacs.d/ORIG/`, and maybe somewhere the package system is looking for files in any subdirectory.)

In any case, now it works fine again.
