### ISSUE TITLE
tide-format-options

### ISSUE THREAD

**Issue by andreineculau** [ananthakumaran/tide#42]
If I follow through the code correctly, the README.md is outdated, since it mentions

`(setq tide-format-options '(:insertSpaceAfterFunctionKeywordForAnonymousFunctions t :placeOpenBraceOnNewLineForFunctions nil))`

but these options are not being passed to the tsserver AFAICS.

The point is not the possibly outdated README.md but how to actually pass options to the tsserver i.e. I format on save, but I don't want spaces in between the braces, but those settings `:spaceAfterOpenBrance nil :spaceBeforeCloseBrance` don't propagate. Any help is appreciated

**Comment by ananthakumaran** [comment]
@andreineculau I had a quick look at the log file and the options are propagated properly to the tsserver, it's likely that the key you are using is misspelled or not supported by tsserver. Enable [log](https://github.com/ananthakumaran/tide#debugging) option and see if there are other problems.

**Comment by jmhdez** [comment]
I'm having a similar problem. 

Using the tss debug log I can see the right options are passed to the server with the configure command, but the formatting is not being applied _to the first opened buffer_. However, if I visit another file or just kill the first buffer and visit it again, formatting starts to work.

**Comment by jmhdez** [comment]
@andreineculau I've managed to find a (ugly) workaround.

It seems the problem is that `tide-configure-buffer`, which pass format options to the server, is not working as expected when the first buffer is opened. It's being called, but the server is ignoring is.

The "solution" I've found is to call `tide-configure-buffer` _every time_ format is applied. It's far from optimal, but at least works. In case you are interested, this is the fix I've applied to `tide.el`:

```elisp
(defun tide-format ()
  "Format the current region or buffer."
  (interactive)
  
  ;; HACK: This shouldn't be needed, but the first time a buffer is
  ;; opened, format options are not honored, so I'm forcing an extra
  ;; tide-configure-buffer before applying formatting
  (tide-configure-buffer)
  
  (if (use-region-p)
      (tide-format-region (region-beginning) (region-end))
    (tide-format-region (point-min) (point-max))))
```

**Comment by andreineculau** [comment]
hmm, after some debugging and soul searching, I am actually experiencing this https://github.com/Microsoft/TypeScript/issues/7540 . therefore closing

@jmhdez thanks for the input nevertheless. I actually couldn't reproduce what you're talking about, except that starting the tsserver takes a while and any saves before that don't trigger the formatting, so can it be that all is fine if you wait longer?

**Comment by ananthakumaran** [comment]
@jmhdez My last commit in master should probably fix your problem. Can you test it?

**Comment by jmhdez** [comment]
@ananthakumaran I've applied the fix manually (I don't want to update to TS2.0), and it works. Thanks!
