### ISSUE TITLE
Tide does not start

### ISSUE THREAD

**Issue by m1cm1c** [ananthakumaran/tide#438]
## Relevant Version Numbers

- OS: Manjaro (up to date)
- Tide: 20220102.441 (v4.5.4)
- TypeScript: 4.6.2 (using es6 as configured in `tsconfig.json`)
- Node: v16.9.1
- Emacs: 27.2

## Steps to Reproduce the Bug
I cannot not reproduce the bug. It even occurs when using an entirely empty `.emacs.d` directory. I merely set up Melpa so I can install Tide but the problem still occurred.

## Actual Behavior
When running `setup-tide-mode` (taken from the README) after opening a *.ts file, the following occurs in `*Messages*`:

```
(server-c749e5a42b) Starting tsserver...
(server-c749e5a42b) tsserver server started successfully.
Error while checking syntax automatically: (error "Process tsserver not running")
(server-c749e5a42b) tsserver exits: exited abnormally with code 127.
Error running timer ‘tide--hl-identifiers-function’: (error "Server does not exist. Run M-x tide-restart-server to start it again")
```

`tsserver.js` appears to run if I simply run it on the command line using `node`:
![image](https://user-images.githubusercontent.com/11382432/157264527-eff9a4b2-5487-40d8-b2b5-358dbfb70b3a.png)

## Fixes that Do Not Work
The only result that came up when I googled the bug was #114. The solution presented in that issue (setting `tide-tsserver-executable` to `nil`) does not apply because `tide-tsserver-executable` already is `nil`.

**Comment by ananthakumaran** [comment]
could you enable [logging](https://github.com/ananthakumaran/tide#debugging) and check the logs. It looks like your tsserver process is crashing. This could happen in multiple ways. Which tsserver is used depends on lot of factors (whether you have local npm install tsserver/global npm install tsserver etc) You can use `execsnoop` command to figure out exactly what command is executed by emacs.

**Comment by ananthakumaran** [comment]
From the report so far, there is not much information available for me to dig deeper. If I can reproduce the issue, I would be able then to debug it.

Since you don't see anything logs, the tsserver is probably crashing right after it started. As I suggested earlier, you can try to figure out what command is being executed and try to run it via terminal. You can use either `execsnoop` (this should be available in linux probably as part of perf-tool or bcc tools). Another option is to use the elisp `M-x trace-function start-file-process`, this should print the args and return value. Tide uses that function to start the tsserver

**Comment by m1cm1c** [comment]
Interesting; I was pretty sure that the built-in tsserver was being used but according to `M-x trace-function start-file-process`, an npm package of the project I'm working on is being used:

```
======================================================================
1 -> (start-file-process "tsserver" #<buffer *tide-server*> "node" "/home/christoph/Development/server/node_modules/typescript/lib/tsserver.js")
1 <- start-file-process: #<process tsserver>
```

If i run `"node" "/home/christoph/Development/server/node_modules/typescript/lib/tsserver.js"` on a terminal (bash), it prints

```
Content-Length: 76

{"seq":0,"type":"event","event":"typingsInstallerPid","body":{"pid":42466}}
```

and does not terminate on its own (but it does terminate on Ctrl+C).

If I put `(setq tide-tsserver-executable "/home/christoph/.emacs.d/elpa/tide-4.5.4/tsserver/tsserver.js")` into my init file, it behaves pretty similarly:

```
(server-c749e5a42b) Starting tsserver...
(server-c749e5a42b) tsserver server started successfully.
File local-variables error: (error Process tsserver not running)
Error while checking syntax automatically: (error "Process tsserver not running")
(server-c749e5a42b) tsserver exits: exited abnormally with code 127.
Error running timer ‘tide--hl-identifiers-function’: (error "Server does not exist. Run M-x tide-restart-server to start it again") [2 times]
```

```
======================================================================
1 -> (start-file-process "tsserver" #<buffer *tide-server*> "node" "/home/christoph/.emacs.d/elpa/tide-4.5.4/tsserver/tsserver.js")
1 <- start-file-process: #<process tsserver>
```

**Comment by ananthakumaran** [comment]
Can you set `tide-node-executable` to your absolute path of node. Also please enable debug mode `M-x toggle-debug-on-error` and see if you get more stack trace

**Comment by m1cm1c** [comment]
> Can you set `tide-node-executable` to your absolute path of node.

Thank you very much! This made the error go away; tide works now! :)

The additional error log (if I do not set `tide-node-executable` to the absolute path of node):
```
Debugger entered--Lisp error: (error "Process tsserver not running")
  process-send-string(#<process tsserver> "{\"command\":\"open\",\"seq\":\"3\",\"arguments\":{\"file\":\"/home/christoph/Development/server/src/async/index.ts\",\"scriptKindName\":\"TS\"}}\n")
  tide-send-command("open" (:file "/home/christoph/Development/server/src/async/index.ts" :scriptKindName "TS"))
  tide-command:openfile()
  tide-configure-buffer()
  tide-configure-buffer-if-server-exists()
  run-hooks(hack-local-variables-hook)
  hack-local-variables-apply()
  hack-local-variables(no-mode)
  run-mode-hooks(typescript-mode-hook)
  typescript-mode()
  set-auto-mode-0(typescript-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer index.ts> "~/Development/server/src/async/index.ts" nil nil "~/Development/server/src/async/index.ts" (59378743 2304))
  find-file-noselect("/home/christoph/Development/server/src/async/index.ts" nil nil nil)
  find-file("/home/christoph/Development/server/src/async/index.ts")
  (if (member (get-mimetype file) unsupported-mime-types) (call-process "xdg-open" nil 0 nil file) (find-file file))
  (let ((file (dired-get-filename nil t))) (if (member (get-mimetype file) unsupported-mime-types) (call-process "xdg-open" nil 0 nil file) (find-file file)))
  dired-find-file-dwim()
  funcall-interactively(dired-find-file-dwim)
  call-interactively(dired-find-file-dwim nil nil)
  command-execute(dired-find-file-dwim)
```

I think that the error is in my `$PATH` definition. The absolute path of node is `/home/christoph/.nvm/versions/node/v16.9.1/bin/node` on my system because I use nvm. `/home/christoph/.nvm/versions/node/v16.9.1/bin` is in my `$PATH` on bash. However, if I open an eshell and print `$PATH`, it's not there. It's only there if I launch bash in eshell and then print `$PATH`.

You can probably best prevent others from running into this problem by adding a hint to the README stating that the user is to make sure that node is in `$PATH` on eshell, especially when using nvm which seems to modify `$PATH` on its own but apparently only for the shell you called it in or that you installed it in (idk).

**Comment by ananthakumaran** [comment]
nice

> You can probably best prevent others from running into this problem by adding a hint to the README stating that the user is to make sure that node is in $PATH on shell

I was under the assumption that the start-file-process would print a proper error message if it can't find the executable (It does show error for me)

**Comment by m1cm1c** [comment]
> I was under the assumption that the start-file-process would print a proper error message if it can't find the executable (It does show error for me)

Maybe it does. But apparently I have a non-working installation of `node` in `/usr/bin` which is in eshell's `$PATH` (I did not know about this):

```
$ node
/usr/bin/node: error while loading shared libraries: libicui18n.so.69: cannot open shared object file: No such file or directory
```

**Comment by ananthakumaran** [comment]
got it. If you had used execsnoop, you might have found it earlier. It would show the exact binary (full path) with the all the args etc.

**Comment by temtem124** [comment]
> Can you set tide-node-executable to your absolute path of node
Can I ask how to set it?

**Comment by m1cm1c** [comment]
> > Can you set tide-node-executable to your absolute path of node
> 
> Can I ask how to set it?

Put something like this into your init file:

```
(setq tide-node-executable "/home/temtem124/.nvm/versions/node/v16.9.1/bin/node")
```
