### ISSUE TITLE
Error 'void-variable tide-references-mode-map' when opening tsx file

### ISSUE THREAD

**Issue by zerinoid** [ananthakumaran/tide#446]
When submitting issues to this project, please include the following information.

## Checklist

- [x] I have searched both open and closed issues and cannot find a duplicate.
- [x] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [x] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [x] I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.

- [x] I am [positive](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

## Relevant Version Numbers

- Tide: 20220514.614
- TypeScript: 4.7.4
- Emacs: 28.1.90 and 27.2.50
- Node 16.16.0 or 14.20.0

(The list above is minimal. Make sure to include any other version numbers relevant to your report.)

## Steps to Reproduce the Bug

Load emacs
open a tsx file

## Expected Behavior

tide server runs automatically

## Actual Behavior

message buffer shows:

`File local-variables error: (void-variable tide-references-mode-map)`

I have to run `tide-setup` to make the server start

**Comment by ananthakumaran** [comment]
There is not much info available here to make any useful suggestions. Please post a full stacktrace. My wild guess would be something wrong with the installation? perhaps try to re-install the package, as I don't see why you would get tide-references-mode-map would be undefined.

**Comment by ananthakumaran** [comment]
Closing this, feel free to re-open with the stacktrace details.
