### ISSUE TITLE
Wrong type displayed if narrowed within the same line

### ISSUE THREAD

**Issue by m1cm1c** [ananthakumaran/tide#449]
## Relevant Version Numbers

- OS: Manjaro (up to date)
- Tide: more recent than the latest release (master branch during March)
- TypeScript: 4.6.2 (using es2020 as configured in `tsconfig.json`)
- Node: v16.9.1
- Emacs: 28.1

## Steps to Reproduce the Bug

Paste the following code into a TS buffer:

```
async function foo(bar: string | Promise<string>): Promise<void> {
  bar = await bar;
  console.log(bar);
}
```

## Expected Behavior

When placing point on `bar` in line 2, the displayed type should be `string` because `await bar` can only return `string`.

## Actual Behavior

The type is displayed as `string | Promise<string>`:
![Screenshot_20220722_160549](https://user-images.githubusercontent.com/11382432/180457798-f61788ba-69e0-41b5-b26d-946d49f8caca.png)

In the next line, it works correctly:
![Screenshot_20220722_160608](https://user-images.githubusercontent.com/11382432/180457845-c7acf698-54ce-406d-a27d-1c447b04fc49.png)

This only happens if the variable on the left pre-exists, i.e. `let baz = await bar;` or `const baz = await bar;` does not exhibit this behavior when point is placed on `baz`.

**Comment by ananthakumaran** [comment]
Check the [debugging](https://github.com/ananthakumaran/tide#debugging) second. Tide sends the cursor location to the tsserver and doesn't know much. Any bug related to semantics should be reported to typescript repo

**Comment by m1cm1c** [comment]
@ananthakumaran Thank you. Will report it there.
