### ISSUE TITLE
Integration of lsp-bridge

### ISSUE THREAD

**Issue by Joxos** [ananthakumaran/tide#450]
## Feature Request

Can tide integrate lsp-bridge? It's now the fastest lsp backend in Emacs.

**Comment by Joxos** [comment]
https://github.com/manateelazycat/lsp-bridge

Here is the repo.

**Comment by ananthakumaran** [comment]
I fail to see how this is relevant to tide. Tide only provides support for typescript/javascript and the only supported backend is tsserver (which doesn't actually follow the lsp protocol).
