### ISSUE TITLE
Expanding tsconfig.json locating logic to deal with unusual (?) project dir structures

### ISSUE THREAD

**Issue by dlbeswick** [ananthakumaran/tide#461]
When submitting issues to this project, please include the following information.

## Checklist

- [x] I have searched both open and closed issues and cannot find a duplicate.
- [x] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [x] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [x] I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.
- [x] If [tide *is reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should not be reported*, I can run `tsc` (and `tslint`, if applicable) without the error or warning I'm seeing in tide.
- [x] If [tide is *not reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should be reported*, `tsc` (or `tslint`, if applicable) reports the error or warning I was expecting to see.
- [x] I am [positive](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

## Relevant Version Numbers

- Tide: 20220514.614
- TypeScript: 4.9.3
- Emacs: 27.0.50

(The list above is minimal. Make sure to include any other version numbers relevant to your report.)

## Steps to Reproduce the Bug

Hello, I'm not a seasoned Typescript developer so I may not have the best idea here with regards to project layout, but I'll explain the issue that I was having. Very happy to be corrected!

I'm developing an app with a frontend and backend component. My project layout looks like this:

    project_root/
        package.json
    
        common/
            source...
    
        backend/
            .emacs.desktop
            tsconfig.json
            source...
    
        frontend/
            .emacs.desktop
            tsconfig.json
            source...

Each component has different configs because they have different targets; the backend runs on Node and the frontend in the browser. Both components also share common code, and that sits in the `common` folder.

Note that I also use Emacs' "Desktop" function and I have a desktop file in both `frontend` and `backend`. I have one desktop for each component so I can save buffers, command history, etc., that's relevant to each component.

The difficulty I found is in the logic Tide uses to locate "tsconfig.json". In function `tide-project-root`, it searches using `locate-dominating-file` for tsconfig.json or jsconfig.json. It looks for these files starting from the location of the current buffer's directory. However, when I browse files from my `common` location, Tide can't locate a tsconfig.json and autocomplete, etc., doesn't work correctly for those files (an "inferred project is used.")

## Expected Behavior

What I would like to do is tell Tide to use a tsconfig.json file that's appropriate for the current "project/component" I'm working on, possibly via a "fallback" mechanism.

## Actual Behavior

Tide always tries to use the tsconfig.json file dominant in the buffer directory.

## My solution

I redefine `tide-project-root` like so:

```elisp
(defun tide-project-root ()
  "Project root folder determined based on the presence of tsconfig.json.
                Augmented: use desktop-dirname if no tsconfig is found in hierarchy."
  (or
   tide-project-root
   (let ((root (or (locate-dominating-file default-directory "tsconfig.json")
		   (locate-dominating-file default-directory "jsconfig.json"))))
     (unless root
       (message (tide-join (list "Couldn't locate project root folder with"
				 " a tsconfig.json or jsconfig.json file. Using '"
				 (or desktop-dirname default-directory) "' as project root.")))  ;; ADDED
       (setq root (or desktop-dirname default-directory)))                                       ;; ADDED
     (let ((full-path (expand-file-name root)))
       (setq tide-project-root full-path)
       full-path))))
```

If the normal logic can't find a tsconfig.json file, then Tide falls back to using `desktop-dirname`. This suits my needs, but it's perhaps more flexible for Tide to provide a hook that can be used to supply the fallback location for tsconfig.json if it can't be found.

If you like this approach and would like me to work on a PR then I'm happy to do that; please let me know. 

As also mentioned, anyone please do feel free to comment if there's a more correct way to organise these kinds of projects.

**Comment by ananthakumaran** [comment]
This issue has been discussed multiple times. Search through the issue tracker for previous ones.
check https://github.com/ananthakumaran/tide/issues/242 as well. The main thing to notice here is, it's not about how tide locates tsconfig.json, but rather how tsserver locates it. Tide can't use an arbitrary file.
