### ISSUE TITLE
ESM module File extension for NodeJS

### ISSUE THREAD

**Issue by nicemaker** [ananthakumaran/tide#462]
We are developing now TS to be compile directly to es2022 with esm modules.
Problem is that node esm modules expects file extensions for imports statements:
So instead `import { foo } from './bar'` the final import has to be `import { foo } from './bar.js'`
As you probably know Typescript team is really stubborn on this topic and they don't want to add that feature to the tsc compiler. There advice is to add the `.js` ending to the imports in the `.ts` files (I know its weird). We are doing that and it works, but its a manual process because the automatic import of tide doesn't support that. VSCode has a flag to add the file extension to the autocompleted imports. Would be great if we can have that in emacs as well.
Don't think that tsserver team will help much considering the heated discussion.

**Comment by ananthakumaran** [comment]
Can you try to configure [importModuleSpecifierEnding](https://github.com/microsoft/TypeScript/blob/8749fb5c0a4a0e3407eb099322c85b850cc642aa/src/server/protocol.ts#L3513) option in [tide-user-preferences](https://github.com/ananthakumaran/tide#tide-user-preferences-includecompletionsformoduleexports-t-includecompletionswithinserttext-t-allowtextchangesinnewfiles-t-generatereturnindoctemplate-t) and see if it solves your issue.

**Comment by nicemaker** [comment]
Thanks for the fast response, that worked like a charm. Below example snippet for anyone needing it.
Any suggested way to do this on a per project basis? I see that you support local project files for formatting the code (tsfmt.json), do you support something like this for typescript settings?

Here the example,  I guess you could also move that setting to the setup-tide mode function described in the docs.

```
(use-package tide
  :after (typescript-mode company)
  :config (tide-user-preferences '(:importModuleSpecifierEnding t))
  :hook(
    (typescript-mode . setup-tide-mode)
    (js-mode . setup-tide-mode)
    (js2-mode . setup-tide-mode)
    (before-save . prettier-js-command)))...

**Comment by ananthakumaran** [comment]
> Any suggested way to do this on a per project basis?

checkout [.dir-local.el](https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html)

> Might be good to mention this particular setting in the docs more prominent

I hope this issue will act as documentation. But if we get lot of issues, we usually add them to FAQ

**Comment by nicemaker** [comment]
Thanks a million
