### ISSUE TITLE
list all possible format options

### ISSUE THREAD

**Issue by andreineculau** [ananthakumaran/tide#47]
or just put a link e.g. https://github.com/Microsoft/TypeScript/blob/2c40fea/src/services/services.ts#L1259
or to the relevant lines in the bundled tsserver.js

**Comment by andreineculau** [comment]
:+1:

PS: be aware of the typescript-mode-hook that you slipped into this commit ,)

**Comment by ananthakumaran** [comment]
ha, It was there already, just moved it a bit up.
