### ISSUE TITLE
tsserver exists [sic]: abort trap: 6.

### ISSUE THREAD

**Issue by anisoptera** [ananthakumaran/tide#49]
I just upgraded to TS2 and I'm having a problem where tsserver only stays open for about 5 seconds before dying either from "killed: 9" or "abort trap: 6", even on the test project included in this repo.

I've attached a tss.log generated from this crash. I looked at it - it doesn't show any obvious signs of failure. Requests seem to get completed while the server is up - I can get it to reformat my file if I'm fast enough.

When starting tsserver from the command line it seems to work fine. I can replay some of the commands from the log into the terminal window and I get good results, and the server never dies.

I'm on OS X 10.11.5, emacs 24.1.1, using spacemacs, latest version off elpa.

Let me know if there are any other logs I can gather.

[tss.txt](https://github.com/ananthakumaran/tide/files/377671/tss.txt)

**Comment by ananthakumaran** [comment]
what is your node version?

**Comment by anisoptera** [comment]
Ah, it's 6.0.0. I thought npm would update my node version but it looks like that doesn't happen through npm anymore.

Updated to 6.3.1 and that seems to have resolved the problem. Thanks much!
