### ISSUE TITLE
Tide not picking up globals as of a couple weeks ago

### ISSUE THREAD

**Issue by mordocai** [ananthakumaran/tide#50]
This is probably more of a support issue than a bug, but I couldn't find another way to get help(sorry).

Recently ( I think within the past couple weeks) tide has stopped picking up my global type definitions. It just says "Cannot find name \<global thing\>"

When I compile the same files with typescript + webpack it works fine.

I am using the melpa version of tide, typescript 1.8.10, and typings 1.3.2. 

tsconfig.json
```
{
  "compilerOptions": {
    "target": "es5",
    "sourceMap": true,
    "module": "commonjs"
  },
  "exclude": [
    "node_modules",
    "typings/index.d.ts",
    "typings/"
  ]
}
```

typings.json
```
{
  "globalDependencies": {
    "angular": "github:DefinitelyTyped/DefinitelyTyped/angularjs/angular.d.ts#fa3294c560ee49f4af43e02a62e3f4b5b6bbe5e5",
    "angular-ui-bootstrap": "registry:dt/angular-ui-bootstrap#0.13.3+20160602140119",
    "angular-ui-router": "registry:dt/angular-ui-router#1.1.5+20160521151413",
    "jquery": "github:DefinitelyTyped/DefinitelyTyped/jquery/jquery.d.ts#4cdfbe96b666eec5e1defbb519a62abf04e96764",
    "lodash": "github:typed-typings/npm-lodash/global#73a6037f16173baee0b40136eee07b2c7ad243c8",
    "moment": "github:DefinitelyTyped/DefinitelyTyped/moment/moment.d.ts#56295f5058cac7ae458540423c50ac2dcf9fc711",
    "moment-node": "github:DefinitelyTyped/DefinitelyTyped/moment/moment-node.d.ts#122b5dd8d183028e514d7cc531340847b22d6c26"
  },
  "globalDevDependencies": {
    "jasmine": "registry:dt/jasmine#2.2.0+20160505161446"
  }
}
```

typescript.el
```
(use-package tide
  :ensure t
  :init
  (add-hook 'typescript-mode-hook
          (lambda ()
            (tide-setup)
            (flycheck-mode +1)
            (setq flycheck-check-syntax-automatically '(save mode-enabled))
            (eldoc-mode +1)
            ;; company is an optional dependency. You have to
            ;; install it separately via package-install
            (company-mode +1))))
```

**Comment by ananthakumaran** [comment]
Tide comes with a bundled tsserver. We recently upgraded tide to use typescript 2.0.0-beta. Probably the global lookup behavior has changed?. I also just tagged 1.8.10. You can pickup the specific version if you want to use 1.8

**Comment by mordocai** [comment]
@ananthakumaran Thanks! That was the issue. I put 1.8.10 version of tide in my emacs config manually and everything looks like it works again. Closing.

**Comment by ananthakumaran** [comment]
Great. Tide has an [option](https://github.com/ananthakumaran/tide/blob/master/tide.el#L54) to configure the tsserver binary. But it only works for TS 2.0 and above.
