### ISSUE TITLE
Failed to verify signature

### ISSUE THREAD

**Issue by TCMiranda** [ananthakumaran/tide#51]
Hey guys,

I got this problem, and I don't even know if it is related to the package.
But I've just upgraded my other packages, and the only one that threw me the error was this one.

The error:
`Failed to verify signature seq-2.16.tar.sig: ("Bad signature from 474F05837FBDEF9B GNU ELPA Signing Agent <elpasign@elpa.gnu.org>")  `

Anyone can head me to the solution?

Thanks!

**Comment by ananthakumaran** [comment]
I am not sure how this question is related to tide. Best to ask in other QA sites like stackoverflow.

**Comment by TCMiranda** [comment]
Yea. Couldn't it be related to the package publication?

**Comment by TCMiranda** [comment]
Just to be clear, that error is the response of `M-x package-install [ret] tide` maybe some dependency got lost.

**Comment by TCMiranda** [comment]
I had to download seq-2.16 and install it by myself, or else it wouldn't have managed to resolve its dependencies.

But I am closing this as it does not seems important
