### ISSUE TITLE
Support for angular templates

### ISSUE THREAD

**Issue by rtm** [ananthakumaran/tide#54]
I see some editors are now starting to support smart editing of angular templates, including type-checking of referenced properties on the underlying component. I understand this is based on some fork of typescript which provides additional necessary metadata. This is something that would be lovely to have.

**Comment by ananthakumaran** [comment]
can you add more details like the editor & forked typescript repo? If this is handled transparently by the `tsserver`, you can just change `tide-tsserver-executable`.

**Comment by rtm** [comment]
There is something called https://github.com/Microsoft/TypeScript-TmLanguage, but I'm not sure exactly where this fits in the ecosystem. Then there is the ngml fork of TypesScript,  Then there is this so-called "[Experimental TypeScript plugin for Angular2 templates](https://github.com/billti/ngml)" but I have no idea what it is supposed to do. There is a [TypeScript extensibility](https://github.com/microsoft/typescript/issues/6508) in the TypeScript repo which is interesting.

**Comment by ananthakumaran** [comment]
Tide already supports editing TSX files. From the look of it, they would provide similar functionality for angularjs. Tide provides a thin UI layer on top of `tsserver`, so if they just use autocomplete, tooltip etc, then it would work right away in Tide without any modification in UI layer.

**Comment by ananthakumaran** [comment]
Plugin API is already supported by tssever https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin. Closing this as there are no action items on tide.
