### ISSUE TITLE
Is there a way to get the type under cursor?

### ISSUE THREAD

**Issue by hiddenlotus** [ananthakumaran/tide#57]
Thanks for your great work~
I think it's a convenience with a helper function to describe the type of the symbol under cursor. 
Is that possible?

**Comment by ananthakumaran** [comment]
I am not sure I understand your request. Have you checked the eldoc integration? does that achieve what you want?

**Comment by hiddenlotus** [comment]
I think the eldoc integration could achieve what I want.
Thanks.
However I will bind the eldoc function to some key to show the type under cursor manually.
