### ISSUE TITLE
Getting warnings about decorators, says to pass --experimentalDecorators

### ISSUE THREAD

**Issue by dotDeeka** [ananthakumaran/tide#6]
I'm trying to switch from emacs-tss to tide but when I load any TS file that has a decorator in it I get warnings that say that decorators are experimental and I should pass --experimentalDecorators to get rid of the warnings.

I originally added experimentalDecorators: true to my tsconfig.json files compilerOptions but the warnings didn't go away. After a little more investigation it seems experimentalDecorators is not one of the compilerOptions (https://github.com/Microsoft/TypeScript/wiki/Compiler-Options).

Am I missing something?

**Comment by ananthakumaran** [comment]
>`M-x tide-restart-server` Restart tsserver. Currently tsserver doesn't pickup tsconfig.json file changes. >This would come in handy after you edit tsconfig.json.

did you run tide-restart-server?

**Comment by dotDeeka** [comment]
Previously I stopped and started emacs again, assuming that would detect the changes. Just now I tried running tide-restart-server to see and I still get the same warning.

Thanks for the quick reply.

**Comment by ananthakumaran** [comment]
just added an example https://github.com/ananthakumaran/tide/commit/329a4f3d76cf67f86eb4ed402eb1304a119c924c
