### ISSUE TITLE
Make `tide-references` behave like occur and compilation-mode

### ISSUE THREAD

**Issue by josteink** [ananthakumaran/tide#61]
When you use `occur` or compile things using `compilation-mode`, you get the results presented in a buffer which where you can navigate between the results using `previous-error` and `next-error` (even though not all things are errors).

I have these commands conveniently bound to F7 and F8 and it works pretty much for all things Emacs. All things except tide's `tide-references`.

Would this be possible to add?

**Comment by ananthakumaran** [comment]
There are already couple of methods that provide navigation (bound to `n` & `p` by default). https://github.com/ananthakumaran/tide/blob/master/tide.el#L726. Could you use those?

**Comment by josteink** [comment]
Those are *different* from what works everywhere else, so it's not really optimal. It also has the disadvantage that the buffer has to be open to use those keys.

`next-error` and `last-error` are global functions accessible from any buffer, meaning you can easily jump from one to the other, without having to go back to the Occur/Build/References-buffer to choose the next one.

It really improves the flow of code navigation.

I'll take a look at how other similar packages for other languages (Racer for Rust, Omnisharp for C#, etc) does this to make it work with the error-system for seamless navigation.

Maybe it's a simple fix, and in that case, I might send a patch back to fix this myself.

**Comment by josteink** [comment]
Looking at `omnisharp-emacs` it seems it's just a matter of [creating a new buffer, use `compilation-mode` for it](https://github.com/OmniSharp/omnisharp-emacs/blob/master/src/omnisharp-utils.el#L37-L68), and ensure [your lines are formatted correctly](https://github.com/OmniSharp/omnisharp-emacs/blob/master/src/omnisharp-utils.el#L70-L87) to trigger the navigation effect.

The format is something we can define ourselves, or like in the case of `omnissharp-emacs`, just reuse an existing one.

It really doesn't seem like an impossible job, but it might break compatibility with the existing implementation. Any opinion? Should I prepare a patch? :)

**Comment by josteink** [comment]
This is obviously not finished code, and it can use some refinements (and probably some cleanup if any obsolete code is left behind as well), but it shows how simple a thing like this can be.

https://github.com/josteink/tide/commit/1d050517e3cd8bd9ba8cfbe88ab6741b6b852866

This will leverage everything emacs already has for these purposes, and present the results in a more standard way.

Obviously the formatting will take some work, but you get the idea. What do you think?

**Comment by josteink** [comment]
**Edit:** A more refined edit can be found here: https://github.com/josteink/tide/commit/2f099ec6c4f8b0b710105ffae3a7da584a9955e6

It has improved formatting and I've cleaned out some obsolete code. Basically re-use more from the Emacs base and less to maintain yourself :)

As for my setup: I have mode-local "Find references" bound to Shift-F12, and `next-error` and `previous-error` globally bound to F7 and F8. If you do that (or anything equally accessible), you can super-quickly navigate all references to any symbol super quickly, across all language-modes. 

No need to stay in the references buffer either. Like all good read-only Emacs-buffer it also closes itself when you press "q" (something the current `tide`-implementation also doesn't do). It's super-efficient, and I want that for TypeScript too.

On overall, I consider this quick doodle an improvement already, but I'm open to feedback. What do you think? :)

**Comment by josteink** [comment]
Any news on this? Any particular feedback?

**Comment by ananthakumaran** [comment]
I have been little busy lately. I will try to review it soon.

I like the fact that it reduces the code, but not sure about the ux. compilation mode shows redundant information like file-name etc. I will try to do a proper review soon

**Comment by josteink** [comment]
Sure. Sounds good!

Keep in mind this was my first best effort only.

Some of the redundancies *may* be possible to work out with a custom compilation mode format expression, but I didn't want to put in too much effort into the prototype if you decidedly didn't like it or wouldn't consider a possible change.

Anyway: Thanks for your time :)

**Comment by ananthakumaran** [comment]
![screen shot 2016-09-29 at 4 32 06 pm](https://cloud.githubusercontent.com/assets/149238/18951484/1167eb10-8663-11e6-909a-55468f96b203.png)
![screen shot 2016-09-29 at 4 30 47 pm](https://cloud.githubusercontent.com/assets/149238/18951488/153c6e96-8663-11e6-9ece-21e973dd99eb.png)

Tide reference does the following things
1) highlights the search symbol
2) group together by file name
3) handles multiple references in the same line. It doesn't show the same line twice

if we can get the same with compilation mode, then I am ok with the switch.

**Comment by josteink** [comment]
Thanks.

I think that should be quite doable. I'll take a look at it when I have more time, and I'll prepare a PR.

**Comment by josteink** [comment]
I've submitted a PR for this. Any chance to get it reviewed? :)
