### ISSUE TITLE
flycheck doesn't use next syntax checker (tslint) after tide

### ISSUE THREAD

**Issue by fugalfunkster** [ananthakumaran/tide#67]
Bug Observed: Flycheck does not apply the tslint syntax checker after applying the tide syntax checker. I report this behavior as an issue because line 1091 in tide.el suggests an intent to execute these syntax checkers consecutively.

Context: I installed typescript-mode and tide, as well as typescript and tslint, for the first time tonight. I followed the configuration recommended in the readme.md for those files. My dot files are publically available on my github account.

Documentation of Observation: In the first attached screenshot, I have a main.ts file (top left window) that violates multiple tslint rules (tslint.json in bottom right window). The tide syntax checker is active, and the tslint syntax checker is not disabled (top right frame).  And, my dot files contain the code from the tide readme.md (bottom left window). However, the only error/warnings that flycheck displays in the buffer are those from tide.

![screen shot 2016-10-09 at 1 33 36 am](https://cloud.githubusercontent.com/assets/14068774/19219158/dad61f3a-8dc0-11e6-99dc-b1106368b0da.png)

Steps Taken: When I manually select typescript-tslint as the syntax checker for a buffer, flycheck applies tslint as expected, but flycheck does not use the tide syntax checker next. 

However, I tried fixing all errors raised by the tide syntax checker, and the tslint syntax checker does run. (See second screenshot).

![screen shot 2016-10-09 at 2 00 57 am](https://cloud.githubusercontent.com/assets/14068774/19219327/f0057eec-8dc4-11e6-9de8-f203c30524f2.png)

Hypothesis and Possible Solution: I think errors from the tide syntax checker block flycheck from running the next syntax checker (tslint). Perhaps reversing the order of the syntax checkers would allow errors/warnings from both checkers to display in the buffer.

Thank you for developing and maintaining tide. If I can be of any further assistance, I am happy to help.

**Comment by ananthakumaran** [comment]
Your hypothesis is correct. PR #26 explains the reason for it. In short, tslint expects valid ts file, so it's better to not run tslint on invalid ts files. That said, now that couple of people have asked about it, we could make the LEVEL of typescript-tslint configurable? What do you think?

**Comment by fugalfunkster** [comment]
Context: Thanks for the link to the PR. If I understand your proposal, you would make the LEVEL of typescript-tslint configurable. So, instead of the default of warning, a user's config might set LEVEL to error, or t. This would tell flycheck to execute the next-checker (tslint), regardless of errors raised by tide.  (See flycheck.el:  "NEXT-CHECKER will only be used if there is no current error whose level is more severe than LEVEL. LEVEL may also be t, in which case NEXT-CHECKER is used regardless of the current errors" ).

Steps Taken: I first attempted to modify line 1091 in tide.el. Replacing warning with error or t had no effect. I also replaced the NEXT cons cell with the syntax checker symbol, also to no effect. Ultimately, I was unable to determine why line 1091 in tide.el did not have the expected behavior. Finally, I moved line 1091 to my config files, and set LEVEL to t. This resulted in expected behavior: tide errors and tslint warnings both displayed in buffer.

Proposed Solution: I think that it would be helpful to provide LEVEL configuration, and some documentation (including a warning regarding tslint's expectations) in the readme. If you approve, I will submit a PR removing line 1091 from tide.el, inserting that line below line 5 of the configuration snipppet in readme.md, and providing comments regarding LEVEL configuration.

**Comment by ananthakumaran** [comment]
Sorry about the brief comment. That's exactly what I proposed. 

I don't see why changing LEVEL has no effect. Do you have any compiled version of tide.el file in your load path. Emacs always loads the compiled file(tide.elc) if available. Easy way would be to add something like `message("hello")` and see if it has any effect.

You might run into another problem also. Because `flycheck-add-next-checker` gets executed when we do `(require 'tide)`, the custom variable needs to be set before tide actually gets required. So you might have to move the `(setq tide-flycheck-tslint-level 'error)` to the top of your config file, before you intialize all the packages using `(package-intialize)`


I would prefer not to remove the `flycheck-add-next-checker` call. Because it would undo what has been done by #26 and might break current users configuration. I would happy to accept a PR that adds a custom-variable & leaves the default value to the current value. No need to mention anything in the readme. Just add enough comments in the custom-variable declaration.

**Comment by fugalfunkster** [comment]
You were correct, I was loading a compiled version of tide. Thanks, I had no idea. Changes to the tslint LEVEL in tide.el now behave as expected, so I concur that there is no reason to modify tide.el.

Instead of binding a var outside of the tide config, I decided to simply make another call to `flycheck-add-next-checker` in the config:
```
(defun setup-tide-mode ()
   (interactive)
   (tide-setup)
   (flycheck-mode +1)
   (setq flycheck-check-syntax-automatically '(save mode-enabled))
   (flycheck-add-next-checker 'typescript-tide '(t . typescript-tslint) 'append)
   (eldoc-mode +1)
   (company-mode +1))
```
I suspect I am adding an additional reference to tslint on the checkers list, instead of overwriting the prior addition. But, I did not have problems in situations in which both references to tslint would activate (for example, when tide reports no errors, both the warning LEVEL tslint and the t LEVEL tslint might activate).

Given that this is a hacky approach, I'm not inclined to make a PR. What do you think?

**Comment by ananthakumaran** [comment]
If this solves the problem, then yes feel free to close the issue. We can come back to this if more people wants the same behavior.
