### ISSUE TITLE
Completion casing

### ISSUE THREAD

**Issue by sandao** [ananthakumaran/tide#68]
Hi! 
use company for completiong, given the completion "SomeThing", typing 'somet' will not trigger the completion 'SomeThing'.

What I want is for the following: given the completion "SomeThing", typing "somet" will trigger the completion "SomeThing". That is, the filtering ignores case, but the completion keeps case.

Is there a way of enabling this that I've missed?

Thanks!

**Comment by neeasade** [comment]
Noob here, also trying to figure this out as well. I would think it would be handled on the company side of things, and I was trying to enable it like so:

``` elisp
(setq company-dabbrev-code-ignore-case t)
(add-to-list 'company-dabbrev-code-modes 'tide-mode)
(setq company-dabbrev-code-everywhere t)
```

Am I mistaken and there's an option to pass along to company that is just currently not exposed in `tide`?

**Comment by neeasade** [comment]
ah okay, you can pass along `ignore-case` and `'keep-prefix` [1] in the call here [2]. That's still not what I'm looking for, trying to get completion without lowercase input, will update w/ edit if I get it. 

[1] https://github.com/company-mode/company-mode/commit/bd82c7e096ecf4c6f0a0545f442be4296c741db5
[2] https://github.com/ananthakumaran/tide/blob/master/tide.el#L745

**Comment by neeasade** [comment]
I wanted to submit a PR exposing this as a configurable option, but am not doing this quite right.. 

see https://github.com/neeasade/tide/commit/cc87e25c7808c05dcf8c661c509800e8ed57a35c#diff-66610336c4569b128b819eae293ca9ceR749
