### ISSUE TITLE
FR: More information in autocomplete dropdown annotation

### ISSUE THREAD

**Issue by KevinVillela** [ananthakumaran/tide#82]
In other company backends, the information that is currently shown in the minibuffer (i.e. the type of the currently selected autocomplete option) is shown as annotations in the dropdown. Currently, just the kind of type is shown (enum => E, method => m, etc...), but showing more information would make it easier to see which type you're looking for at a glance.

Thanks very much for the great package!

**Comment by ananthakumaran** [comment]
<img width="714" alt="screen shot 2016-11-27 at 12 24 45 pm" src="https://cloud.githubusercontent.com/assets/149238/20646233/8c14f36e-b49c-11e6-8899-6a50009f34de.png">

You mean, something like the above? Personally, I find it too cluttered. But if enough people want this behavior, then we can add a config option

**Comment by KevinVillela** [comment]
Yes exactly! I can take a stab at it, would you accept a PR?
