### ISSUE TITLE
typescript-tslint is not a valid Flycheck checker

### ISSUE THREAD

**Issue by turboMaCk** [ananthakumaran/tide#89]
Hi!

This might be really silly question but I really don't know how to fix it so I'll be glad if you can point me any direction. I have this error in mini buffer every time I run `tide-setup`. I've installed this package yesterday when everything was working correctly. Even when I turn flycheck off and run `tide-setup` again same error occurs. Not sure if it's issue with tide or flycheck though.

actual error is
```
typescript-tslint is not a valid Flycheck checker 
```

**Comment by cpitclaudel** [comment]
What does `(flycheck-valid-checker-p 'typescript-tslint)` return when you run it in `M-:`?

**Comment by turboMaCk** [comment]
`(flycheck-valid-checker-p 'typescript-tslint) => nil`

**Comment by cpitclaudel** [comment]
Ok.  Now please try `(get  'typescript-tslint 'flycheck-generic-checker-version)` and `flycheck-generic-checker-version`.

**Comment by turboMaCk** [comment]
get returns nil and on `flycheck-generic-checker-version`. I got void function error. Also I don't see that function in `helm M-x`.

**Comment by cpitclaudel** [comment]
flycheck-generic-checker-version is a variable, not a function.  But AFAICT these results mean that the tslint checker isn't defined… How did you install flycheck?

**Comment by turboMaCk** [comment]
I'm using version from melpa a package.el

**Comment by cpitclaudel** [comment]
Ok; please uninstall it and reinstall it, then restart Emacs; maybe something's wrong there?

**Comment by turboMaCk** [comment]
Omg it really helped. Sorry for wasting your time & thank you so much!

**Comment by cpitclaudel** [comment]
No problem :) Enjoy flycheck and tide!
