### ISSUE TITLE
tslint does not run for .tsx files under web-mode

### ISSUE THREAD

**Issue by YosubShin** [ananthakumaran/tide#95]
When editing a `.tsx` file under `web-mode`, Flycheck checker does not run TSLint even when the file has zero errors. (https://github.com/ananthakumaran/tide/issues/67)

I believe this is happening because:
1. `tsx-tide` Flycheck checker does not have a next checker registered with `flycheck-add-next-checker`.
2. `typescript-tslint` does not support `web-mode`.

Above issues can be resolved by adding:
```
(flycheck-add-next-checker 'tsx-tide '(warning . typescript-tslint) 'append)
(flycheck-add-mode 'typescript-tslint 'web-mode)
```

A similar thing could be added for other Flycheck checkers such as `jsx-tide` and `javascript-tide` for completeness.
Is this something that you could consider merging to the master branch? Or, do you think there is a better way of achieving the same thing?

**Comment by ananthakumaran** [comment]
> `(flycheck-add-next-checker 'tsx-tide '(warning . typescript-tslint) 'append)`

Does tslint officially support tsx files? If so, I would be OK to add this.

> (flycheck-add-mode 'typescript-tslint 'web-mode)

This should be either added in the typescript-tslint's definition or user's config.

regarding `jsx-tide` & `javascript-tide`, I am not sure how useful they are. eslint already reports syntax errors.

**Comment by AndyMoreland** [comment]
(I contribute to tslint and know the maintainers professionally) yeah, it does officially support tsx files.

**Comment by yatesco** [comment]
This works brilliantly well as far as I can see:

``` elisp
    (use-package tide :diminish t)
    (defun setup-tide-mode ()
      (interactive)
       (tide-setup)
       (flycheck-add-next-checker 'typescript-tide '(t . typescript-tslint) 'append)
       (eldoc-mode +1)
       (company-mode +1)
       (tide-hl-identifier-mode +1))

    ;; aligns annotation to the right hand side
    (setq company-tooltip-align-annotations t)

    ;; formats the buffer before saving
    (add-hook 'before-save-hook 'tide-format-before-save)
    (add-hook 'typescript-mode-hook #'setup-tide-mode)

    (add-to-list 'auto-mode-alist '("\\.tsx\\'" . web-mode))
    (add-hook 'typescript-mode-hook
	      (lambda ()
		(when (string-equal "tsx" (file-name-extension buffer-file-name))
		    (setup-tide-mode))))
    ;; funky typescript linting in web-mode
    (flycheck-add-mode 'typescript-tslint 'web-mode)
```
