### ISSUE TITLE
Please consider providing an option to disable sync-after-change

### ISSUE THREAD

**Issue by nikclayton** [ananthakumaran/tide#99]
tide syncs the buffer after every change.

I find this to be quite distracting. I'll be editing in one window, with an eye on the browser in the other, and as soon as I start to type the contents are synced, compilation starts happening, and the browser starts to refresh.

Please consider providing an option to disable this, so that syncing only happens when files are saved.

Thanks.

**Comment by ananthakumaran** [comment]
> tide syncs the buffer after every change.
I believe it's not after every change, but before making any request to tsserver, the buffer contents are synched. It's essential for many features like autocomplete to work correctly.
> compilation starts happening
Could you change the `compileOnSave` flag in tsconfig file and see if that solves the issue?

**Comment by MarcusRiemer** [comment]
I am also experiencing issues with this behavior, but the `compileOnSave` flag wont help with this. In my case its an external filesystem watcher (namely `angular-cli`) which keeps spinning everytime I use tide to make some changes. Having (temporarily) incorrect / outdated autocomplete data would be fine for me, so I would like +1 @nikclayton call for an option to disable this.

**Comment by ananthakumaran** [comment]
>  In my case its an external filesystem watcher (namely angular-cli) which keeps spinning everytime I use tide to make some changes

interesting. Tide sync doesn't persist the change to the disk. It creates a new tmp file with the contents in the buffer and sends that file to tsserver. I am curious how an external watcher can pick this up.

**Comment by MarcusRiemer** [comment]
> interesting. Tide sync doesn't persist the change to the disk. It creates a new tmp file with the contents in the buffer and sends that file to tsserver. I am curious how an external watcher can pick this up.

I'll do a more thorough check whether this is really due to Tide.

> auto-complete might completly stop without sync. We send the char position to the tsserver and ask for completions, so it is essential both the buffer and internal model of tsserver to be identical.

Ah, bummer. I don't know how I expected `tsserver` to work, but using the cursor position of course makes an exact model mandatory.

**Comment by MarcusRiemer** [comment]
Tide is indeed not the problem on my end, from my POV this can be closed.

**Comment by ananthakumaran** [comment]
@nikclayton do you still have this issue?

**Comment by ananthakumaran** [comment]
closing this due to no response
